export interface Anexo {
  id: string;
  numero: string;
  titulo: string;
  fonte: "te" | "tcc";
  esquema?: string;
  instrucoes: string[];
  referencia: string;
}

// ========== TERAPIA DO ESQUEMA — Schütz (Sinopsys, 2023) ==========
const te = (n: number, titulo: string, esquema: string, instrucoes: string[]): Anexo => ({
  id: `te-anexo-${n}`, numero: `Anexo ${n}`, titulo, fonte: "te", esquema,
  instrucoes, referencia: "Schütz, N. T. (2023). Manual de Técnicas em Terapia do Esquema. Sinopsys.",
});

// ========== TCC — Leahy (Artmed, 2ª ed.) ==========
const tcc = (cap: string, n: number, titulo: string, instrucoes: string[]): Anexo => ({
  id: `tcc-${cap}-${n}`, numero: `Form. ${cap}.${n}`, titulo, fonte: "tcc",
  instrucoes, referencia: "Leahy, R. L. (2019). Técnicas de Terapia Cognitiva (2ª ed.). Artmed.",
});

export const anexos: Anexo[] = [
  // ===== TE: Desconexão e Rejeição =====
  te(1, "Gatilhos que ativam meu esquema de abandono/instabilidade", "Abandono",
    ["Liste situações em que sente seu esquema de abandono ativado.", "Identifique os gatilhos presentes nessas situações.", "Escreva: o que fazer quando isso acontecer?"]),
  te(2, "Meus direitos e necessidades emocionais nos relacionamentos", "Abandono",
    ["Liste suas necessidades e direitos emocionais em uma relação.", "Liste coisas que a outra pessoa faz que satisfazem essas necessidades."]),
  te(3, "Atendendo às necessidades emocionais nas relações", "Abandono",
    ["Escreva suas necessidades emocionais.", "Liste comportamentos de convivência que respeitem as necessidades de ambos os lados.", "Identifique as necessidades emocionais de pessoas significativas na sua vida (nome + necessidades)."]),
  te(4, "Usando estratégias válidas para enfraquecer meu esquema de abandono", "Abandono",
    ["Liste estratégias que usa e que são válidas, mas também inválidas, para lidar com o esquema.", "Por que são também inválidas?", "Qual estratégia exclusivamente válida poderia usar no lugar?"]),
  te(5, "Violações dos meus direitos", "Desconfiança/Abuso",
    ["Liste situações em que seus direitos foram violados.", "Quem foi responsável? Por quê?", "O que isso representou na sua vida?"]),
  te(6, "Reformulação de histórias — Desconfiança/Abuso", "Desconfiança/Abuso",
    ["Descreva acontecimentos ruins que vivenciou.", "Reformule cada acontecimento se colocando como forte: como teria reagido?"]),
  te(7, "Acumulando relações mais positivas", "Desconfiança/Abuso",
    ["Liste situações em que alguém fez algo bom por você (mencione quem).", "Como você se sentiu?", "Como pode vivenciar isso mais vezes?"]),
  te(8, "Clarificando minhas necessidades emocionais", "Privação Emocional",
    ["Escreva (ou desenhe dentro de uma silhueta) o que você acredita ser importante receber emocionalmente — de si e dos outros."]),
  te(9, "Automonitoramento do meu esquema de privação emocional", "Privação Emocional",
    ["Liste situações em que se sente privado emocionalmente.", "Quais gatilhos costumam ativar isso?", "Sensações emocionais que observa.", "Sensações físicas que observa.", "Memórias infantis ligadas à situação.", "Modo de funcionamento comum nesses momentos."]),
  te(10, "A vida que eu quero (e mereço)", "Privação Emocional",
    ["Descreva a vida que gostaria de ter.", "O que precisa emocionalmente?", "Onde está hoje (quão próximo ou distante do que quer)?", "O que quer?", "O que pode fazer para chegar lá?"]),
  te(11, "Tentativas de superar o esquema de defectividade/vergonha", "Defectividade",
    ["Liste exemplos de quando se sente defectivo.", "Como tenta hipercompensar esse sentimento?", "Quais resultados tem (vantagens e desvantagens)?"]),
  te(12, "Construindo uma reação alternativa diante dos erros", "Defectividade",
    ["Liste erros que cometeu.", "Pensamentos que teve ao cometer.", "Emoção que sentiu.", "Como poderia ter lidado de forma menos crítica?"]),
  te(13, "Aceitando o amor das outras pessoas", "Defectividade",
    ["O que significa receber amor?", "Formas pelas quais as pessoas tentam te oferecer amor.", "Como pode ser mais receptivo ao amor?"]),
  te(14, "Fontes da minha rejeição", "Defectividade",
    ["Para aspectos físicos, mentais e sociais: como se sentia em relação aos outros?", "Como lidou com isso?", "Forma mais assertiva de lidar?"]),
  te(15, "E se conviver não for tão ruim assim?", "Isolamento Social",
    ["Qual é sua previsão negativa sobre conviver com pessoas?", "Como se sente ao prever assim?", "Essas previsões realmente te protegem?", "Quantas vezes previsões negativas NÃO se concretizaram?", "O que perde ao deixar de tentar?", "Como seria se se permitisse tentar mais?", "O que poderia colher de bom?"]),
  te(16, "Coisas positivas que a convivência social me trouxe", "Isolamento Social",
    ["Liste situações sociais boas que viveu.", "Quais lições elas mostram?"]),
  te(17, "Passo a passo da minha mudança", "Isolamento Social",
    ["Cite passos concretos que pode dar para interagir mais socialmente com as pessoas."]),
  // ===== TE: Autonomia e Desempenho Prejudicados =====
  te(18, "Qual é a origem da minha dependência/incompetência?", "Dependência",
    ["Quem cuidava de você quando era criança?", "Estilo dessas pessoas com você.", "Por que lidavam assim (o que diz sobre elas)?", "Como as pessoas lidam com você hoje?", "O que isso gera na sua vida atualmente?"]),
  te(19, "Deixando claros meus recursos", "Dependência",
    ["Pessoas ligadas ao seu esquema: o que era delas vs. o que era realmente seu.", "O que é delas hoje vs. o que é seu hoje.", "Lições aprendidas."]),
  te(20, "Ciclo da minha ansiedade no esquema de dependência", "Dependência",
    ["Situações em que sente muita ansiedade.", "Pensamentos durante essas situações.", "Como costuma lidar com os sintomas.", "Pessoas às quais recorre.", "Resultados ao recorrer a elas.", "Como isso impacta no esquema."]),
  te(21, "Enfrentando meus medos", "Vulnerabilidade ao Dano",
    ["Planeje o enfrentamento passo a passo (passos 1-5).", "Pensamento de enfrentamento.", "Comportamentos a aplicar.", "Resultados obtidos."]),
  te(22, "No que me sinto vulnerável?", "Vulnerabilidade ao Dano",
    ["Para cada área, descreva como se sente e por quê: Saúde e doenças, Perigos, Pobreza, Perder o controle."]),
  te(23, "Medos da infância vs. medos atuais", "Vulnerabilidade ao Dano",
    ["Liste medos da infância com nível de ansiedade (0-10).", "Liste medos atuais com nível de ansiedade.", "O que é semelhante e o que mudou? Por quê?"]),
  te(24, "Quase nada do que penso é 100% verdade", "Vulnerabilidade ao Dano",
    ["Escreva pensamentos ligados a preocupações.", "Reescreva cada um convencendo-se de que é apenas um pensamento, não verdade absoluta."]),
  te(25, "Diminuindo a intensidade das minhas preocupações", "Vulnerabilidade ao Dano",
    ["Escreva sua preocupação atual.", "Avalie de 0-100% a intensidade.", "Após questionar, reavalie."]),
  te(26, "Mostrando a importância da independência", "Emaranhamento",
    ["Liste benefícios da independência.", "Como mostrar isso para pessoas emaranhadas a você?", "Quando fará isso?"]),
  te(27, "Cada peça precisa estar no seu lugar", "Emaranhamento",
    ["Imagine um quebra-cabeça: cada peça é uma pessoa da sua vida.", "Escreva o nome e a função de cada pessoa, respeitando a individualidade."]),
  te(28, "Monitorando minha satisfação durante a solidão", "Emaranhamento",
    ["Liste momentos do dia em que está sozinho(a).", "Como se sente em cada momento?", "Por que acha que se sente assim?"]),
  te(29, "Fortalecendo minha autoeficácia", "Fracasso",
    ["Liste situações em que se descreve de forma depreciativa.", "Reescreva cada uma considerando que terá eficácia ao passar por ela."]),
  te(30, "Aprendendo com os erros", "Fracasso",
    ["Visão que tem dos erros cometidos até hoje.", "Principais erros.", "Fatores envolvidos.", "O que aprendeu graças a eles.", "Visão mais assertiva agora."]),
  te(31, "Rotina mais saudável", "Fracasso",
    ["Liste atividades diárias para aumentar satisfação pessoal.", "Obstáculos no cumprimento.", "Estratégias para lidar com esses obstáculos."]),
  // ===== TE: Limites Prejudicados =====
  te(32, "Base do meu esquema de arrogo/grandiosidade", "Arrogo/Grandiosidade",
    ["Quem eram seus cuidadores na infância? Perfil de cada um.", "Ligação do perfil com a formação do esquema.", "Considerações sobre isso."]),
  te(33, "O que é importante para mim?", "Arrogo/Grandiosidade",
    ["Lista hierárquica das coisas mais importantes. Como espera que proporcionem amor e segurança?", "Observe o ciclo: Busca por sucesso → Reconhecimento → Menos conexão afetiva → Mais busca. Quando isso acontece com você?"]),
  te(34, "Treinando a gentileza", "Arrogo/Grandiosidade",
    ["Formas de ser gentil com os outros.", "Palavras/frases gentis que pode utilizar.", "Ganhos que pode ter ao ser gentil."]),
  te(35, "Como fui privado das frustrações?", "Autocontrole Insuficiente",
    ["Frustrações que deixou de passar na infância/adolescência.", "Quem evitou essas frustrações.", "Como isso te prejudica hoje."]),
  te(36, "Prós e contras do autocontrole", "Autocontrole Insuficiente",
    ["Prós de agir por impulso. Impacto na vida (0-10).", "Contras de agir por impulso. Impacto na vida (0-10)."]),
  te(37, "Análise para escolhas mais saudáveis", "Autocontrole Insuficiente",
    ["Situação em que se sente empolgado ou frustrado.", "Pensamentos que passam antes de agir.", "Esses pensamentos são verdadeiros?", "O quanto fazer isso pode ajudar?", "Quais consequências terá?", "Como pessoas que admira avaliariam?", "Existem outras formas de pensar?", "Como vai se sentir depois de algum tempo?"]),
  // ===== TE: Direcionamento para o Outro =====
  te(38, "Por que me subjugo?", "Subjugação",
    ["Situações em que foi coagido a ser submisso.", "Motivos.", "Pessoas envolvidas.", "Considerações sobre esses acontecimentos."]),
  te(39, "Gatilhos para meu esquema de subjugação", "Subjugação",
    ["Para cada área (família, relacionamento, parentalidade, amizades, trabalho): gatilhos que ativam o esquema.", "Plano para evitar gatilhos.", "Plano para lidar com eles."]),
  te(40, "A vida com o reconhecimento das minhas necessidades e emoções", "Subjugação",
    ["Liste suas necessidades e emoções.", "Benefícios de reconhecê-las como algo importante."]),
  te(41, "Vantagens e desvantagens do meu autossacrifício", "Autossacrifício",
    ["Para 3 situações em que ajuda alguém: liste vantagens e desvantagens de cada."]),
  te(42, "A vida é uma troca", "Autossacrifício",
    ["De um lado: o que ofereço. Do outro: o que recebo.", "As coisas estão justas?"]),
  te(43, "Melhorando minha autoestima", "Busca de Aprovação",
    ["Avalie sua autoestima na escala.", "O que está por trás dessa avaliação?", "Quais os riscos?"]),
  te(44, "Aceitando quem sou", "Busca de Aprovação",
    ["Imperfeições que observa em si.", "Como acha que os outros percebem? Eles também têm imperfeições?", "Pessoas que admira — como lidam com imperfeições?", "Se outros têm imperfeições, você tem o mesmo direito?", "Como pode lidar melhor com as suas, via aceitação?", "Resultados esperados."]),
  te(45, "Avaliando minha espiral de aprovação", "Busca de Aprovação",
    ["Liste problemas/frustrações/dificuldades que tem ao esperar se sentir bem por meio dos outros."]),
  // ===== TE: Supervigilância e Inibição =====
  te(46, "Percebendo no que pratico o negativismo/pessimismo", "Negativismo",
    ["Por que acha que isso aconteceu?", "O quanto focar nisso ajuda?", "Existe lição importante?", "Como pessoas que admira lidam com isso?"]),
  te(47, "Foco nos recursos para enfrentar os perigos", "Negativismo",
    ["De um lado: perigos na sua vida. Do outro: seus recursos para lidar."]),
  te(48, "Outros pontos de vista", "Negativismo",
    ["Coisas que te incomodam atualmente.", "Três outros pontos de vista sobre cada.", "Vantagens de avaliar mais perspectivas."]),
  te(49, "Conversa com meus dois lados", "Inibição Emocional",
    ["Dê voz ao lado que bloqueia emoções: por que ele faz isso?", "Dê voz ao lado que quer sentir: o que ele precisa?", "Escreva um diálogo entre os dois."]),
  te(50, "Autoexpressão", "Inibição Emocional",
    ["Pessoas que te invalidavam.", "O que precisa expressar.", "Escreva o que diria a elas.", "Como se sente agora?"]),
  te(51, "Aproveitando eventos agradáveis", "Inibição Emocional",
    ["Eventos agradáveis que viveu. Como costuma lidar? Desvantagens da forma como lida.", "Formas alternativas. Benefícios esperados.", "Ideias de eventos agradáveis para testar."]),
  te(52, "Cartão de enfrentamento para me permitir sentir", "Inibição Emocional",
    ["Complete: 'Estou consciente de que as emoções são ___.'", "'Elas exercem funções que me ajudam a ___.'", "'Possibilitando os seguintes benefícios: ___.'", "'Quando alguma emoção estiver ativada, posso: ___.'"]),
  te(53, "Por que sigo essa regra?", "Padrões Inflexíveis",
    ["Suas regras sobre como as coisas deveriam ser.", "Quem te ensinou?", "O quanto é embasado na realidade?", "O quanto pode ter sido distorcido?", "Custos e benefícios.", "Por que segue essa regra?", "Outras formas de enxergar?"]),
  te(54, "Otimizando minha energia", "Padrões Inflexíveis",
    ["Divida em duas colunas: 'Tenho controle' e 'Não tenho controle'.", "Foque energia apenas no que pode controlar."]),
  te(55, "Flexibilidade psicológica", "Padrões Inflexíveis",
    ["O que é uma vida significativa para você?", "O quanto sua vida é significativa hoje?", "Como alcançar?", "Quais são seus valores?", "Prioridades e quanto tempo dedica a elas.", "O que precisa enfrentar para mudar?", "Como lidar melhor com frustração e desconforto?"]),
  te(56, "Conectando-me com meus valores", "Padrões Inflexíveis",
    ["Para cada área (relações, parentalidade, amizades, carreira, educação, lazer, espiritualidade, saúde): valores que tem e desvios quando o esquema está ativado."]),
  te(57, "Xô, culpa!", "Postura Punitiva",
    ["Explique sua culpa.", "Quem são os responsáveis?", "Quanto cada um foi responsável (%)?", "Foi intencional?"]),
  te(58, "Aspectos envolvidos na postura punitiva", "Postura Punitiva",
    ["Situação em que usou sua postura punitiva.", "Fatores/pessoas envolvidos no que aconteceu."]),
  te(59, "Compreendendo os fatos em vez de punir", "Postura Punitiva",
    ["Pensamentos automáticos diante de um erro.", "Variáveis envolvidas sobre as quais NÃO tem controle.", "Visão mais equilibrada sobre o erro."]),
  te(60, "Parando com os rótulos", "Postura Punitiva",
    ["Rótulos que coloca em si e nos outros.", "Reescreva cada um como apenas comportamentos que ocorreram."]),

  // ========== TCC — Leahy (Artmed, 2ª ed.) ==========
  // Cap 2: Identificação de pensamentos automáticos
  tcc("2", 1, "Distinção entre eventos, pensamentos e sentimentos",
    ["Descreva a situação. Separe: EVENTO (fato), PENSAMENTO (interpretação), SENTIMENTO (emoção)."]),
  tcc("2", 2, "Como os pensamentos criam sentimentos",
    ["Para uma situação, escreva o pensamento que teve e o sentimento que surgiu.", "Como um pensamento DIFERENTE criaria um sentimento diferente?"]),
  tcc("2", 3, "Técnica A-B-C",
    ["A = Evento ativador. B = Crença/pensamento. C = Consequência emocional.", "Preencha para 3 situações recentes."]),
  tcc("2", 4, "Outros fatos possíveis",
    ["Para seu pensamento negativo, liste todos os outros fatos/explicações possíveis para a situação."]),
  tcc("2", 5, "Avaliação das emoções e crenças",
    ["Identifique a emoção e avalie de 0-100%. Identifique a crença e avalie de 0-100%."]),
  tcc("2", 6, "Registro do grau de crença em um pensamento",
    ["Antes e depois de questionar o pensamento: avalie de 0-100% o quanto acredita nele."]),
  tcc("2", 7, "Lista de verificação de distorções cognitivas",
    ["Verifique quais distorções estão presentes: leitura mental, catastrofização, filtro negativo, desqualificação do positivo, tudo-ou-nada, generalização, personalização, rotulação, 'deveria', raciocínio emocional, ampliação/minimização."]),
  tcc("2", 8, "Categorização das suas distorções do pensamento",
    ["Para cada pensamento negativo recente, identifique QUAL distorção está operando."]),
  tcc("2", 9, "Uso da seta descendente",
    ["Pensamento: ___. 'Se isso fosse verdade, por que me incomodaria?' Repita até chegar na crença central."]),
  tcc("2", 10, "Exame da sequência de probabilidades",
    ["Qual a probabilidade (%) de cada etapa da sua previsão catastrófica acontecer? Multiplique-as."]),
  tcc("2", 11, "Adivinhação do pensamento negativo",
    ["Qual pensamento negativo você está 'adivinhando'? Quais evidências reais sustentam essa adivinhação?"]),
  // Cap 3: Avaliação e contestação
  tcc("3", 1, "Definição dos termos",
    ["Pensamento negativo. Liste cada termo usado, sua definição, e problemas nessas definições."]),
  tcc("3", 2, "Tornando as definições claras",
    ["Termo que usa quando perturbado. Como o define. Outras pessoas saberiam do que está falando?"]),
  tcc("3", 3, "Análise de custo-benefício de um pensamento",
    ["Pensamento: ___. Custos de mantê-lo. Benefícios de mantê-lo."]),
  tcc("3", 4, "Custos e benefícios no curto e longo prazo",
    ["Divida em 4 quadrantes: custos curto prazo, benefícios curto prazo, custos longo prazo, benefícios longo prazo."]),
  tcc("3", 5, "Exame das evidências",
    ["Evidências A FAVOR do pensamento. Evidências CONTRA o pensamento."]),
  tcc("3", 6, "Exame da qualidade das evidências",
    ["Para cada evidência: é um fato concreto ou uma interpretação? É atual ou antiga?"]),
  tcc("3", 7, "Advogado de defesa",
    ["Desempenhe o papel do seu próprio advogado de defesa. Liste todos os argumentos a seu favor."]),
  tcc("3", 8, "Contestações relevantes?",
    ["Suas contestações realmente respondem ao pensamento negativo? Ou são irrelevantes?"]),
  tcc("3", 9, "Dramatização de ambos os lados",
    ["Escreva um diálogo entre a parte acusadora e a parte defensora."]),
  tcc("3", 10, "Avaliação dos rótulos negativos",
    ["Rótulo que usa. Aplica-se 100% do tempo? Liste exceções."]),
  tcc("3", 11, "Busca de variações",
    ["Liste vezes em que o rótulo NÃO se aplicou. O que isso diz?"]),
  tcc("3", 12, "Modificação de pensamentos via comportamento",
    ["Que comportamento concreto pode mudar para testar se o pensamento é verdade?"]),
  // Cap 4: Pressupostos, regras e padrões
  tcc("4", 1, "Monitoramento de pressupostos, regras e padrões",
    ["Liste suas regras internas: 'Eu deveria ___', 'Se eu ___, então ___'."]),
  tcc("4", 2, "Contestação de afirmações do tipo 'deveria'",
    ["Para cada 'deveria': é preferência ou mandamento? Quem te ensinou? O que acontece se não cumprir?"]),
  tcc("4", 3, "Identificação de crenças condicionais",
    ["'Se eu ___, então ___.' Essas conexões são reais ou assumidas?"]),
  tcc("4", 4, "Avaliação de pressupostos secundários",
    ["Quais pressupostos estão por trás das suas regras?"]),
  tcc("4", 5, "Clarificação de valores",
    ["O que realmente importa para você? Suas regras estão alinhadas?"]),
  tcc("4", 6, "Inventário de perfeccionismo",
    ["Em quais áreas exige perfeição? Qual o custo?"]),
  tcc("4", 8, "Aprendizado a partir dos lapsos",
    ["Descreva um lapso recente. O que aprendeu? Como usar isso a seu favor?"]),
  tcc("4", 10, "Implicações do perfeccionismo",
    ["Quais são as implicações do perfeccionismo na sua saúde, relações e bem-estar?"]),
  tcc("4", 11, "Transformação do trabalho em diversão",
    ["Transforme crítica e desapontamento em curiosidade. Como?"]),
  tcc("4", 12, "Transformação de antigas regras em novas",
    ["Antiga regra: ___. Nova regra (mais flexível): ___."]),
  tcc("4", 13, "Minha nova declaração de direitos",
    ["Liste direitos que você merece: 'Tenho direito de ___'."]),
  // Cap 5: Processamento de informação e erros lógicos
  tcc("5", 1, "Exame do viés de confirmação",
    ["Que informações IGNOROU por não confirmarem sua crença?"]),
  tcc("5", 2, "Utilização de todas as informações",
    ["Liste TUDO que sabe sobre a situação — não apenas o negativo."]),
  tcc("5", 3, "Estimativas de probabilidade dos eventos",
    ["Qual a chance real (%) de o pior acontecer? Baseado em quê?"]),
  tcc("5", 4, "Exame dos erros de lógica",
    ["Conclusão sem dados suficientes? Confusão correlação/causa? Generalização?"]),
  tcc("5", 5, "Padrões que podem não existir",
    ["Você está vendo um padrão onde pode haver coincidência?"]),
  tcc("5", 6, "Desafio às falsas dicotomias",
    ["Está pensando em tudo-ou-nada? Quais são os tons de cinza?"]),
  tcc("5", 7, "Redução dos pensamentos ao absurdo",
    ["Leve o pensamento ao extremo lógico. Faz sentido?"]),
  tcc("5", 8, "Indução de humor e pensamentos alternativos",
    ["Se estivesse de bom humor, como interpretaria a mesma situação?"]),
  tcc("5", 9, "Efeito da recenticidade",
    ["Está dando peso excessivo ao que aconteceu recentemente?"]),
  tcc("5", 10, "Falácias nos argumentos",
    ["Identifique falácias lógicas nas suas crenças negativas."]),
  // Cap 6: Tomada de decisão
  tcc("6", 1, "Foco nos objetivos de curto prazo",
    ["Quais são seus objetivos para os próximos 30 dias?"]),
  tcc("6", 2, "Foco nos objetivos de longo prazo",
    ["Quais são seus objetivos para o próximo ano?"]),
  tcc("6", 3, "Compromisso com o futuro decidindo agora",
    ["Que decisão o seu 'eu do futuro' gostaria que você tomasse hoje?"]),
  tcc("6", 4, "Custos não recuperáveis",
    ["Está mantendo algo só porque 'já investiu muito'? O que faria começando do zero?"]),
  tcc("6", 5, "Humor e tomada de decisão",
    ["Está decidindo num momento de emoção intensa? Como se sentiria sobre isso em 1 semana? 1 mês?"]),
  tcc("6", 6, "Perdas e ganhos na tomada de decisão",
    ["Está focando mais no que pode perder do que no que pode ganhar?"]),
  tcc("6", 7, "Evitação do arrependimento",
    ["Está evitando decidir por medo de se arrepender? Qual o custo de não decidir?"]),
  tcc("6", 8, "Decisões pelo self atual e futuro",
    ["O que seu 'eu atual' quer? O que seu 'eu do futuro' agradeceria?"]),
  tcc("6", 9, "Atividades recompensadoras",
    ["Liste atividades recompensadoras: passadas, presentes e futuras."]),
  tcc("6", 10, "Escolhas de risco versus risco",
    ["Compare o risco de agir vs. o risco de não agir."]),
  // Cap 7: Desapego consciente
  tcc("7", 1, "Desapego consciente",
    ["Observe o pensamento sem reagir. 'Estou tendo o pensamento de que ___'."]),
  tcc("7", 2, "Não atenda a ligação",
    ["Imagine o pensamento como um telefone tocando. Não é obrigado a atender."]),
  tcc("7", 3, "Balão de pensamentos",
    ["Imagine o pensamento num balão de quadrinhos flutuando. Observe de fora."]),
  tcc("7", 4, "Pensamentos versus realidade",
    ["Esse pensamento é um FATO ou produção da mente?"]),
  tcc("7", 5, "Estes pensamentos são relevantes?",
    ["Esse pensamento é realmente relevante para sua vida agora?"]),
  tcc("7", 6, "O pensamento visitante",
    ["O pensamento é um visitante. Reconheça-o sem convidar pra entrar."]),
  tcc("7", 7, "O pensamento palhaço",
    ["Imagine o pensamento dito por uma voz cômica. Perde força?"]),
  tcc("7", 8, "Respostas problemáticas a pensamento indesejado",
    ["Quando tem pensamento indesejado: suprime, rumina ou neutraliza? Qual o resultado?"]),
  tcc("7", 9, "A técnica tédio",
    ["Repita o pensamento perturbador por 2 min seguidos. Perceba como perde força."]),
  // Cap 8: Preocupação e ruminação
  tcc("8", 1, "Automonitoramento de preocupações",
    ["Registre: tema, frequência, intensidade (0-10), o que fez."]),
  tcc("8", 2, "Custos e benefícios da preocupação",
    ["Preocupar-se ajuda a resolver ou paralisa?"]),
  tcc("8", 3, "Transformação de preocupações em previsões",
    ["Transforme cada preocupação em previsão testável."]),
  tcc("8", 5, "Teste das previsões negativas",
    ["Teste sua previsão. Registre o resultado real."]),
  tcc("8", 6, "Previsões negativas passadas",
    ["Liste previsões passadas. Quantas se concretizaram?"]),
  tcc("8", 7, "Possíveis desfechos",
    ["Liste TODOS os desfechos possíveis, não apenas o pior."]),
  tcc("8", 9, "Soluções imperfeitas",
    ["Qual seria uma solução imperfeita mas aceitável?"]),
  tcc("8", 10, "Como lidei com eventos negativos no passado",
    ["Liste eventos negativos passados e como você lidou. Sobreviveu a todos."]),
  tcc("8", 13, "Preocupações produtivas e improdutivas",
    ["Classifique: PRODUTIVA (posso agir) ou IMPRODUTIVA (não controlo)."]),
  tcc("8", 14, "Tempo da preocupação",
    ["Adie preocupações para um horário fixo de 20 min. Fora dele, anote e guarde."]),
  tcc("8", 16, "Inundação com incertezas",
    ["Repita 'É possível que ___' até que a incerteza perca o poder."]),
  tcc("8", 20, "Máquina do tempo",
    ["Imagine-se daqui a 5 anos olhando para esta preocupação. Qual a importância?"]),
  tcc("8", 24, "Prática da aceitação",
    ["Aceite a incerteza como parte da vida. O que pode fazer APESAR dela?"]),
  // Cap 9: Continuum e torta
  tcc("9", 1, "Gráfico de torta",
    ["Liste TODOS os fatores que contribuíram. Distribua 100% entre eles."]),
  tcc("9", 2, "Exercício do continuum",
    ["Em vez de sim/não, coloque a qualidade num continuum de 0-100."]),
  tcc("9", 3, "O que ainda posso fazer",
    ["Mesmo na pior hipótese, o que AINDA está ao seu alcance?"]),
  tcc("9", 5, "Comparações com o ponto zero",
    ["Compare com 'não ter nada'. O quanto avançou?"]),
  tcc("9", 6, "Despolarização das comparações",
    ["Liste 10 qualidades. Em quantas você é melhor e em quantas a outra pessoa é?"]),
  tcc("9", 7, "Como outros lidaram com isso?",
    ["Alguém passou por algo parecido? Como lidou?"]),
  tcc("9", 12, "Viagem ao futuro",
    ["Imagine-se daqui a 1, 5, 10 anos. Como verá esta situação?"]),
  // Cap 10: Esquemas e personalidade
  tcc("10", 3, "O que são esquemas?",
    ["Identifique padrões repetitivos na sua vida. Qual crença central está por trás?"]),
  tcc("10", 4, "Esquiva e compensação do meu esquema",
    ["Como EVITA ativar o esquema? Como COMPENSA?"]),
  tcc("10", 5, "Motivação para modificar esquemas",
    ["Razões para mudar. O que ganha mantendo? O que ganha transcendendo?"]),
  tcc("10", 6, "Lembranças precoces de esquemas",
    ["Memórias da infância ligadas ao esquema."]),
  tcc("10", 7, "Carta à fonte dos esquemas",
    ["Escreva carta (sem enviar) à pessoa/situação que originou o esquema."]),
  tcc("10", 8, "Contestação dos esquemas pessoais",
    ["Liste evidências que contradizem seu esquema."]),
  tcc("10", 9, "Vida por lentes de um esquema diferente",
    ["Como seria sua vida operando a partir de um esquema positivo?"]),
  tcc("10", 11, "Transcendência do esquema",
    ["Descreva como seria viver ALÉM deste esquema."]),
  // Cap 11: Processamento emocional
  tcc("11", 1, "Diário de emoções",
    ["Situação, emoção, intensidade (0-100), pensamentos, resposta."]),
  tcc("11", 2, "Emoções que evito",
    ["Quais emoções tem dificuldade de sentir? O que aconteceria se sentisse?"]),
  tcc("11", 5, "Identificação dos pontos de tensão",
    ["Onde 'guarda' cada emoção no corpo?"]),
  tcc("11", 9, "Aceitação das emoções",
    ["'Faz sentido eu sentir ___ porque ___.' Valide sem julgar."]),
  tcc("11", 10, "Reformulação da história",
    ["Reescreva experiência emocional difícil com perspectiva de aceitação e crescimento."]),
];
