export interface EscalaDominio {
  id: string;
  nome: string;
  esquemas: { id: string; nome: string; itens: number[]; invertido?: boolean }[];
}

export interface EscalaConfig {
  id: string;
  sigla: string;
  nome: string;
  instrucoes: string;
  itens: string[];
  opcoes: { label: string; valor: number }[];
  dominios?: EscalaDominio[];
  scoring: "schema-avg" | "threshold";
  rodadas?: string[];
}

const opcoes6 = [
  { label: "Completamente falso", valor: 1 },
  { label: "Em grande parte falso", valor: 2 },
  { label: "Mais verdadeiro do que falso", valor: 3 },
  { label: "Moderadamente verdadeiro", valor: 4 },
  { label: "Em grande parte verdadeiro", valor: 5 },
  { label: "Me descreve perfeitamente", valor: 6 },
];

export const ysq: EscalaConfig = {
  id: "ysq",
  sigla: "YSQ-S3",
  nome: "Questionario de Esquemas de Young",
  instrucoes:
    "Leia cada afirmacao e avalie o quanto ela descreve voce no ultimo ano. Quando voce nao tiver certeza, baseie sua resposta nos seus sentimentos, e nao no que voce acredita racionalmente que seja verdade.",
  opcoes: opcoes6,
  scoring: "schema-avg",
  dominios: [
    {
      id: "d1",
      nome: "Desconexao e Rejeicao",
      esquemas: [
        { id: "ed", nome: "Privacao Emocional", itens: [1, 19, 37, 55, 73] },
        { id: "ab", nome: "Abandono / Instabilidade", itens: [2, 20, 38, 56, 74] },
        { id: "ma", nome: "Desconfianca / Abuso", itens: [3, 21, 39, 57, 75] },
        { id: "si", nome: "Isolamento Social", itens: [4, 22, 40, 58, 76] },
        { id: "ds", nome: "Defectividade / Vergonha", itens: [5, 23, 41, 59, 77] },
      ],
    },
    {
      id: "d2",
      nome: "Autonomia e Desempenho Prejudicados",
      esquemas: [
        { id: "fa", nome: "Fracasso", itens: [6, 24, 42, 60, 78] },
        { id: "di", nome: "Dependencia / Incompetencia", itens: [7, 25, 43, 61, 79] },
        { id: "vu", nome: "Vulnerabilidade ao Perigo/Doenca", itens: [8, 26, 44, 62, 80] },
        { id: "em", nome: "Emaranhamento / Self Subdesenvolvido", itens: [9, 27, 45, 63, 81] },
      ],
    },
    {
      id: "d3",
      nome: "Limites Prejudicados",
      esquemas: [
        { id: "et", nome: "Arrogo / Grandiosidade", itens: [14, 32, 50, 68, 86] },
        { id: "is", nome: "Autocontrole / Autodisciplina Insuficientes", itens: [15, 33, 51, 69, 87] },
      ],
    },
    {
      id: "d4",
      nome: "Direcionamento para o Outro",
      esquemas: [
        { id: "sb", nome: "Subjugacao", itens: [10, 28, 46, 64, 82] },
        { id: "ss", nome: "Autossacrificio", itens: [11, 29, 47, 65, 83] },
        { id: "as", nome: "Busca de Aprovacao / Reconhecimento", itens: [16, 34, 52, 70, 88] },
      ],
    },
    {
      id: "d5",
      nome: "Supervigilancia e Inibicao",
      esquemas: [
        { id: "np", nome: "Negativismo / Pessimismo", itens: [17, 35, 53, 71, 89] },
        { id: "ei", nome: "Inibicao Emocional", itens: [12, 30, 48, 66, 84] },
        { id: "us", nome: "Padroes Inflexiveis / Postura Hipercritica", itens: [13, 31, 49, 67, 85] },
        { id: "pu", nome: "Punicao", itens: [18, 36, 54, 72, 90] },
      ],
    },
  ],
  itens: [
    "Eu nao tive ninguem para me dar afeto, cuidado e protecao, que partilhasse sua vida comigo, ou que se importasse de verdade com as coisas que me acontecem.",
    "Eu percebo que me agarro as pessoas que sao proximas de mim com medo de que elas me abandonem.",
    "Eu sinto que as pessoas vao tirar vantagem de mim.",
    "Eu nao me encaixo.",
    "Nenhum homem/mulher que eu deseje seria capaz de me amar depois de ver meus defeitos ou falhas.",
    "Quase nada do que eu faco no trabalho (ou nos estudos) e tao bom quanto o que os outros sao capazes de fazer.",
    "Eu nao me sinto capaz de me virar sem a ajuda dos outros no dia a dia.",
    "Parece que eu nao consigo parar de sentir que algo ruim esta prestes a acontecer.",
    "Eu ainda nao consegui me separar dos meus pais (ambos ou um deles) do jeito que as outras pessoas da minha idade parecem ter se separado.",
    "Eu sinto que, se eu fizer o que quero, os outros nao me apoiarao e poderao ficar bravos ou chateados comigo.",
    "Geralmente sou eu quem acaba cuidando das pessoas que sao proximas de mim.",
    "Eu sou envergonhado demais para demonstrar sentimentos positivos para os outros (por ex.: afeto; demonstrar que me importo com eles).",
    "Eu tenho que ser o melhor na maioria das coisas que eu faco; nao consigo aceitar o segundo lugar.",
    "Eu tenho muita dificuldade de aceitar um 'nao' quando quero algo dos outros.",
    "Parece que eu nao consigo me disciplinar para concluir a maioria das tarefas rotineiras ou entediantes.",
    "Ter dinheiro e conhecer pessoas importantes faz com que eu me sinta uma pessoa com valor.",
    "Mesmo quando as coisas parecem estar indo bem, eu sinto que e apenas questao de tempo para que elas comecem a dar errado.",
    "Se eu cometer algum erro, mereco ser punido.",
    "Eu nao tenho quem me de carinho, apoio e afeto.",
    "Eu preciso tanto das pessoas que fico muito preocupado com a possibilidade de perde-las.",
    "Eu sinto que nao posso baixar a guarda na presenca de outras pessoas, senao elas irao me machucar de proposito.",
    "Eu sou fundamentalmente diferente das outras pessoas.",
    "Ninguem que eu deseje iria querer ficar perto de mim se conhecesse quem eu sou de verdade.",
    "Eu sou incompetente quando se refere a realizacoes pessoais/profissionais.",
    "Eu me vejo como uma pessoa dependente dos outros no que se refere ao meu funcionamento diario.",
    "Eu sinto que uma tragedia (natural, financeira, criminal ou de saude) pode acontecer a qualquer momento.",
    "Eu e meu pai/mae temos a tendencia de nos envolver demais nos problemas e na vida uns dos outros.",
    "Eu sinto como se eu nao tivesse outra opcao a nao ser ceder aos desejos dos outros, senao eles irao ficar bravos, me rejeitar ou retaliar de alguma forma.",
    "Sou uma boa pessoa por pensar mais nos outros do que em mim.",
    "Eu acho constrangedor demonstrar o que eu sinto para as outras pessoas.",
    "Eu tento fazer o meu melhor; eu nao consigo me conformar em ser 'bom o suficiente'.",
    "Eu sou diferenciado e nao deveria ter que aceitar muitas das restricoes ou limitacoes impostas as outras pessoas.",
    "Se nao consigo atingir um objetivo, eu logo me frustro e desisto.",
    "Minhas conquistas tem mais valor para mim se forem notadas pelas outras pessoas.",
    "Se algo de bom acontece, fico preocupado e pensando que algo ruim provavelmente vai acontecer depois.",
    "Se eu nao der o meu melhor, eu tenho que me dar mal mesmo.",
    "Eu nunca me senti especial para ninguem.",
    "Eu me preocupo muito com a possibilidade de que pessoas proximas a mim me deixem ou me abandonem.",
    "E so uma questao de tempo ate alguem me trair.",
    "Eu nao faco parte; sou uma pessoa solitaria.",
    "Eu nao sou digno de receber amor, atencao e o respeito dos outros.",
    "A maioria das pessoas e mais capaz do que eu no trabalho e nas realizacoes pessoais.",
    "Me falta bom senso.",
    "Eu me preocupo muito em ser agredido fisicamente por alguem.",
    "Eu e meu pai/mae temos dificuldades de deixar de contar detalhes intimos uns para os outros sem nos sentirmos culpados.",
    "Nos relacionamentos, eu geralmente deixo que a outra pessoa tome as decisoes e esteja no controle.",
    "Eu passo tanto tempo fazendo coisas para as pessoas com quem me importo que acabo tendo pouco tempo para mim mesmo.",
    "Eu acho dificil me sentir livre e ser espontaneo perto de outras pessoas.",
    "Eu tenho que dar conta de todas as minhas responsabilidades.",
    "Eu detesto me sentir obrigado a fazer algo ou que me impecam de fazer aquilo que eu quero.",
    "Para mim, e muito dificil abrir mao de prazeres imediatos para atingir objetivos de longo prazo.",
    "Se as pessoas nao me dao muita atencao, eu me sinto menos importante.",
    "Todo cuidado e pouco, quase sempre algo vai dar errado.",
    "Se eu nao fizer minhas tarefas de forma correta, devo sofrer as consequencias.",
    "Eu nao tive ninguem que realmente me escutasse, compreendesse, ou estivesse conectado com as minhas verdadeiras necessidades e sentimentos.",
    "Quando alguem importante para mim parece estar se fechando ou se afastando, eu fico desesperado.",
    "Eu desconfio bastante das intencoes das outras pessoas.",
    "Eu me sinto isolado ou desconectado dos outros.",
    "Eu sinto que sou alguem que nao pode ser amado.",
    "Eu nao sou tao talentoso no trabalho quanto a maioria das pessoas.",
    "Nao se pode contar com meu julgamento em situacoes do dia a dia.",
    "Eu tenho medo de perder todo o meu dinheiro, de passar necessidades ou ficar muito pobre.",
    "Eu frequentemente sinto como se meus pais vivessem a minha vida ou vivessem atraves de mim - e como se eu nao tivesse uma vida propria.",
    "Eu sempre deixei as outras pessoas escolherem por mim, entao nem sei o que eu quero para mim mesmo.",
    "Eu sempre fui aquele que escuta os problemas de todo mundo.",
    "Eu me controlo tanto que muitas pessoas acham que eu nao tenho emocoes ou sou insensivel.",
    "Sinto que ha uma pressao constante para que eu conquiste e termine as coisas.",
    "Eu sinto que nao deveria ter que seguir as regras e normas que as outras pessoas tem que seguir.",
    "Eu nao consigo me forcar a fazer coisas que eu nao goste, mesmo quando sei que e para o meu proprio bem.",
    "Quando eu faco comentarios em uma reuniao, ou sou apresentado a alguem em uma situacao social, para mim e importante receber reconhecimento e admiracao.",
    "Independentemente de quanto eu trabalhe, preocupo-me com a ideia de ter problemas financeiros serios e perder quase tudo que tenho.",
    "Nao importa os motivos que me levaram a cometer um erro. Quando faco algo errado, devo sofrer as consequencias.",
    "Eu nao tenho tido uma pessoa forte ou sabia para me dar conselhos uteis ou orientacao quando nao tenho certeza do que fazer.",
    "As vezes eu me preocupo tanto que as pessoas possam me abandonar que as afasto de mim.",
    "Eu geralmente estou atento aos motivos ocultos e as segundas intencoes das outras pessoas.",
    "Eu sempre me senti deslocado ou de fora dos grupos.",
    "Sou inaceitavel demais para mostrar para as pessoas como eu sou ou deixar que elas me conhecam bem.",
    "Nao sou tao inteligente no trabalho (ou estudos) quanto a maioria das pessoas.",
    "Nao tenho confianca na minha habilidade de resolver os problemas que surgem no dia a dia.",
    "Eu me preocupo com a possibilidade de desenvolver uma doenca grave, mesmo que nada serio tenha sido diagnosticado por um medico.",
    "Eu muitas vezes sinto que nao tenho uma identidade separada da do meu pai/mae ou companheiro(a).",
    "Para mim, e muito dificil exigir que meus direitos sejam respeitados e que meus sentimentos sejam levados em consideracao.",
    "As pessoas consideram que faco demais pelos outros e nao faco o suficiente por mim mesmo.",
    "As pessoas me veem como alguem mais fechado emocionalmente.",
    "Eu nao posso 'pegar leve' comigo mesmo ou ficar arranjando desculpas pelos meus erros.",
    "Eu sinto que o que tenho a oferecer tem muito mais valor quando comparado ao que os outros tem para dar.",
    "Eu raramente consigo seguir com minhas resolucoes ou projetos pessoais/profissionais.",
    "Receber muitos elogios dos outros faz com que eu me sinta uma pessoa de valor.",
    "Eu me preocupo que uma decisao errada possa causar um desastre.",
    "Sou uma pessoa ma e que merece ser punida.",
  ],
};

export const ypi: EscalaConfig = {
  id: "ypi",
  sigla: "YPI",
  nome: "Inventario Parental de Young",
  instrucoes:
    "Leia cada afirmacao e avalie o quanto ela descreve as atitudes dos seus pais enquanto voce crescia. Voce respondera as mesmas 72 perguntas duas vezes: primeiro pensando no seu PAI (ou figura paterna), depois na sua MAE (ou figura materna). 1 = Completamente Falso ate 6 = Descreve Perfeitamente.",
  rodadas: ["Pai", "Mae"],
  opcoes: opcoes6,
  scoring: "schema-avg",
  dominios: [
    {
      id: "d1",
      nome: "Desconexao e Rejeicao",
      esquemas: [
        { id: "pe", nome: "Privacao Emocional", itens: [1, 2, 3, 4, 5], invertido: true },
        { id: "ab", nome: "Abandono", itens: [6, 7, 8, 9] },
        { id: "da", nome: "Desconfianca / Abuso", itens: [10, 11, 12, 13] },
        { id: "dv", nome: "Defectividade / Vergonha", itens: [21, 22, 23, 24] },
      ],
    },
    {
      id: "d2",
      nome: "Autonomia e Desempenho Prejudicados",
      esquemas: [
        { id: "vu", nome: "Vulnerabilidade ao Dano", itens: [14, 15, 16, 17] },
        { id: "di", nome: "Dependencia / Incompetencia", itens: [18, 19, 20] },
        { id: "fr", nome: "Fracasso", itens: [25, 26, 27, 28] },
        { id: "em", nome: "Emaranhamento", itens: [52, 53, 54, 55] },
      ],
    },
    {
      id: "d3",
      nome: "Orientacao para o Outro",
      esquemas: [
        { id: "sb", nome: "Subjugacao", itens: [29, 30, 31, 32] },
        { id: "as", nome: "Auto-Sacrificio", itens: [33, 34, 35, 36] },
        { id: "bar", nome: "Busca de Aprovacao", itens: [69, 70, 71, 72] },
      ],
    },
    {
      id: "d4",
      nome: "Supervigilancia e Inibicao",
      esquemas: [
        { id: "pi", nome: "Padroes Inflexiveis", itens: [37, 38, 39, 40, 41, 42, 43] },
        { id: "np", nome: "Negativismo / Pessimismo", itens: [56, 57, 58, 59] },
        { id: "ie", nome: "Inibicao Emocional", itens: [60, 61, 62, 63, 64] },
        { id: "pu", nome: "Postura Punitiva", itens: [65, 66, 67, 68] },
      ],
    },
    {
      id: "d5",
      nome: "Limites Prejudicados",
      esquemas: [
        { id: "gr", nome: "Grandiosidade / Arrogo", itens: [44, 45, 46, 47] },
        { id: "ai", nome: "Autocontrole Insuficiente", itens: [48, 49, 50, 51] },
      ],
    },
  ],
  itens: [
    "Gostava de mim e me tratava como uma pessoa especial.",
    "Prestava atencao em mim, passando bastante tempo comigo.",
    "Costumava me dar conselhos e orientacoes uteis.",
    "Costumava me ouvir, me entender e compartilhar sentimentos comigo.",
    "Era caloroso(a) e afetuoso(a).",
    "Morreu ou abandonou a casa para sempre quando eu era crianca.",
    "Era mal humorado(a), imprevisivel ou alcoolatra.",
    "Preferia meus irmaos a mim.",
    "Isolava-se ou me deixava sozinho(a) por longos periodos de tempo.",
    "Mentia pra mim, me enganava e me traia.",
    "Abusava fisica, emocional ou sexualmente de mim.",
    "Usava-me para satisfazer suas necessidades emocionais.",
    "Parecia ter prazer em magoar os outros.",
    "Preocupava-se excessivamente com o fato de eu poder me magoar.",
    "Preocupava-se excessivamente com o fato de eu ficar fisicamente doente.",
    "Era uma pessoa medrosa ou fobica.",
    "Era superprotetor(a).",
    "Fazia-me sentir que eu nao podia confiar em minhas decisoes ou opinioes.",
    "Fazia as coisas por mim em vez de me deixar tentar faze-las sozinho(a).",
    "Tratava-me como se eu fosse mais novo(a) do que eu realmente era.",
    "Criticava-me bastante.",
    "Nao me fazia sentir amado(a) ou me fazia sentir rejeitado(a).",
    "Tratava-me como se houvesse algo de errado comigo.",
    "Fazia-me sentir vergonha de mim mesmo(a) em aspectos importantes.",
    "Nunca me ensinou a ter disciplina suficiente para ser bem sucedido(a) na escola.",
    "Tratava-me como se eu fosse estupido(a) ou nao tivesse jeito pra nada.",
    "No fundo, nao queria que eu fosse bem sucedido(a).",
    "Esperava que eu fosse um fracasso na vida.",
    "Tratava-me como se as minhas opinioes ou desejos nao contassem.",
    "Fazia o que queria, independente das minhas necessidades.",
    "Controlava tanto a minha vida que eu tinha pouca liberdade de escolha.",
    "Tudo tinha que ser como ele(a) queria.",
    "Sacrificava as suas necessidades para o bem da familia.",
    "Era incapaz de lidar com a maior parte das responsabilidades diarias, de modo que eu tinha que fazer mais do que a minha parte.",
    "Era bastante infeliz e apoiava-se em mim para conforta-lo(a) e compreende-lo(a).",
    "Fazia-me sentir que eu era forte e que devia cuidar dos outros.",
    "Tinha expectativas muito altas em relacao a si mesmo(a).",
    "Esperava que eu fizesse sempre o melhor.",
    "Era perfeccionista em muitas areas; as coisas tinham que ser do jeito dele(a).",
    "Fazia-me sentir que quase nada do que eu fazia era suficientemente bom.",
    "Tinha regras rigidas e estritas quanto ao que era certo e errado.",
    "Ficava impaciente se as coisas nao fossem feitas de forma adequada ou suficientemente rapida.",
    "Dava mais importancia a fazer as coisas bem do que a se divertir ou relaxar.",
    "Estragou-me com mimos ou era demasiado indulgente em muitos aspectos.",
    "Fazia-me sentir que eu era especial, melhor que a maioria das outras pessoas.",
    "Era exigente; esperava que as coisas ocorressem a sua maneira.",
    "Nao me ensinou que eu tinha responsabilidade para com os outros.",
    "Forneceu-me muito pouca disciplina e limites.",
    "Estabeleceu poucas regras ou responsabilidades para mim.",
    "Permitia-me ficar muito bravo(a) ou perder o controle.",
    "Era uma pessoa indisciplinada.",
    "Eramos tao proximos que compreendiam um ao outro de uma maneira quase perfeita.",
    "Eu sentia que nao tinha individualidade suficiente, nao me sentindo separado dele(a).",
    "Enquanto crescia, eu sentia que nao tinha meu proprio senso de direcao de tanto que estava ligado(a) a ele(a).",
    "Eu sentia que nos magoariamos um(a) ao outro(a) se nos afastassemos.",
    "Preocupava-se muito com os problemas financeiros da familia.",
    "Fazia-me sentir que se eu cometesse um erro, mesmo que pequeno, algo de mal poderia acontecer.",
    "Tinha uma perspectiva pessimista; frequentemente esperava pelo pior.",
    "Seu foco era nos aspectos negativos da vida ou nas coisas que estavam indo mal.",
    "Tinha que ter tudo sob controle.",
    "Sentia-se desconfortavel ao demonstrar afeto ou vulnerabilidade.",
    "Era estruturado(a) e organizado(a); preferia o que era habitual a mudanca.",
    "Raramente expressava raiva.",
    "Era reservado(a); raramente discutia seus sentimentos.",
    "Ficava bravo(a) ou criticava bastante se eu fizesse algo de errado.",
    "Eu era castigado(a) se eu fizesse algo de errado.",
    "Costumava me xingar (por exemplo, de 'estupido' ou 'idiota') se eu cometesse algum erro.",
    "Culpava as pessoas quando as coisas iam mal.",
    "Preocupava-se com as aparencias e com o status social.",
    "Dava muita importancia ao sucesso e a competicao.",
    "Preocupava-se com o que os outros pensariam dele(a) por causa do meu comportamento.",
    "Parecia me dar mais atencao quando eu me sobressaia.",
  ],
};

export const yci: EscalaConfig = {
  id: "yci",
  sigla: "YCI",
  nome: "Inventario de Compensacao de Young",
  instrucoes:
    "Leia cada afirmacao e decida o quao bem elas descrevem voce. Responda guiado por como voce sente e age, nao pelo que acha 'correto'.",
  opcoes: opcoes6,
  scoring: "threshold",
  itens: [
    "Eu desconto as minhas frustracoes nos outros.",
    "Muitas vezes eu culpo os outros quando as coisas dao errado.",
    "Eu demonstro muita raiva quando as pessoas me decepcionam ou me traem.",
    "Eu nao consigo parar de sentir raiva ate me vingar.",
    "Quando eu sou criticado, fico na defensiva.",
    "E importante que os outros admirem minhas realizacoes ou conquistas.",
    "Para mim, e importante demonstrar o meu sucesso (p. ex., com carros caros, roupas, casa).",
    "Eu me esforco muito para ficar entre os melhores ou mais bem-sucedidos.",
    "Eu considero importante ser popular (p. ex., fazer parte de um grupo seleto).",
    "Eu frequentemente tenho fantasias de sucesso, fama, riqueza, poder ou popularidade.",
    "Eu gosto de ser o centro das atencoes.",
    "Eu flerto mais ou sou mais sedutor do que as pessoas em geral.",
    "Eu dou muita importancia a ordem na minha vida (p. ex., organizacao, estrutura, planejamento, rotina).",
    "Eu gasto muita energia tentando evitar que as coisas deem errado.",
    "Eu penso muito antes de tomar decisoes para que eu nao cometa um erro.",
    "Eu sou bastante controlador em relacao as pessoas a minha volta.",
    "Eu gosto de estar em posicoes nas quais eu tenha controle ou autoridade sobre as pessoas ao meu redor.",
    "Eu nao gosto que as pessoas deem palpites sobre a minha vida.",
    "Para mim, e muito dificil ceder ou chegar num consenso.",
    "Eu nao gosto de ser dependente de ninguem.",
    "Eu considero essencial que eu tome as minhas proprias decisoes e seja independente.",
    "Eu tenho dificuldade de me comprometer com uma pessoa ou me manter em uma relacao estavel.",
    "Eu gosto de ser uma pessoa livre, de ter liberdade para fazer o que eu quiser.",
    "Eu tenho dificuldade de me limitar a um emprego ou carreira; eu gosto de ter liberdade de escolha.",
    "Eu geralmente coloco as minhas proprias necessidades na frente das dos outros.",
    "Muitas vezes eu sou exigente com as outras pessoas - eu gosto que tudo seja 'exatamente como tem que ser'.",
    "Eu preciso cuidar de mim primeiro, assim como fazem as outras pessoas.",
    "Para mim, e muito importante que o meu ambiente seja confortavel (p. ex., temperatura, luz, moveis).",
    "Eu me considero uma pessoa rebelde; eu frequentemente vou contra a autoridade estabelecida.",
    "Eu nao gosto de regras e sinto satisfacao quando as desrespeito.",
    "Eu gosto de nao ser convencional, mesmo que isso me faca ser pouco popular ou que eu nao me encaixe por isso.",
    "Eu nao procuro sucesso seguindo os padroes da sociedade (ex., riqueza, realizacoes, popularidade).",
    "Eu sempre fui diferente; nunca fui atras da maioria.",
    "Eu sou uma pessoa muito reservada; nao gosto que as pessoas saibam muito a respeito da minha vida particular ou dos meus sentimentos.",
    "Eu tento sempre parecer forte para as outras pessoas, mesmo que me sinta vulneravel ou inseguro.",
    "As vezes eu sou muito possessivo e fico muito grudado com as pessoas que eu valorizo.",
    "Eu frequentemente manipulo os outros para atingir meus objetivos.",
    "Em vez de pedir o que eu quero diretamente, muitas vezes prefiro conseguir as coisas por meios indiretos.",
    "Eu mantenho as pessoas a distancia para que elas so vejam as partes de mim que eu quero que elas vejam.",
    "Eu sou uma pessoa extremamente critica.",
    "Eu sinto que me pressiono demais para satisfazer os meus proprios padroes e responsabilidades.",
    "Muitas vezes eu nao tenho tato ou sou insensivel ao me expressar.",
    "Eu tento ser otimista o tempo todo; nao me permito dar atencao aos aspectos negativos.",
    "Eu acho que e importante parecer feliz, independentemente de como eu me sinta por dentro.",
    "Varias vezes eu sinto inveja ou fico frustrado quando os outros sao mais bem-sucedidos ou recebem mais atencao do que eu.",
    "Eu irei ate aonde for necessario para me certificar de que eu ganhe o que e meu por direito e que eu nao seja enganado ou traido.",
    "Eu busco maneiras de ser mais esperto do que os outros para que eles nao tirem vantagem de mim ou me magoem.",
    "Eu sei exatamente o que dizer ou fazer para que os outros gostem de mim (p. ex., elogiar, dizer aquilo que eles querem ouvir).",
  ],
};

// ============ YRAI (Inventário de Evitação de Young-Rygh) ============
// Young & Rygh (1994); BR: Cazassa & Oliveira (2008). 40 itens. Threshold ≥ 5.
export const yrai: EscalaConfig = {
  id: "yrai",
  sigla: "YRAI",
  nome: "Inventario de Evitacao de Young-Rygh",
  instrucoes:
    "Leia cada afirmacao e avalie o quanto ela descreve voce no ultimo ano, de 1 (Completamente falso) a 6 (Me descreve perfeitamente).",
  opcoes: opcoes6,
  scoring: "threshold",
  itens: [
    "Eu evito pensar sobre coisas que me perturbam.",
    "Eu me esforco para nao pensar sobre coisas que me magoam.",
    "Eu me mantenho ocupado(a) para nao ter que pensar sobre coisas que me perturbam.",
    "Eu afasto pensamentos e imagens perturbadoras da minha mente.",
    "Muitas vezes nao sei o que estou sentindo.",
    "Eu bloqueio meus sentimentos.",
    "Eu me sinto entorpecido(a) emocionalmente.",
    "Eu evito sentir emocoes fortes.",
    "Eu evito situacoes que me fazem sentir desconfortavel.",
    "Eu evito fazer coisas que possam resultar em fracasso.",
    "Eu evito desafios novos.",
    "Eu evito situacoes onde posso ser criticado(a) ou julgado(a).",
    "Eu me afasto das pessoas quando estou chateado(a).",
    "Eu prefiro ficar sozinho(a) a estar com outras pessoas.",
    "Eu evito relacoes intimas.",
    "Eu nao deixo as pessoas se aproximarem muito de mim.",
    "Eu nao gosto de depender de ninguem.",
    "Eu evito pedir ajuda, mesmo quando preciso.",
    "Eu prefiro fazer tudo sozinho(a).",
    "Eu nao demonstro fraqueza para os outros.",
    "Eu como demais para me sentir melhor.",
    "Eu bebo ou uso substancias para aliviar o estresse.",
    "Eu compro coisas para me sentir melhor.",
    "Eu trabalho excessivamente para nao ter que lidar com meus sentimentos.",
    "Eu assisto televisao ou uso a internet demais para me distrair.",
    "Eu durmo demais para evitar lidar com problemas.",
    "Eu me queixo de problemas fisicos quando estou emocionalmente perturbado(a).",
    "Eu tendo a ter dores de cabeca ou problemas digestivos quando estou sob estresse.",
    "Eu concordo com os outros para evitar conflitos, mesmo quando discordo.",
    "Eu digo o que os outros querem ouvir em vez do que realmente penso.",
    "Eu engulo minha raiva para evitar confrontos.",
    "Eu faco tudo para manter a paz, mesmo sacrificando minhas necessidades.",
    "Eu finjo que esta tudo bem quando nao esta.",
    "Eu nego que tenho problemas mesmo quando outros apontam.",
    "Eu minimizo a gravidade dos meus problemas.",
    "Eu mudo de assunto quando a conversa fica pessoal demais.",
    "Eu evito falar sobre meus sentimentos mais profundos.",
    "Eu mantenho meus relacionamentos superficiais de proposito.",
    "Eu evito situacoes que me lembram de experiencias dolorosas do passado.",
    "Eu tendo a fugir de responsabilidades que me causam ansiedade.",
  ],
};

// ============ SMI (Inventário de Modos Esquemáticos) ============
// Lobbestael, van Vreeswijk & Arntz (2010); BR: Rocha et al. (2017). 118 itens, 14 modos.
export const smi: EscalaConfig = {
  id: "smi",
  sigla: "SMI",
  nome: "Inventario de Modos Esquematicos",
  instrucoes:
    "Leia cada afirmacao e avalie o quanto ela descreve voce, de 1 (Completamente falso) a 6 (Me descreve perfeitamente). Responda sobre como voce se sentiu na maioria das vezes no ultimo ano.",
  opcoes: opcoes6,
  scoring: "schema-avg",
  dominios: [
    {
      id: "crianca",
      nome: "Modos Crianca",
      esquemas: [
        { id: "cv", nome: "Crianca Vulneravel", itens: [1, 15, 29, 42, 43, 56, 57, 69, 71, 82, 85, 99, 109, 113] },
        { id: "cza", nome: "Crianca Zangada", itens: [2, 16, 30, 44, 58, 70, 72, 86, 100, 110, 114] },
        { id: "ci", nome: "Crianca Impulsiva", itens: [3, 17, 31, 45, 59, 73, 87, 101] },
        { id: "cid", nome: "Crianca Indisciplinada", itens: [4, 18, 32, 46, 60, 74, 88, 102] },
        { id: "cfe", nome: "Crianca Feliz", itens: [5, 19, 33, 47, 61, 75, 89, 103, 111, 115] },
      ],
    },
    {
      id: "parental",
      nome: "Modos Parentais Disfuncionais",
      esquemas: [
        { id: "pp", nome: "Pai/Mae Punitivo(a)", itens: [6, 20, 34, 48, 62, 76, 90, 104, 112, 116] },
        { id: "pe", nome: "Pai/Mae Exigente", itens: [7, 21, 35, 49, 63, 77, 91, 105, 117] },
      ],
    },
    {
      id: "enfrentamento",
      nome: "Modos de Enfrentamento Disfuncionais",
      esquemas: [
        { id: "cc", nome: "Capitulador Complacente", itens: [8, 22, 36, 50, 55, 64, 78, 92, 96, 106] },
        { id: "pd", nome: "Protetor Desligado", itens: [9, 14, 23, 28, 37, 51, 65, 79, 93, 107] },
        { id: "acd", nome: "Autoconsolador Desligado", itens: [10, 24, 38] },
        { id: "ae", nome: "Autoengrandecedor", itens: [11, 25, 39, 52, 66, 80, 83, 94, 97, 108] },
        { id: "va", nome: "Valentao e Ataque", itens: [12, 26, 40, 53, 67] },
      ],
    },
    {
      id: "saudavel",
      nome: "Modo Saudavel",
      esquemas: [
        { id: "as", nome: "Adulto Saudavel", itens: [13, 27, 41, 54, 68, 81, 84, 95, 98, 118] },
      ],
    },
  ],
  itens: [
    "Eu me sinto sozinho(a) no mundo.",
    "Eu me sinto com raiva porque minhas necessidades nao sao atendidas.",
    "Eu tenho dificuldade em resistir a impulsos.",
    "Eu desisto facilmente quando algo se torna dificil.",
    "Eu me sinto amado(a) e acolhido(a).",
    "Eu mereco ser punido(a).",
    "Eu tenho que fazer tudo perfeitamente, sem erros.",
    "Eu cedo aos desejos dos outros para evitar conflitos.",
    "Eu me desligo dos meus sentimentos.",
    "Eu me acalmo comendo, bebendo ou usando outras formas de me consolar.",
    "Eu me sinto superior as outras pessoas.",
    "Eu ataco os outros antes que eles possam me atacar.",
    "Eu consigo lidar com a maioria dos problemas de forma equilibrada.",
    "Eu nao me sinto conectado(a) com as outras pessoas.",
    "Sinto que ninguem me ama.",
    "Sinto-me frustrado(a) quando os outros nao me tratam de forma justa.",
    "Quando quero algo, quero imediatamente.",
    "Tenho dificuldade em completar tarefas rotineiras.",
    "Sinto-me seguro(a) e protegido(a).",
    "Eu sinto que sou uma pessoa ma e que mereco sofrer.",
    "Eu me cobro demais para dar conta de tudo.",
    "Eu faco o que os outros querem, mesmo quando nao concordo.",
    "Eu me fecho emocionalmente para nao ser magoado(a).",
    "Eu uso distracao para nao ter que enfrentar emocoes dificeis.",
    "Eu acho que sou melhor que a maioria das pessoas.",
    "Eu intimido os outros para conseguir o que quero.",
    "Eu busco solucoes praticas para os meus problemas.",
    "Eu evito situacoes que possam me machucar emocionalmente.",
    "Sinto-me desamparado(a) e sem protecao.",
    "Eu fico com raiva quando me sinto controlado(a) por outros.",
    "Eu ajo por impulso sem pensar nas consequencias.",
    "Nao consigo me forcar a fazer coisas que nao gosto.",
    "Eu me divirto e brinco com facilidade.",
    "Eu me critico severamente quando cometo um erro.",
    "Eu me esforco para atender a expectativas muito altas.",
    "Eu coloco as necessidades dos outros na frente das minhas.",
    "Eu evito relacoes intimas porque podem me machucar.",
    "Eu me distraio com atividades repetitivas para nao sentir dor emocional.",
    "Eu gosto de ser o centro das atencoes.",
    "Eu uso a intimidacao para controlar os outros.",
    "Eu consigo expressar meus sentimentos de forma saudavel.",
    "Eu me sinto carente de afeto e atencao.",
    "Sinto que nao sou bom(boa) o suficiente.",
    "Sinto vontade de gritar quando nao me escutam.",
    "Eu tenho dificuldade em esperar por coisas que quero.",
    "Eu evito fazer coisas que exigem muito esforco.",
    "Sinto que posso ser eu mesmo(a) com as pessoas.",
    "Sinto que sou uma pessoa terrivel e que nao mereco coisas boas.",
    "Eu sinto que nunca faco o suficiente, nao importa o quanto me esforce.",
    "Eu me sinto obrigado(a) a agradar as pessoas.",
    "Eu me retiro e fico em silencio quando me sinto ameacado(a).",
    "Eu me sinto superior e tenho dificuldade em aceitar criticas.",
    "Eu reajo com agressividade verbal quando me sinto ameacado(a).",
    "Eu trato a mim mesmo(a) com cuidado e compaixao.",
    "Eu nao consigo tomar decisoes sozinho(a).",
    "Eu me sinto sem esperanca sobre o futuro.",
    "Sinto medo de que pessoas importantes para mim vao me abandonar.",
    "Eu me sinto impaciente e irritado(a) com as pessoas.",
    "Eu gasto dinheiro impulsivamente.",
    "Eu procrastino constantemente.",
    "Sinto-me conectado(a) com os outros.",
    "Eu me puno mentalmente quando erro.",
    "Eu sinto que preciso ser o(a) melhor em tudo.",
    "Eu tenho dificuldade em dizer nao.",
    "Eu finjo que nao me importo quando na verdade me importo muito.",
    "Eu acho que mereco tratamento especial.",
    "Eu ameaco os outros quando nao consigo o que quero.",
    "Eu consigo estabelecer limites saudaveis com os outros.",
    "Eu me sinto dependente dos outros para me sentir seguro(a).",
    "Eu sinto uma raiva intensa que parece incontrolavel.",
    "Sinto-me vulneravel e facilmente magoado(a).",
    "Tenho explosoes de raiva que depois me arrependo.",
    "Eu faco coisas arriscadas quando estou excitado(a).",
    "Falta-me disciplina para atingir meus objetivos.",
    "Sinto-me otimista e esperancoso(a) sobre o futuro.",
    "Quando cometo um erro, sinto que mereco ser castigado(a).",
    "Eu me sinto um fracasso quando nao atinjo padroes perfeitos.",
    "Eu me submeto a situacoes que nao gosto para manter a paz.",
    "Eu me sinto distante e desconectado(a) das minhas emocoes.",
    "Eu gosto de impressionar os outros com minhas qualidades.",
    "Eu consigo cuidar de mim e dos outros de forma equilibrada.",
    "Eu me sinto inseguro(a) sobre quem eu sou.",
    "Eu nao consigo aceitar quando nao sou o(a) melhor.",
    "Eu me sinto tranquilo(a) e em paz comigo mesmo(a).",
    "Sinto uma tristeza profunda sem motivo aparente.",
    "Eu me sinto revoltado(a) por nao ter tido o que eu merecia.",
    "Eu digo coisas das quais me arrependo depois.",
    "Eu largo as coisas pela metade com frequencia.",
    "Eu me sinto alegre e com energia.",
    "Eu acredito que sou inerentemente defeituoso(a) e mau(ma).",
    "Eu me esforco demais para atender aos padroes dos outros.",
    "Eu deixo que os outros tomem decisoes por mim.",
    "Eu evito pensar sobre experiencias dolorosas do passado.",
    "Eu desprezo as pessoas que considero inferiores.",
    "Eu aceito meus erros e aprendo com eles.",
    "Eu me sinto sufocado(a) pelas expectativas dos outros.",
    "Eu tendo a competir e querer vencer a qualquer custo.",
    "Eu busco um equilibrio entre trabalho, lazer e relacionamentos.",
    "Eu me sinto abandonado(a) e deixado(a) de lado.",
    "Eu sinto uma raiva que me consome por dentro.",
    "Eu como ou bebo demais quando estou com vontade.",
    "Eu tenho dificuldade em seguir regras e rotinas.",
    "Eu consigo me divertir e aproveitar o momento.",
    "Eu sinto que sou uma pessoa sem valor e que mereco desprezo.",
    "Eu nao consigo relaxar enquanto nao terminar tudo perfeitamente.",
    "Eu me anulo para que os outros gostem de mim.",
    "Eu me afasto emocionalmente para me proteger.",
    "Eu uso meu charme ou poder para manipular situacoes a meu favor.",
    "Eu me sinto como uma crianca perdida e assustada.",
    "Eu fico furioso(a) quando sinto que estao me desrespeitando.",
    "Eu me sinto satisfeito(a) com quem eu sou.",
    "Eu me trato com dureza e me critico o tempo todo.",
    "Sinto que nao pertenco a lugar nenhum.",
    "Eu me sinto com raiva de mim mesmo(a) por nao conseguir me impor.",
    "Eu me sinto livre para expressar meus sentimentos.",
    "Eu acredito que os outros merecem ser punidos quando erram.",
    "Eu sinto que preciso provar meu valor o tempo todo.",
    "Eu consigo pedir ajuda quando preciso e aceitar apoio dos outros.",
  ],
};

export const escalas: Record<string, EscalaConfig> = { ysq, ypi, yci, yrai, smi };