// Auto-generated scale data - do not edit manually
// Extracted from HTML source files

export interface BDIItem {
  opcoes: { texto: string; valor: number }[];
}

export interface EscalaGeralDominio {
  id: string;
  nome: string;
  itens: number[];
  invertidos?: number[];
}

export interface EscalaGeralConfig {
  id: string;
  sigla: string;
  nome: string;
  instrucoes: string;
  tipo: "likert" | "likert-statements" | "binary";
  opcoes?: { label: string; valor: number }[];
  itens: string[] | BDIItem[];
  dominios?: EscalaGeralDominio[];
  invertidos?: number[];
  chaveCorrecao?: Record<number, string>;
  pontuacaoMaxima?: number;
  /** Min/max da escala de resposta, usado na inversao de itens quando os
   * itens tem opcoes proprias (tipo "likert-statements") em vez de um
   * `opcoes` global. Default: min 0, max 4 (compatibilidade retroativa). */
  escalaMin?: number;
  escalaMax?: number;
}

// ============ ASRS-18 ============
export const asrs: EscalaGeralConfig = {
  id: "asrs",
  sigla: "ASRS-18",
  nome: "Escala de TDAH no Adulto",
  instrucoes: "Responda as perguntas abaixo escolhendo a opcao que corresponde a como voce se sentiu e se comportou nos ultimos seis meses.",
  tipo: "likert",
  opcoes: [
    { label: "Nunca", valor: 0 },
    { label: "Raramente", valor: 1 },
    { label: "Algumas vezes", valor: 2 },
    { label: "Frequentemente", valor: 3 },
    { label: "Muito frequentemente", valor: 4 },
  ],
  dominios: [
    { id: "desatencao", nome: "Parte A: Desatencao", itens: [1,2,3,4,5,6,7,8,9] },
    { id: "hiperatividade", nome: "Parte B: Hiperatividade/Impulsividade", itens: [10,11,12,13,14,15,16,17,18] },
  ],
  itens: [
    "Com que frequencia voce comete erros por falta de atencao quando tem de trabalhar num projeto chato ou dificil?",
    "Com que frequencia voce tem dificuldade para manter a atencao quando esta fazendo um trabalho chato ou repetitivo?",
    "Com que frequencia voce tem dificuldade para se concentrar no que as pessoas dizem, mesmo quando elas estao falando diretamente com voce?",
    "Com que frequencia voce deixa um projeto pela metade depois de ja ter feito as partes mais dificeis?",
    "Com que frequencia voce tem dificuldade para fazer um trabalho que exige organizacao?",
    "Quando voce precisa fazer algo que exige muita concentracao, com que frequencia voce evita ou adia o inicio?",
    "Com que frequencia voce coloca as coisas fora do lugar ou tem dificuldade de encontrar as coisas em casa ou no trabalho?",
    "Com que frequencia voce se distrai com atividades ou barulho a sua volta?",
    "Com que frequencia voce tem dificuldade para lembrar de compromissos ou obrigacoes?",
    "Com que frequencia voce fica se mexendo na cadeira ou balancando as maos ou os pes quando precisa ficar sentado(a) por muito tempo?",
    "Com que frequencia voce se levanta da cadeira em reunioes ou em outras situacoes onde deveria ficar sentado(a)?",
    "Com que frequencia voce se sente inquieto(a) ou agitado(a)?",
    "Com que frequencia voce tem dificuldade para sossegar e relaxar quando tem tempo livre para voce?",
    "Com que frequencia voce se sente ativo(a) demais e necessitando fazer coisas, como se estivesse com um motor ligado?",
    "Com que frequencia voce se pega falando demais em situacoes sociais?",
    "Quando voce esta conversando, com que frequencia voce se pega terminando as frases das pessoas antes delas?",
    "Com que frequencia voce tem dificuldade para esperar nas situacoes onde cada um tem a sua vez?",
    "Com que frequencia voce interrompe os outros quando eles estao ocupados?",
  ],
};

// ============ BAI ============
export const bai: EscalaGeralConfig = {
  id: "bai",
  sigla: "BAI",
  nome: "Inventario de Ansiedade de Beck",
  instrucoes: "Avalie o quanto voce tem sido incomodado por cada sintoma durante a ultima semana, incluindo hoje.",
  tipo: "likert",
  pontuacaoMaxima: 63,
  opcoes: [
    { label: "Absolutamente nao", valor: 0 },
    { label: "Levemente", valor: 1 },
    { label: "Moderadamente", valor: 2 },
    { label: "Gravemente", valor: 3 },
  ],
  itens: [
    "Dormencia ou formigamento.",
    "Sensacao de calor.",
    "Tremores nas pernas.",
    "Incapaz de relaxar.",
    "Medo que aconteca o pior.",
    "Atordoado ou tonto.",
    "Palpitacao ou aceleracao do coracao.",
    "Sem equilibrio.",
    "Aterrorizado.",
    "Nervoso.",
    "Sensacao de sufocacao.",
    "Tremores nas maos.",
    "Tremulo.",
    "Medo de perder o controle.",
    "Dificuldade de respirar.",
    "Medo de morrer.",
    "Assustado.",
    "Indigestao ou desconforto no abdomen.",
    "Sensacao de desmaio.",
    "Rosto afogueado.",
    "Suor (nao devido ao calor).",
  ],
};

// ============ BDI ============
export const bdi: EscalaGeralConfig = {
  id: "bdi",
  sigla: "BDI",
  nome: "Inventario de Depressao de Beck",
  instrucoes: "Este questionario consiste em 21 grupos de afirmacoes. Escolha a afirmacao que melhor descreve a maneira que voce tem se sentido na ultima semana, incluindo hoje.",
  tipo: "likert-statements",
  pontuacaoMaxima: 63,
  itens: [
    { opcoes: [
      { texto: "Nao me sinto triste.", valor: 0 },
      { texto: "Eu me sinto triste.", valor: 1 },
      { texto: "Estou sempre triste e nao consigo sair disto.", valor: 2 },
      { texto: "Estou tao triste ou infeliz que nao consigo suportar.", valor: 3 },
    ] },
    { opcoes: [
      { texto: "Nao estou especialmente desanimado quanto ao futuro.", valor: 0 },
      { texto: "Eu me sinto desanimado quanto ao futuro.", valor: 1 },
      { texto: "Acho que nada tenho a esperar.", valor: 2 },
      { texto: "Acho o futuro sem esperanca e tenho a impressao de que as coisas nao podem melhorar.", valor: 3 },
    ] },
    { opcoes: [
      { texto: "Nao me sinto um fracasso.", valor: 0 },
      { texto: "Acho que fracassei mais do que uma pessoa comum.", valor: 1 },
      { texto: "Quando olho para tras, na minha vida, tudo o que posso ver e um monte de fracassos.", valor: 2 },
      { texto: "Acho que, como pessoa, sou um completo fracasso.", valor: 3 },
    ] },
    { opcoes: [
      { texto: "Tenho tanto prazer em tudo como antes.", valor: 0 },
      { texto: "Nao sinto mais prazer nas coisas como antes.", valor: 1 },
      { texto: "Nao encontro um prazer real em mais nada.", valor: 2 },
      { texto: "Estou insatisfeito ou aborrecido com tudo.", valor: 3 },
    ] },
    { opcoes: [
      { texto: "Nao me sinto especialmente culpado.", valor: 0 },
      { texto: "Eu me sinto culpado grande parte do tempo.", valor: 1 },
      { texto: "Eu me sinto culpado na maior parte do tempo.", valor: 2 },
      { texto: "Eu me sinto sempre culpado.", valor: 3 },
    ] },
    { opcoes: [
      { texto: "Nao acho que esteja sendo punido.", valor: 0 },
      { texto: "Acho que posso ser punido.", valor: 1 },
      { texto: "Creio que vou ser punido.", valor: 2 },
      { texto: "Acho que estou sendo punido.", valor: 3 },
    ] },
    { opcoes: [
      { texto: "Nao me sinto decepcionado comigo mesmo.", valor: 0 },
      { texto: "Estou decepcionado comigo mesmo.", valor: 1 },
      { texto: "Estou enojado de mim.", valor: 2 },
      { texto: "Eu me odeio.", valor: 3 },
    ] },
    { opcoes: [
      { texto: "Nao me sinto de qualquer modo pior que os outros.", valor: 0 },
      { texto: "Sou critico em relacao a mim por minhas fraquezas ou erros.", valor: 1 },
      { texto: "Eu me culpo sempre por minhas falhas.", valor: 2 },
      { texto: "Eu me culpo por tudo de mal que acontece.", valor: 3 },
    ] },
    { opcoes: [
      { texto: "Nao tenho quaisquer ideias de me matar.", valor: 0 },
      { texto: "Tenho ideias de me matar, mas nao as executaria.", valor: 1 },
      { texto: "Gostaria de me matar.", valor: 2 },
      { texto: "Eu me mataria se tivesse oportunidade.", valor: 3 },
    ] },
    { opcoes: [
      { texto: "Nao choro mais que o habitual.", valor: 0 },
      { texto: "Choro mais agora do que costumava.", valor: 1 },
      { texto: "Agora, choro o tempo todo.", valor: 2 },
      { texto: "Costumava ser capaz de chorar, mas agora nao consigo, mesmo que o queira.", valor: 3 },
    ] },
    { opcoes: [
      { texto: "Nao sou mais irritado agora do que ja fui.", valor: 0 },
      { texto: "Fico aborrecido ou irritado mais facilmente do que costumava.", valor: 1 },
      { texto: "Agora, eu me sinto irritado o tempo todo.", valor: 2 },
      { texto: "Nao me irrito mais com coisas que costumavam me irritar.", valor: 3 },
    ] },
    { opcoes: [
      { texto: "Nao perdi o interesse pelas outras pessoas.", valor: 0 },
      { texto: "Estou menos interessado pelas outras pessoas do que costumava estar.", valor: 1 },
      { texto: "Perdi a maior parte do meu interesse pelas outras pessoas.", valor: 2 },
      { texto: "Perdi todo o interesse pelas outras pessoas.", valor: 3 },
    ] },
    { opcoes: [
      { texto: "Tomo decisoes tao bem quanto antes.", valor: 0 },
      { texto: "Adio as tomadas de decisoes mais do que costumava.", valor: 1 },
      { texto: "Tenho mais dificuldades de tomar decisoes do que antes.", valor: 2 },
      { texto: "Absolutamente nao consigo mais tomar decisoes.", valor: 3 },
    ] },
    { opcoes: [
      { texto: "Nao acho que de qualquer modo pareco pior do que antes.", valor: 0 },
      { texto: "Estou preocupado em estar parecendo velho ou sem atrativo.", valor: 1 },
      { texto: "Acho que ha mudancas permanentes na minha aparencia, que me fazem parecer sem atrativo.", valor: 2 },
      { texto: "Acredito que pareco feio.", valor: 3 },
    ] },
    { opcoes: [
      { texto: "Posso trabalhar tao bem quanto antes.", valor: 0 },
      { texto: "E preciso algum esforco extra para fazer alguma coisa.", valor: 1 },
      { texto: "Tenho que me esforcar muito para fazer alguma coisa.", valor: 2 },
      { texto: "Nao consigo mais fazer qualquer trabalho.", valor: 3 },
    ] },
    { opcoes: [
      { texto: "Consigo dormir tao bem como o habitual.", valor: 0 },
      { texto: "Nao durmo tao bem como costumava.", valor: 1 },
      { texto: "Acordo 1 a 2 horas mais cedo do que habitualmente e acho dificil voltar a dormir.", valor: 2 },
      { texto: "Acordo varias horas mais cedo do que costumava e nao consigo voltar a dormir.", valor: 3 },
    ] },
    { opcoes: [
      { texto: "Nao fico mais cansado do que o habitual.", valor: 0 },
      { texto: "Fico cansado mais facilmente do que costumava.", valor: 1 },
      { texto: "Fico cansado em fazer qualquer coisa.", valor: 2 },
      { texto: "Estou cansado demais para fazer qualquer coisa.", valor: 3 },
    ] },
    { opcoes: [
      { texto: "O meu apetite nao esta pior do que o habitual.", valor: 0 },
      { texto: "Meu apetite nao e tao bom como costumava ser.", valor: 1 },
      { texto: "Meu apetite e muito pior agora.", valor: 2 },
      { texto: "Absolutamente nao tenho mais apetite.", valor: 3 },
    ] },
    { opcoes: [
      { texto: "Nao tenho perdido muito peso se e que perdi algum recentemente.", valor: 0 },
      { texto: "Perdi mais do que 2 quilos e meio.", valor: 1 },
      { texto: "Perdi mais do que 5 quilos.", valor: 2 },
      { texto: "Perdi mais do que 7 quilos.", valor: 3 },
    ] },
    { opcoes: [
      { texto: "Nao estou mais preocupado com a minha saude do que o habitual.", valor: 0 },
      { texto: "Estou preocupado com problemas fisicos, tais como dores, indisposicao do estomago ou constipacao.", valor: 1 },
      { texto: "Estou muito preocupado com problemas fisicos e e dificil pensar em outra coisa.", valor: 2 },
      { texto: "Estou tao preocupado com meus problemas fisicos que nao consigo pensar em qualquer outra coisa.", valor: 3 },
    ] },
    { opcoes: [
      { texto: "Nao notei qualquer mudanca recente no meu interesse por sexo.", valor: 0 },
      { texto: "Estou menos interessado por sexo do que costumava.", valor: 1 },
      { texto: "Estou muito menos interessado por sexo agora.", valor: 2 },
      { texto: "Perdi completamente o interesse por sexo.", valor: 3 },
    ] },
  ] as BDIItem[],
};

// ============ BHS ============
export const bhs: EscalaGeralConfig = {
  id: "bhs",
  sigla: "BHS",
  nome: "Escala de Desesperanca de Beck",
  instrucoes: "Leia cuidadosamente e decida se a afirmacao descreve ou nao a sua atitude na ultima semana, incluindo hoje.",
  tipo: "binary",
  pontuacaoMaxima: 20,
  opcoes: [
    { label: "Certo", valor: 1 },
    { label: "Errado", valor: 0 },
  ],
  chaveCorrecao: {
    1: "E", 2: "C", 3: "E", 4: "C", 5: "E",
    6: "E", 7: "C", 8: "E", 9: "C", 10: "E",
    11: "C", 12: "C", 13: "E", 14: "C", 15: "E",
    16: "C", 17: "C", 18: "C", 19: "E", 20: "C",
  },
  itens: [
    "Penso no futuro com esperanca e entusiasmo.",
    "Seria melhor desistir, porque nada ha que eu possa fazer para tornar as coisas melhores para mim.",
    "Quando as coisas vao mal, me ajuda saber que elas nao podem continuar assim para sempre.",
    "Nao consigo imaginar que especie da vida sera a minha em dez anos.",
    "Tenho tempo suficiente para realizar as coisas que quero fazer.",
    "No futuro, eu espero ter sucesso no que mais me interessa.",
    "Meu futuro me parece negro.",
    "Acontece que tenho uma sorte especial e espero conseguir mais coisas boas da vida do que uma pessoa comum.",
    "Simplesmente nao consigo aproveitar as oportunidades e nao ha razao para que consiga, no futuro.",
    "Minhas experiencias passadas me prepararam bem para o futuro.",
    "Tudo o que posso ver a minha frente e mais desprazer do que prazer.",
    "Nao espero conseguir o que realmente quero.",
    "Quando penso no futuro, espero ser mais feliz do que sou agora.",
    "As coisas simplesmente nao se resolvem da maneira que eu quero.",
    "Tenho uma grande fe no futuro.",
    "Nunca consigo o que quero. Assim, e tolice querer qualquer coisa.",
    "E pouco provavel que eu va obter qualquer satisfacao real, no futuro.",
    "O futuro me parece vago e incerto.",
    "Posso esperar mais tempos bons do que maus.",
    "Nao adianta tentar realmente obter algo que quero, porque provavelmente nao vou conseguir.",
  ],
};

// ============ EBEP ============
export const ebep: EscalaGeralConfig = {
  id: "ebep",
  sigla: "EBEP",
  nome: "Escala de Bem-Estar Psicologico",
  instrucoes: "Leia cada afirmacao e avalie o quanto voce concorda com cada uma, usando a escala de 1 (Discordo totalmente) a 6 (Concordo totalmente).",
  tipo: "likert",
  opcoes: [
    { label: "Discordo totalmente", valor: 1 },
    { label: "Discordo em grande parte", valor: 2 },
    { label: "Discordo ligeiramente", valor: 3 },
    { label: "Concordo ligeiramente", valor: 4 },
    { label: "Concordo em grande parte", valor: 5 },
    { label: "Concordo totalmente", valor: 6 },
  ],
  invertidos: [2, 4, 7, 9, 11, 13, 15, 17, 18, 20, 22, 24, 27, 29, 31, 32, 34, 35, 41, 42, 43, 44, 45, 54, 55, 56, 58, 60, 61, 62, 63, 65, 66, 73, 74, 75, 76, 82, 83, 84],
  dominios: [
    { id: "relacoes", nome: "Relacoes Positivas", itens: [1,7,13,19,25,31,37,43,49,55,61,67,73,79] },
    { id: "autonomia", nome: "Autonomia", itens: [2,8,14,20,26,32,38,44,50,56,62,68,74,80] },
    { id: "dominio", nome: "Dominio do Ambiente", itens: [3,9,15,21,27,33,39,45,51,57,63,69,75,81] },
    { id: "crescimento", nome: "Crescimento Pessoal", itens: [4,10,16,22,28,34,40,46,52,58,64,70,76,82] },
    { id: "proposito", nome: "Proposito na Vida", itens: [5,11,17,23,29,35,41,47,53,59,65,71,77,83] },
    { id: "autoaceitacao", nome: "Autoaceitacao", itens: [6,12,18,24,30,36,42,48,54,60,66,72,78,84] },
  ],
  itens: [
    "A maioria das pessoas me ve como amavel e afetuoso",
    "As vezes eu mudo minha maneira de agir ou pensar para parecer mais com as pessoas a minha volta",
    "Sinto que tenho controle sobre as situacoes do meu dia-a-dia",
    "Eu nao tenho interesse em atividades nas quais possa conhecer coisas nova",
    "Sinto-me bem quando penso no que eu fiz no passado e o que eu espero fazer no futuro",
    "Quando olho para a historia da minha vida, fico satisfeito com a maneira como as coisas aconteceram",
    "Manter relacoes intimas com outras pessoas tem sido dificil e frustrante para mim",
    "Nao tenho medo de expressar minhas opinioes, mesmo quando elas sao contrarias as opinioes da maioria das pessoas",
    "As exigencias do dia-a-dia geralmente me deixam desanimado",
    "De forma geral, sinto que eu continuo aprendendo mais a meu respeito com o passar do tempo",
    "Eu vivo um dia de cada vez e nao penso muito no futuro",
    "De forma geral, sinto-me confiante e positivo sobre mim mesmo",
    "Frequentemente, sinto-me solitario porque tenho poucos amigos intimos com quem eu posso compartilhar minhas preocupacoes",
    "Minhas decisoes geralmente nao sao influenciadas pelo que os outros estao fazendo",
    "Eu nao me integro muito bem as pessoas e a comunidade a minha volta",
    "Sou o tipo de pessoa que gosta de experimentar coisas novas",
    "Costumo me deter no presente, porque pensar no futuro quase sempre me traz problemas",
    "Eu percebo que muitas pessoas tiveram mais sucesso na vida do que eu",
    "Eu gosto de conversas pessoais e corriqueiras com familiares e amigos",
    "Muitas vezes me preocupo com o que os outros pensam sobre mim",
    "Eu sou muito bom em gerenciar as diversas responsabilidades da minha vida diaria",
    "Nao quero experimentar novas formas de fazer as coisas - minha vida esta bem do jeito que esta",
    "Acredito possuir objetivos e propositos na minha vida",
    "Se eu pudesse, mudaria muitas coisas em mim",
    "E importante pra mim escutar meu amigos quando eles falam sobre seus problemas",
    "Estar feliz comigo mesmo e mais importante para mim do que a aprovacao dos outros",
    "Geralmente sinto-me sobrecarregado por minhas responsabilidades",
    "Eu acredito que e importante ter experiencias novas que desafiem o que voce pensa sobre voce mesmo e sobre o mundo",
    "Na maioria das vezes, acho minhas atividades desinteressantes e banais",
    "Gosto de ser do jeito que sou",
    "Eu nao tenho muitas pessoas que queiram me ouvir quando eu preciso falar",
    "Eu tenho a tendencia a ser influenciado por pessoas com opinioes fortes",
    "Se eu estivesse infeliz com minha situacao de vida, tomaria atitudes concretas para muda-la",
    "Ao pensar sobre mim, percebo que nao melhorei muito como pessoa ao longo dos anos",
    "Eu nao tenho clareza sobre o que eu estou tentando alcancar na vida",
    "Eu cometi alguns erros no passado, mas sinto que, no geral, as coisas se resolveram da melhor maneira",
    "Eu sinto que ganho muito com as minhas amizades",
    "As pessoas dificilmente me convencem a fazer coisas que eu nao queira",
    "Eu normalmente gerencio bem minhas financas e negocios",
    "Em minha opiniao, pessoas de todas as idades sao capazes de continuar crescendo e se desenvolvendo",
    "Eu costumava estabelecer metas para mim mesmo, mas agora isso parece uma perda de tempo",
    "De um modo geral, me sinto decepcionado com o que alcancei na vida",
    "Parece-me que a maioria das pessoas tem mais amigos do que eu",
    "Acho mais importante pensar como os outros do que ficar sozinho em meus principios",
    "Acho muito estressante nao conseguir levar adiante tudo que preciso fazer no dia-a-dia",
    "Eu aprendi com a vida muitas coisas ao longo do tempo, o que me tornou uma pessoa forte e capaz",
    "Eu gosto de fazer planos para o futuro e trabalhar para torna-los realidade",
    "Em geral, tenho orgulho de quem sou e da vida que levo",
    "As pessoas me descreveriam como alguem disposta a compartilhar meu tempo com os outros",
    "Eu tenho confianca nas minhas opinioes, ainda que elas sejam contrarias ao consenso geral",
    "Consigo administrar bem meu tempo, desta maneira consigo fazer tudo o que deve ser feito",
    "Eu acredito que cresci muito como pessoa ao longo do tempo",
    "Sou uma pessoa ativa para executar os planos que estipulei pra mim mesmo",
    "Invejo muitas pessoas pelo tipo de vida que elas levam",
    "Eu nao tenho vivido muitas relacoes afetuosas e co nfiaveis com outras pessoas",
    "E dificil para mim opinar sobre assuntos polemicos",
    "Minha vida diaria e atarefada, mas me sinto satisfeito em manter tudo em dia",
    "Eu nao gosto de situacoes novas que exigem que eu troque meus velhos habitos de fazer as coisas",
    "Algumas pessoas vagam sem proposito na vida, mas eu nao sou uma delas",
    "Minha atitude sobre mim mesmo provavelmente nao e tao positiva quanto a da maioria das pessoas sobre si mesmas",
    "Em relacao as amizades, eu geralmente me sinto deslocado",
    "Muitas vezes, eu mudo de opiniao se meus amigos ou familiares discordam das minhas decisoes",
    "Eu fico frustrado quando tento planejar minhas atividades diarias porque eu nunca consigo fazer as coisas que planejo",
    "Para mim, a vida e um continuo processo de aprendizado, mudanca e crescimento",
    "As vezes sinto que ja fiz tudo o que tinha para fazer na vida",
    "Muitas vezes eu acordo desanimado com o jeito que tenho levado minha vida",
    "Eu sei que posso confiar em meus amigos, e eles sabem que podem confiar em mim",
    "Eu nao sou o tipo de pessoa que cede a pressoes sociais para pensar ou agir de determinadas formas",
    "Tenho tido sucesso na busca de atividades e relacionamentos que necessito",
    "Eu gosto de ver como minhas opinioes mudaram e amadureceram ao longo dos anos",
    "Meus objetivos na vida tem sido mais uma fonte de satisfacao do que de frustracao para mim",
    "Meu passado teve altos e baixos, mas de modo geral eu nao gostaria de muda-lo",
    "Eu acho dificil me abrir quando eu falo com os outros",
    "Eu me preocupo com as avaliacoes dos outros sobre as escolhas que eu faco na minha vida",
    "Eu tenho dificuldades para organizar minha vida de uma forma satisfatoria para mim",
    "Eu desisti de fazer grandes mudancas ou melhoras na minha vida ha muito tempo atras",
    "Eu fico satisfeito quando penso no que eu ja realizei na vida",
    "Quando eu me comparo a amigos e conhecidos, sinto-me bem em relacao a quem eu sou",
    "Meus amigos e eu somos solidarios aos problemas uns dos outros",
    "Eu julgo a mim mesmo pelo que eu penso que e importante, nao pelos valores que os outros consideram importantes",
    "Tenho sido capaz de construir um lar e um estilo de vida para mim mesmo que correspondem ao que eu quero",
    "Acredito que pessoas mais velhas nao queiram aprender coisas novas",
    "Nao estou certo que minha vida tenha algum sentido",
    "Todos tem suas limitacoes, mas eu pareco ter mais que os outros",
  ],
};

// ============ LESS ============
export const less: EscalaGeralConfig = {
  id: "less",
  sigla: "LESS",
  nome: "Escala de Esquemas Emocionais de Leahy",
  instrucoes: "Leia cada afirmacao e avalie o quanto voce concorda, usando a escala de 1 (Discordo totalmente) a 6 (Concordo totalmente).",
  tipo: "likert",
  opcoes: [
    { label: "Discordo totalmente", valor: 1 },
    { label: "Discordo", valor: 2 },
    { label: "Discordo levemente", valor: 3 },
    { label: "Concordo levemente", valor: 4 },
    { label: "Concordo", valor: 5 },
    { label: "Concordo totalmente", valor: 6 },
  ],
  dominios: [
    { id: "validacao", nome: "Validacao", itens: [8,16,49], invertidos: [16,49] },
    { id: "intelig", nome: "Inteligibilidade", itens: [5,10,33,45], invertidos: [5,10,33,45] },
    { id: "valores", nome: "Valores mais elevados", itens: [21,25,42], invertidos: [25] },
    { id: "controle", nome: "Controle", itens: [7,27,44], invertidos: [7,27,44] },
    { id: "consenso", nome: "Consenso", itens: [3,19,39,41], invertidos: [3,19] },
    { id: "aceitacao", nome: "Aceitacao", itens: [1,2,9,12,20,28,36,40,50], invertidos: [1,2,9,12,20,28,36,50] },
    { id: "expressao", nome: "Expressao", itens: [6,23] },
    { id: "culpa", nome: "Culpa / Vergonha", itens: [4,14,26,31] },
    { id: "simples", nome: "Visao Simplista", itens: [18,35,38,47] },
    { id: "entorpecimento", nome: "Entorpecimento", itens: [15,32] },
    { id: "racional", nome: "Necessidade de ser Racional", itens: [17,30,46] },
    { id: "duracao", nome: "Duracao", itens: [13,29], invertidos: [29] },
    { id: "ruminacao", nome: "Ruminacao", itens: [24,37,48] },
    { id: "responsabilidade", nome: "Culpar os Outros", itens: [11,34] },
  ],
  itens: [
    "Quando me sinto para baixo, tento pensar em uma maneira diferente de ver as coisas.",
    "Quando tenho um sentimento que me incomoda, tento pensar em uma razao pela qual ele nao e importante.",
    "Frequentemente penso que reajo com sentimentos que outras pessoas nao teriam.",
    "E errado ter determinados sentimentos.",
    "Ha coisas a meu respeito que simplesmente nao compreendo.",
    "Acredito que e importante me permitir chorar para deixar meus sentimentos \"sairem\".",
    "Se me permitir ter alguns desses sentimentos, temo perder o controle.",
    "Os outros compreendem e aceitam meus sentimentos.",
    "Voce nao pode permitir-se ter certos tipos de sentimentos como aqueles relacionados a sexo ou violencia.",
    "Meus sentimentos nao fazem sentido para mim.",
    "Se as outras pessoas mudassem, eu me sentiria muito melhor.",
    "Acho que tenho sentimentos dos quais nao estou de fato consciente.",
    "As vezes receio que, se me permitisse ter um sentimento forte, ele nao iria mais embora.",
    "Sinto vergonha de meus sentimentos.",
    "Coisas que incomodam outras pessoas nao me incomodam.",
    "Ninguem se importa realmente com meus sentimentos.",
    "E importante que eu seja razoavel e pratico em vez de sensivel e aberto a meus sentimentos.",
    "Nao consigo suportar ter sentimentos contraditorios - como gostar e nao gostar da mesma pessoa.",
    "Sou muito mais sensivel que as outras pessoas.",
    "Tento me livrar dos sentimentos desagradaveis imediatamente.",
    "Quando me sinto para baixo, tento pensar nas coisas mais importantes da vida - aquilo que valorizo.",
    "Quando me sinto para baixo ou triste, questiono meus valores.",
    "Sinto que posso expressar meus sentimentos abertamente.",
    "Frequentemente digo a mim mesmo: \"O que ha de errado comigo?\".",
    "Vejo-me como uma pessoa superficial.",
    "Quero que as pessoas acreditem que eu seja diferente do jeito como me sinto de verdade.",
    "Fico preocupado com a ideia de nao ser capaz de controlar meus sentimentos.",
    "Voce precisa se policiar contra certos sentimentos.",
    "Sentimentos fortes duram apenas um curto periodo.",
    "Voce nao pode depender dos sentimentos para saber o que e bom pra voce.",
    "Eu nao deveria ter alguns dos sentimentos que tenho.",
    "Com frequencia, sinto-me anestesiado emocionalmente, como se nao tivesse sentimentos.",
    "Acho que meus sentimentos sao estranhos ou esquisitos.",
    "Outras pessoas provocam em mim sentimentos desagradaveis.",
    "Quando tenho sentimentos conflitantes em relacao a alguem, fico perturbado ou confuso.",
    "Quando tenho um sentimento que me incomoda, tento encontrar outra coisa para pensar ou fazer.",
    "Quando me sinto para baixo, fico sozinho e penso muito em como me sinto mal.",
    "Gosto de ter absoluta certeza em relacao a como me sinto em relacao a outra pessoa.",
    "Todos tem sentimentos como os meus.",
    "Aceito meus sentimentos.",
    "Acho que tenho os mesmos sentimentos que outras pessoas tem.",
    "Aspiro a valores mais elevados.",
    "Penso que meus sentimentos agora nao tem nada a ver com o modo como fui criado.",
    "Tenho a preocupacao de que, se tiver certos sentimentos, posso ficar louco.",
    "Meus sentimentos parecem vir do nada.",
    "Acho que e importante ser racional e logico em quase tudo.",
    "Gosto de ter absoluta certeza sobre o modo como me sinto em relacao a mim mesmo.",
    "Foco muito em meus sentimentos ou sensacoes fisicas.",
    "Nao quero que ninguem saiba de alguns dos meus sentimentos.",
    "Nao quero admitir que tenho certos sentimentos, mas sei que os tenho.",
  ],
};

// ============ NEO-FFI-R ============
export const neoffir: EscalaGeralConfig = {
  id: "neoffir",
  sigla: "NEO-FFI-R",
  nome: "Inventario de Personalidade NEO Revisado (Versao Curta)",
  instrucoes: "Leia cada afirmacao e avalie o quanto ela descreve voce, de DF (Discordo Fortemente) a CF (Concordo Fortemente).",
  tipo: "likert",
  opcoes: [
    { label: "Discordo fortemente", valor: 0 },
    { label: "Discordo", valor: 1 },
    { label: "Neutro", valor: 2 },
    { label: "Concordo", valor: 3 },
    { label: "Concordo fortemente", valor: 4 },
  ],
  invertidos: [1, 16, 31, 46, 12, 27, 42, 57, 18, 23, 28, 33, 48, 9, 14, 19, 24, 39, 44, 54, 59, 15, 30, 45, 55],
  dominios: [
    { id: "N", nome: "Neuroticismo", itens: [1,6,11,16,21,26,31,36,41,46,51,56], invertidos: [1,16,31,46] },
    { id: "E", nome: "Extroversao", itens: [2,7,12,17,22,27,32,37,42,47,52,57], invertidos: [12,27,42,57] },
    { id: "O", nome: "Abertura a Experiencia", itens: [3,8,13,18,23,28,33,38,43,48,53,58], invertidos: [18,23,28,33,48] },
    { id: "A", nome: "Amabilidade", itens: [4,9,14,19,24,29,34,39,44,49,54,59], invertidos: [9,14,19,24,39,44,54,59] },
    { id: "C", nome: "Conscienciosidade", itens: [5,10,15,20,25,30,35,40,45,50,55,60], invertidos: [15,30,45,55] },
  ],
  itens: [
    "Sou uma pessoa despreocupada.",
    "Gosto de ter muita gente a minha volta.",
    "Gosto de me concentrar numa fantasia e explorar todas as suas possibilidades, deixando-a crescer e se desenvolver.",
    "Tento ser educado(a) com todas as pessoas que encontro.",
    "Mantenho as minhas coisas limpas e em ordem.",
    "Algumas vezes senti ressentimento e amargura.",
    "Sou propenso(a) a rir facilmente.",
    "Acho interessante aprender e cultivar novos hobbies (passatempos).",
    "As vezes, intimido ou bajulo as pessoas para que elas facam o que eu quero.",
    "Eu sou bom (boa) em organizar meu tempo de maneira a fazer as coisas dentro do prazo.",
    "Quando estou sob uma grande tensao, algumas vezes sinto que nao vou resistir.",
    "Prefiro trabalhos que possa fazer sozinho(a), sem ser incomodado(a) por outras pessoas.",
    "Fico admirado(a) com a variedade de padroes que encontro na arte e na natureza.",
    "Algumas pessoas pensam que sou invejoso(a) e egoista.",
    "Frequentemente entro em situacoes sem estar totalmente preparado(a) para elas.",
    "Raramente me sinto so ou triste.",
    "Gosto muito de falar com as outras pessoas.",
    "Acredito que deixar estudantes ouvirem pessoas com ideias controversas so vai confundi-los e desorienta-los.",
    "Se alguem comeca uma briga, estou sempre pronto(a) para revidar.",
    "Tento cumprir todas as minhas obrigacoes com responsabilidade.",
    "Frequentemente, sinto-me tenso(a) e agitado(a).",
    "Gosto de estar em lugares animados.",
    "A poesia pouco ou nada me sensibiliza.",
    "Sou melhor que a maioria das pessoas e tenho consciencia disso.",
    "Tenho objetivos claros e busco atingi-los de forma organizada.",
    "As vezes, sinto que eu nao valho nada.",
    "Nao gosto de multidoes e por isso as evito.",
    "Tenho dificuldade em soltar a minha imaginacao (devanear).",
    "Quando sou insultado(a), tento perdoar e esquecer.",
    "Perco muito tempo antes de me concentrar no trabalho.",
    "Raramente me sinto amedrontado(a) ou ansioso(a).",
    "Frequentemente, sinto-me explodindo de energia.",
    "Raramente me dou conta dos humores ou sentimentos que diferentes ambientes causam.",
    "Tendo a pensar o melhor acerca das pessoas.",
    "Trabalho muito para conseguir o que quero.",
    "Muitas vezes, fico irritado(a) com a maneira como as pessoas me tratam.",
    "Sou uma pessoa alegre e bem disposta.",
    "Experimento uma grande variedade de emocoes e sentimentos.",
    "Algumas pessoas consideram-me frio(a) e calculista.",
    "Quando assumo um compromisso as pessoas confiam que vou cumprir.",
    "Muitas vezes, quando as coisas dao errado, fico desanimado(a) e tenho vontade de desistir.",
    "Eu nao gosto muito de ficar conversando com as pessoas.",
    "As vezes, ao ler poesia ou ao olhar para uma obra de arte, sinto um arrepio, uma onda de emocao.",
    "Sou cabecudo(a) e teimoso(a).",
    "As vezes, nao sou tao confiavel como deveria ser.",
    "Raramente estou triste ou deprimido(a).",
    "Minha vida e agitada.",
    "Tenho pouco interesse em especular sobre a natureza do universo ou da condicao humana.",
    "Geralmente, procuro ser atencioso(a) e delicado(a).",
    "Eu sou uma pessoa produtiva que sempre consegue fazer as coisas.",
    "Sinto-me, muitas vezes, desamparado(a), desejando que alguem resolva os meus problemas.",
    "Sou uma pessoa muito ativa.",
    "Tenho muita curiosidade intelectual.",
    "Quando nao gosto de alguem, faco questao de demonstrar.",
    "Parece que nunca consigo ser organizado(a).",
    "Algumas vezes me senti tao envergonhado(a) que simplesmente queria sumir.",
    "Prefiro tratar da minha vida a ser um(a) lider para outras pessoas.",
    "Muitas vezes, sinto prazer em brincar com teorias e ideias abstratas.",
    "Se for necessario, estou disposto(a) a manipular as pessoas para conseguir aquilo que quero.",
    "Esforco-me por ser excelente em tudo que faco.",
  ],
};

// ============ NEO-PI-R ============
// Build domain structure from estruturaFaceta
export const neopir: EscalaGeralConfig = {
  id: "neopir",
  sigla: "NEO-PI-R",
  nome: "Inventario de Personalidade NEO Revisado",
  instrucoes: "Leia cada afirmacao e avalie o quanto ela descreve voce, de DF (Discordo Fortemente) a CF (Concordo Fortemente).",
  tipo: "likert",
  opcoes: [
    { label: "Discordo fortemente", valor: 0 },
    { label: "Discordo", valor: 1 },
    { label: "Neutro", valor: 2 },
    { label: "Concordo", valor: 3 },
    { label: "Concordo fortemente", valor: 4 },
  ],
  invertidos: [1, 4, 7, 8, 10, 11, 13, 14, 17, 18, 20, 21, 24, 27, 28, 30, 32, 33, 35, 39, 42, 43, 45, 46, 49, 52, 53, 54, 55, 56, 59, 60, 61, 64, 67, 68, 70, 71, 74, 77, 78, 79, 80, 81, 84, 87, 88, 89, 90, 92, 93, 95, 96, 99, 102, 103, 105, 106, 109, 112, 113, 116, 118, 119, 124, 127, 128, 129, 130, 132, 134, 137, 138, 140, 141, 144, 147, 150, 153, 155, 156, 159, 162, 163, 166, 169, 173, 175, 176, 181, 183, 187, 189, 190, 198, 199, 205, 206, 207, 208, 213, 220, 222, 225, 228, 229, 231, 234, 236],
  dominios: [
    { id: "N", nome: "Neuroticismo", itens: [1,6,11,16,21,26,31,36,41,46,51,56,61,66,71,76,81,86,91,96,101,106,111,116,121,126,131,136,141,146,151,156,161,166,171,176,181,186,191,196,201,206,211,216,221,226,231,236], invertidos: [1,11,21,46,56,61,71,81,96,106,116,141,156,166,176,181,206,231,236] },
    { id: "E", nome: "Extroversao", itens: [2,7,12,17,22,27,32,37,42,47,52,57,62,67,72,77,82,87,92,97,102,107,112,117,122,127,132,137,142,147,152,157,162,167,172,177,182,187,192,197,202,207,212,217,222,227,232,237], invertidos: [7,17,27,32,42,52,67,77,87,92,102,112,127,132,137,147,162,187,207,222] },
    { id: "O", nome: "Abertura a Experiencia", itens: [3,8,13,18,23,28,33,38,43,48,53,58,63,68,73,78,83,88,93,98,103,108,113,118,123,128,133,138,143,148,153,158,163,168,173,178,183,188,193,198,203,208,213,218,223,228,233,238], invertidos: [8,13,18,28,33,43,53,68,78,88,93,103,113,118,128,138,153,163,173,183,198,208,213,228] },
    { id: "A", nome: "Amabilidade", itens: [4,9,14,19,24,29,34,39,44,49,54,59,64,69,74,79,84,89,94,99,104,109,114,119,124,129,134,139,144,149,154,159,164,169,174,179,184,189,194,199,204,209,214,219,224,229,234,239], invertidos: [4,14,24,39,49,54,59,64,74,79,84,89,99,109,119,124,129,134,144,159,169,189,199,229,234] },
    { id: "C", nome: "Conscienciosidade", itens: [5,10,15,20,25,30,35,40,45,50,55,60,65,70,75,80,85,90,95,100,105,110,115,120,125,130,135,140,145,150,155,160,165,170,175,180,185,190,195,200,205,210,215,220,225,230,235,240], invertidos: [10,20,30,35,45,55,60,70,80,90,95,105,130,140,150,155,175,190,205,220,225] },
  ],
  itens: [
    "Sou uma pessoa despreocupada.",
    "Gosto realmente da maioria das pessoas que encontro.",
    "Tenho uma imaginacao muito fertil.",
    "Tendo a ser descrente frente as intencoes dos outros.",
    "Sou conhecido(a) pela minha prudencia e bom senso.",
    "Muitas vezes, fico irritado(a) com a maneira como as pessoas me tratam.",
    "Nao gosto de multidoes e por isso as evito.",
    "Assuntos de estetica e de arte nao sao muito importantes para mim.",
    "Nao sou dissimulado(a) nem espertalhao(ona).",
    "Prefiro deixar as opcoes em aberto que planejar tudo com antecedencia.",
    "Raramente me sinto so ou triste.",
    "Sou dominador(a), firme e assertivo(a).",
    "Sem emocoes fortes a vida nao teria muita graca para mim.",
    "Algumas pessoas pensam que sou invejoso(a) e egoista.",
    "Tento cumprir todas as minhas obrigacoes com responsabilidade.",
    "Ao lidar com outras pessoas, sempre tenho medo de fazer alguma coisa errada.",
    "Gosto de realizar as coisas com calma.",
    "Sou bastante agarrado(a) as minhas proprias maneiras de agir.",
    "Prefiro colaborar com as outras pessoas a competir com elas.",
    "Sou despreocupado(a) e pouco determinado(a).",
    "Raramente me excedo em qualquer coisa.",
    "Sinto, muitas vezes, forte necessidade de me divertir.",
    "Muitas vezes, sinto prazer em brincar com teorias e ideias abstratas.",
    "Nao me incomodo de me vangloriar de meus talentos e sucessos.",
    "Eu sou bom (boa) em organizar meu tempo de maneira a fazer as coisas dentro do prazo.",
    "Sinto-me, muitas vezes, desamparado(a), desejando que alguem resolva os meus problemas.",
    "Para dizer a verdade, nunca pulei de alegria.",
    "Acredito que deixar estudantes ouvirem pessoas com ideias controversas so vai confundi-los e desorienta-los.",
    "Os governantes precisam estar muito mais atentos para o lado humano dos seus projetos politicos.",
    "Ao longo dos anos cometi muitos erros.",
    "Assusto-me facilmente.",
    "Eu nao gosto muito de ficar conversando com as pessoas.",
    "Tento sempre organizar os meus pensamentos de forma realista, nao dando asas a imaginacao.",
    "Acredito que a maioria das pessoas e, no fundo, bem intencionada.",
    "Nao levo muito a serio os deveres civicos, como votar.",
    "Sou uma pessoa tranquila.",
    "Gosto de ter muita gente a minha volta.",
    "Em algumas ocasioes, quando ouco musica, nao presto atencao em mais nada.",
    "Se for necessario, estou disposto(a) a manipular as pessoas para conseguir aquilo que quero.",
    "Mantenho as minhas coisas limpas e em ordem.",
    "As vezes, sinto que eu nao valho nada.",
    "As vezes, eu deveria mostrar maior firmeza em minhas acoes.",
    "Raramente experimento fortes emocoes.",
    "Tento ser educado(a) com todas as pessoas que encontro.",
    "As vezes, nao sou tao confiavel como deveria ser.",
    "Raramente me sinto constrangido(a) quando estou rodeado(a) de pessoas.",
    "Quando faco alguma coisa, eu faco com todo o entusiasmo.",
    "Acho interessante aprender e cultivar novos hobbies (passatempos).",
    "Sei ser sarcastico(a) e ironico(a) quando necessario.",
    "Tenho objetivos claros e busco atingi-los de forma organizada.",
    "Tenho dificuldade em resistir aos meus desejos.",
    "Nao gostaria de passar as ferias em um lugar muito frequentado e agitado.",
    "Acho as discussoes filosoficas enfadonhas (chatas).",
    "Quando estou conversando com as pessoas, prefiro nao falar de mim mesmo(a) e das minhas realizacoes.",
    "Perco muito tempo antes de me concentrar no trabalho.",
    "Sinto que sou capaz de resolver a maioria dos meus problemas.",
    "Ja experimentei, algumas vezes, sensacoes de grande alegria ou de extase (arrebatamento).",
    "Acredito que as leis e as politicas sociais deveriam mudar para que possam refletir as necessidades atuais.",
    "Sou inflexivel e teimoso(a) nas minhas atitudes.",
    "Penso muito antes de tomar uma decisao.",
    "Raramente me sinto amedrontado(a) ou ansioso(a).",
    "Sou uma pessoa amigavel e simpatica.",
    "Tenho uma grande capacidade de fantasiar.",
    "Acredito que, se voce deixar, as pessoas vao te passar para tras (enganar).",
    "Mantenho-me informado(a) e, geralmente, tomo decisoes inteligentes.",
    "Eu sou conhecido(a) como uma pessoa esquentada.",
    "Normalmente, prefiro fazer as coisas sozinho(a).",
    "Assistir bale ou danca moderna me deixa entediado(a).",
    "Mesmo que quisesse, nao conseguiria enganar ninguem.",
    "Nao sou uma pessoa muito metodica (ordeira).",
    "Raramente estou triste ou deprimido(a).",
    "Ja fui muitas vezes lider de grupos a que pertenci.",
    "E importante para mim como eu me sinto frente a pessoas ou situacoes.",
    "Algumas pessoas consideram-me frio(a) e calculista.",
    "Pago minhas dividas em dia.",
    "Algumas vezes me senti tao envergonhado(a) que simplesmente queria sumir.",
    "Trabalho devagar, mas persistentemente (de forma regular).",
    "Quando encontro a maneira correta de fazer uma coisa me agarro a ela.",
    "Apesar de ter direito, tenho receio em mostrar a minha indignacao e raiva, pois posso magoar as pessoas.",
    "Quando inicio um programa de modificacao pessoal (regime, esporte), deixo de cumpri-lo apos alguns dias.",
    "Eu nao tenho dificuldade em resistir as tentacoes.",
    "Ja fiz algumas coisas so por puro entusiasmo.",
    "Gosto de resolver problemas e quebra-cabecas.",
    "Sou melhor que a maioria das pessoas e tenho consciencia disso.",
    "Eu sou uma pessoa produtiva que sempre consegue fazer as coisas.",
    "Quando estou sob uma grande tensao, algumas vezes sinto que nao vou resistir.",
    "Nao sou um(a) grande otimista.",
    "Acredito que devemos confiar nas nossas autoridades religiosas para decisoes sobre assuntos morais.",
    "Nunca fazemos o suficiente pelos pobres e pelos velhos.",
    "As vezes, ajo primeiro e penso depois.",
    "Frequentemente, sinto-me tenso(a) e agitado(a).",
    "Muitas pessoas me veem como alguem um pouco frio e distante.",
    "Nao gosto de perder tempo sonhando acordado(a).",
    "Penso que a maioria das pessoas com quem lido e honesta e digna de confianca.",
    "Frequentemente entro em situacoes sem estar totalmente preparado(a) para elas.",
    "Nao sou considerado(a) uma pessoa melindrosa e temperamental.",
    "Sinto muita necessidade de estar com outras pessoas quando fico sozinho(a) durante muito tempo.",
    "Fico admirado(a) com a variedade de padroes que encontro na arte e na natureza.",
    "Penso que ser totalmente honesto(a) nao e uma boa maneira de fazer negocios.",
    "Gosto de ter as coisas no seu lugar, pois assim sei onde posso encontra-las.",
    "Ja senti, algumas vezes, uma sensacao profunda de culpa ou de ter pecado.",
    "Geralmente, nas reunioes, deixo os outros falarem.",
    "Raramente presto muita atencao ao que estou sentindo no momento.",
    "Geralmente, procuro ser atencioso(a) e delicado(a).",
    "Em alguns jogos, acho divertido conseguir trapacear os outros sem ser percebido.",
    "Nao fico desconcertado(a) se as pessoas me ridicularizam ou me provocam.",
    "Frequentemente, sinto-me explodindo de energia.",
    "Frequentemente, experimento comidas novas e desconhecidas.",
    "Quando nao gosto de alguem, faco questao de demonstrar.",
    "Trabalho muito para conseguir o que quero.",
    "Tenho tendencia a me esbaldar, a agir em excesso, quando estou diante de coisas ou situacoes que gosto muito.",
    "Procuro evitar filmes com cenas muito chocantes ou assustadoras.",
    "As vezes, perco o interesse quando as pessoas comecam a falar sobre assuntos muito teoricos e abstratos.",
    "Tento ser humilde.",
    "Tenho dificuldade em comecar a fazer o que eu devo fazer.",
    "Em casos de emergencia, mantenho a cabeca fria.",
    "As vezes, sinto que vou explodir de alegria.",
    "Considero que definir o que e certo e errado depende da cultura em que as pessoas vivem.",
    "Nao gosto de mendigos.",
    "Sempre penso nas consequencias antes de agir.",
    "Fico apreensivo(a) com o futuro.",
    "Gosto muito de falar com as outras pessoas.",
    "Gosto de me concentrar numa fantasia e explorar todas as suas possibilidades, deixando ela crescer e se desenvolver.",
    "Fico desconfiado(a) quando alguem faz alguma coisa boa para mim.",
    "Tenho orgulho do meu bom senso.",
    "Frequentemente, sinto antipatia pelas pessoas com as quais tenho que conviver.",
    "Prefiro trabalhos que possa fazer sozinho(a), sem ser incomodado(a) por outras pessoas.",
    "A poesia pouco ou nada me sensibiliza.",
    "Ficaria aborrecido(a) se alguem me considerasse um(a) pessoa hipocrita.",
    "Parece que nunca consigo ser organizado(a).",
    "Tenho tendencia a me culpar se alguma coisa da errado.",
    "Muitas vezes, outras pessoas pedem para eu ajuda-las a tomar decisoes.",
    "Experimento uma grande variedade de emocoes e sentimentos.",
    "Nao sou conhecido(a) como alguem generoso.",
    "Quando assumo um compromisso as pessoas confiam que vou cumprir.",
    "Sinto-me, muitas vezes, inferior as outras pessoas.",
    "Nao sou tao ativo(a) e animado(a) como as outras pessoas.",
    "Prefiro ficar em ambientes conhecidos.",
    "Quando sou insultado(a), tento perdoar e esquecer.",
    "Nao sou ambicioso(a).",
    "Tenho facilidade em resistir a meus impulsos.",
    "Gosto de estar em lugares animados.",
    "Gosto de resolver problemas complicados do tipo quebra-cabecas.",
    "Eu tenho uma opiniao muito boa sobre mim.",
    "Quando comeco um projeto, quase sempre o termino.",
    "Frequentemente, tenho dificuldade em tomar decisoes.",
    "Nao me considero uma pessoa alegre.",
    "Acredito que e mais importante ser fiel aos meus ideais e principios do que ter uma mente aberta.",
    "As necessidades humanas sao mais importantes que os interesses economicos.",
    "Costumo agir sem pensar.",
    "Frequentemente me preocupo com as coisas que podem dar errado.",
    "E facil para mim sorrir e ser simpatico(a) com pessoas desconhecidas.",
    "Quando percebo que estou sendo levado(a) pela minha propria imaginacao, procuro me concentrar, ocupando-me com algum trabalho ou atividade.",
    "Minha primeira reacao e confiar nas pessoas.",
    "Eu acho que nao tive sucesso completo em coisa nenhuma.",
    "E preciso muito para me irritar.",
    "Prefiro passar ferias numa praia cheia a um chale isolado nas montanhas.",
    "Fico extasiado com certos tipos de musica.",
    "Por vezes, levo as pessoas a fazerem o que eu quero.",
    "Sou uma pessoa exigente e meticulosa.",
    "Tenho uma opiniao pouco favoravel de mim mesmo(a).",
    "Prefiro tratar da minha vida a ser um(a) lider para outras pessoas.",
    "Raramente me dou conta dos humores ou sentimentos que diferentes ambientes causam.",
    "A maioria das pessoas que me conhece gosta de mim.",
    "Sigo, rigorosamente, meus principios eticos.",
    "Sinto-me a vontade na presenca do meu chefe ou de outras autoridades.",
    "As pessoas acham que estou sempre com pressa.",
    "Por vezes, mudo coisas em minha casa so para experimentar a diferenca.",
    "Se alguem comeca uma briga, estou sempre pronto(a) para revidar.",
    "Esforco-me para conseguir tudo que puder.",
    "As vezes, como ate me sentir mal.",
    "Adoraria sentir as emocoes de pular de paraquedas.",
    "Tenho pouco interesse em especular sobre a natureza do universo ou da condicao humana.",
    "Sinto que nao sou melhor que os outros, seja qual for a condicao deles.",
    "Quando um projeto se torna muito dificil, minha tendencia e comecar um novo.",
    "Consigo me controlar muito bem numa situacao de crise.",
    "Sou uma pessoa alegre e bem disposta.",
    "Considero-me um individuo aberto e tolerante quanto ao estilo de vida das outras pessoas.",
    "Penso que todos os seres humanos sao dignos de respeito.",
    "Raramente tomo decisoes precipitadas.",
    "Tenho menos temores que a maioria das pessoas.",
    "Tenho fortes ligacoes afetivas com meus amigos.",
    "Quando crianca, raramente me divertia com jogos de faz-de-conta.",
    "Tendo a pensar o melhor acerca das pessoas.",
    "Sou uma pessoa muito competente.",
    "Algumas vezes senti ressentimento e amargura.",
    "Geralmente eu fico entediado(a) em encontros sociais.",
    "As vezes, ao ler poesia ou ao olhar para uma obra de arte, sinto um arrepio, uma onda de emocao.",
    "As vezes, intimido ou bajulo as pessoas para que elas facam o que eu quero.",
    "Nao tenho obsessao por limpeza.",
    "As vezes, as coisas parecem-me bastante tristes e sem esperanca.",
    "Nas conversas, tendo a falar mais do que os outros.",
    "Acho facil ser empatico(a), ou seja, sentir o que os outros sentem.",
    "Considero-me uma pessoa caridosa.",
    "Tento fazer as tarefas com todo o cuidado, para nao ter necessidade de faze-las novamente.",
    "Caso eu tenha dito ou feito algo errado a alguem, custa-me muito encara-lo outra vez.",
    "Minha vida e agitada.",
    "Quando estou em ferias, prefiro voltar a um lugar ja conhecido.",
    "Sou cabecudo(a) e teimoso(a).",
    "Esforco-me por ser excelente em tudo que faco.",
    "As vezes, faco as coisas de modo tao impulsivo que, mais tarde, me arrependo.",
    "Sinto-me atraido(a) por cores alegres e os estilos exuberantes.",
    "Tenho muita curiosidade intelectual.",
    "Prefiro muito mais elogiar os outros a ser elogiado(a).",
    "Tem tantas pequenas coisas que precisam ser feitas que, as vezes, eu simplesmente ignoro todas elas.",
    "Mesmo quando tudo parece estar dando errado, ainda consigo tomar boas decisoes.",
    "E raro eu utilizar palavras como 'fantastico' ou 'sensacional' para descrever minhas experiencias.",
    "Acho que se pessoas com 25 anos de idade nao sabem no que acreditam, alguma coisa esta errada com elas.",
    "Tenho pena de pessoas com menos sorte do que eu.",
    "Planejo as minhas viagens com antecedencia e com cuidado.",
    "As vezes, tenho pensamentos aterrorizantes.",
    "Crio facilmente vinculos sociais com as pessoas com quem trabalho.",
    "Tenho dificuldade em soltar a minha imaginacao (devanear).",
    "Tenho bastante fe na natureza humana.",
    "Sou eficiente e eficaz no meu trabalho.",
    "Mesmo os pequenos contratempos podem ser frustrantes para mim.",
    "Gosto de festas com muita gente.",
    "Gosto mais de ler poesia do que historias estruturadas (romances e contos).",
    "Orgulho-me do meu jeito de lidar com as pessoas.",
    "Gasto muito tempo a procura de coisas que coloquei fora do lugar.",
    "Muitas vezes, quando as coisas dao errado, fico desanimado(a) e tenho vontade de desistir.",
    "Nao considero facil dirigir (comandar) uma situacao.",
    "Coisas diferentes, como certos cheiros ou nomes de locais distantes, podem evocar em mim fortes emocoes.",
    "Quando posso, deixo o que estou fazendo para ajudar os outros.",
    "So faltaria ao trabalho se estivesse realmente doente.",
    "Quando pessoas que eu conheco fazem uma bobagem, fico constrangido(a) por elas.",
    "Sou uma pessoa muito ativa.",
    "Sigo sempre o mesmo caminho quando vou a qualquer lugar.",
    "Frequentemente me envolvo em discussoes com a minha familia e colegas de trabalho.",
    "Sou um pouco viciado(a) em trabalho.",
    "Consigo sempre manter os meus sentimentos sob controle.",
    "Gosto de fazer parte da multidao em acontecimentos esportivos.",
    "Tenho uma grande variedade de interesses intelectuais.",
    "Considero que sou melhor que a maioria das pessoas.",
    "Tenho muita autodisciplina.",
    "Sou bastante estavel do ponto de vista emocional.",
    "Sou propenso(a) a rir facilmente.",
    "Penso que a nova moralidade, que consiste em tudo permitir, nao e moralidade nenhuma.",
    "Prefiro ser conhecido(a) como uma pessoa 'compreensiva' (inclinada a perdoar) do que como uma pessoa 'justa' (inclinada ao rigor).",
    "Penso duas vezes antes de responder a uma pergunta.",
  ],
};

// ============ WHO-5 (Índice de Bem-Estar da OMS) ============
// Escore bruto 0-25; multiplicado por 4 = percentual 0-100. Maior = melhor bem-estar.
// Pontos de corte: ≤50% (bruto ≤12) rastreio positivo; <28% (bruto ≤6) provável depressão.
export const who5: EscalaGeralConfig = {
  id: "who5",
  sigla: "WHO-5",
  nome: "Índice de Bem-Estar (OMS)",
  instrucoes:
    "Para cada uma das cinco afirmacoes, indique como voce se sentiu nas ultimas duas semanas. Quanto maior o numero, mais presente esteve o sentimento.",
  tipo: "likert",
  opcoes: [
    { label: "O tempo todo", valor: 5 },
    { label: "A maior parte do tempo", valor: 4 },
    { label: "Mais da metade do tempo", valor: 3 },
    { label: "Menos da metade do tempo", valor: 2 },
    { label: "De vez em quando", valor: 1 },
    { label: "Em nenhum momento", valor: 0 },
  ],
  pontuacaoMaxima: 25,
  itens: [
    "Eu me senti alegre e de bom humor.",
    "Eu me senti calmo(a) e relaxado(a).",
    "Eu me senti ativo(a) e vigoroso(a).",
    "Eu acordei me sentindo descansado(a) e revigorado(a).",
    "Meu dia a dia foi preenchido com coisas que me interessam.",
  ],
};

// ============ Rosenberg / EAR (Escala de Autoestima) ============
// Hutz & Zanon (2011). 10 itens, 1-4. Itens 3,5,8,9,10 invertidos. Maior = melhor.
export const rosenberg: EscalaGeralConfig = {
  id: "rosenberg",
  sigla: "EAR",
  nome: "Escala de Autoestima de Rosenberg",
  instrucoes: "Leia cada frase e indique o quanto voce concorda ou discorda dela.",
  tipo: "likert",
  opcoes: [
    { label: "Discordo totalmente", valor: 1 },
    { label: "Discordo", valor: 2 },
    { label: "Concordo", valor: 3 },
    { label: "Concordo totalmente", valor: 4 },
  ],
  pontuacaoMaxima: 40,
  dominios: [{ id: "total", nome: "Autoestima", itens: [1,2,3,4,5,6,7,8,9,10], invertidos: [3,5,8,9,10] }],
  itens: [
    "Eu sinto que sou uma pessoa de valor, no minimo tanto quanto as outras pessoas.",
    "Eu acho que eu tenho varias boas qualidades.",
    "Levando tudo em conta, eu penso que eu sou um fracasso.",
    "Eu acho que sou capaz de fazer as coisas tao bem quanto a maioria das pessoas.",
    "Eu acho que eu nao tenho muito do que me orgulhar.",
    "Eu tenho uma atitude positiva com relacao a mim mesmo(a).",
    "No conjunto, eu estou satisfeito(a) comigo mesmo(a).",
    "Eu gostaria de poder ter mais respeito por mim mesmo(a).",
    "As vezes eu me sinto inutil.",
    "As vezes eu acho que nao presto para nada.",
  ],
};

// ============ PSS-10 (Estresse Percebido) ============
// Cohen, Kamarck & Mermelstein (1983); BR: Luft et al. (2007). 10 itens, 0-4. Itens 4,5,7,8 invertidos.
export const pss10: EscalaGeralConfig = {
  id: "pss10",
  sigla: "PSS-10",
  nome: "Escala de Estresse Percebido",
  instrucoes: "Para cada pergunta, indique com que frequencia voce se sentiu ou pensou dessa forma no ultimo mes.",
  tipo: "likert",
  opcoes: [
    { label: "Nunca", valor: 0 },
    { label: "Quase nunca", valor: 1 },
    { label: "As vezes", valor: 2 },
    { label: "Com alguma frequencia", valor: 3 },
    { label: "Muito frequentemente", valor: 4 },
  ],
  pontuacaoMaxima: 40,
  dominios: [{ id: "total", nome: "Estresse Percebido", itens: [1,2,3,4,5,6,7,8,9,10], invertidos: [4,5,7,8] }],
  itens: [
    "No ultimo mes, com que frequencia voce ficou aborrecido(a) por causa de algo que aconteceu inesperadamente?",
    "No ultimo mes, com que frequencia voce sentiu que era incapaz de controlar as coisas importantes da sua vida?",
    "No ultimo mes, com que frequencia voce esteve nervoso(a) e estressado(a)?",
    "No ultimo mes, com que frequencia voce se sentiu confiante em sua capacidade de lidar com seus problemas pessoais?",
    "No ultimo mes, com que frequencia voce sentiu que as coisas estavam indo do jeito que voce queria?",
    "No ultimo mes, com que frequencia voce percebeu que nao conseguia dar conta de tudo que tinha para fazer?",
    "No ultimo mes, com que frequencia voce conseguiu controlar as irritacoes da sua vida?",
    "No ultimo mes, com que frequencia voce sentiu que estava no comando das situacoes?",
    "No ultimo mes, com que frequencia voce ficou irritado(a) por causa de coisas que estavam fora de seu controle?",
    "No ultimo mes, com que frequencia voce sentiu que as dificuldades se acumulavam tanto que voce nao conseguia supera-las?",
  ],
};

// ============ ISI (Índice de Gravidade de Insônia) ============
// Morin (1993); BR: Bastien, Vallières & Morin (2001). 7 itens, 0-4. Maior = pior.
export const isi: EscalaGeralConfig = {
  id: "isi",
  sigla: "ISI",
  nome: "Indice de Gravidade de Insonia",
  instrucoes: "Avalie a gravidade dos seus problemas de sono nas ultimas duas semanas.",
  tipo: "likert",
  opcoes: [
    { label: "Nenhum(a)", valor: 0 },
    { label: "Leve", valor: 1 },
    { label: "Moderado(a)", valor: 2 },
    { label: "Grave", valor: 3 },
    { label: "Muito grave", valor: 4 },
  ],
  pontuacaoMaxima: 28,
  itens: [
    "Dificuldade para pegar no sono.",
    "Dificuldade para manter o sono (acordar durante a noite).",
    "Problema de despertar muito cedo.",
    "Quao satisfeito(a) ou insatisfeito(a) voce esta com seu padrao de sono atual?",
    "Em que medida voce acha que seu problema de sono interfere no seu funcionamento diario (fadiga, humor, concentracao, memoria, disposicao)?",
    "Como os outros percebem a diminuicao da sua qualidade de vida por causa do seu problema de sono?",
    "Quao preocupado(a) ou angustiado(a) voce esta com seu problema de sono atual?",
  ],
};

// ============ AUDIT (Transtornos por Uso de Álcool — OMS) ============
// Babor et al. (2001); BR: Lima et al. (2005). 10 itens, 0-40.
const auditOp3a8: BDIItem["opcoes"] = [
  { texto: "Nunca", valor: 0 },
  { texto: "Menos do que uma vez ao mes", valor: 1 },
  { texto: "Mensalmente", valor: 2 },
  { texto: "Semanalmente", valor: 3 },
  { texto: "Todos ou quase todos os dias", valor: 4 },
];
export const audit: EscalaGeralConfig = {
  id: "audit",
  sigla: "AUDIT",
  nome: "Rastreio de Uso de Alcool (OMS)",
  instrucoes: "Responda sobre seu consumo de bebidas alcoolicas nos ultimos 12 meses. Se voce nao bebe, responda 'Nunca' ou 'Nao' e pule para o proximo.",
  tipo: "likert-statements",
  pontuacaoMaxima: 40,
  itens: [
    { opcoes: [
      { texto: "Nunca consumo bebidas alcoolicas", valor: 0 },
      { texto: "Consumo mensalmente ou menos", valor: 1 },
      { texto: "Consumo de 2 a 4 vezes por mes", valor: 2 },
      { texto: "Consumo de 2 a 3 vezes por semana", valor: 3 },
      { texto: "Consumo 4 ou mais vezes por semana", valor: 4 },
    ]},
    { opcoes: [
      { texto: "1 ou 2 doses num dia tipico", valor: 0 },
      { texto: "3 ou 4 doses", valor: 1 },
      { texto: "5 ou 6 doses", valor: 2 },
      { texto: "7 a 9 doses", valor: 3 },
      { texto: "10 ou mais doses", valor: 4 },
    ]},
    { opcoes: auditOp3a8.map((o) => ({ texto: o.texto === "Nunca" ? "Nunca consumo 6 ou mais doses de uma vez" : o.texto, valor: o.valor })) },
    { opcoes: auditOp3a8.map((o) => ({ texto: o.texto === "Nunca" ? "Nunca achei que nao conseguiria parar de beber" : o.texto, valor: o.valor })) },
    { opcoes: auditOp3a8.map((o) => ({ texto: o.texto === "Nunca" ? "Nunca deixei de fazer o esperado por causa da bebida" : o.texto, valor: o.valor })) },
    { opcoes: auditOp3a8.map((o) => ({ texto: o.texto === "Nunca" ? "Nunca precisei beber pela manha para me sentir bem" : o.texto, valor: o.valor })) },
    { opcoes: auditOp3a8.map((o) => ({ texto: o.texto === "Nunca" ? "Nunca me senti culpado(a) depois de beber" : o.texto, valor: o.valor })) },
    { opcoes: auditOp3a8.map((o) => ({ texto: o.texto === "Nunca" ? "Nunca fui incapaz de lembrar o que aconteceu por ter bebido" : o.texto, valor: o.valor })) },
    { opcoes: [
      { texto: "Nao, ninguem se machucou por causa do meu consumo de alcool", valor: 0 },
      { texto: "Sim, mas nao no ultimo ano", valor: 2 },
      { texto: "Sim, no ultimo ano", valor: 4 },
    ]},
    { opcoes: [
      { texto: "Nao, ninguem se preocupou ou sugeriu que eu diminuisse", valor: 0 },
      { texto: "Sim, mas nao no ultimo ano", valor: 2 },
      { texto: "Sim, no ultimo ano", valor: 4 },
    ]},
  ] as BDIItem[],
};

// ============ SCS (Escala de Autocompaixão — Neff) ============
// Neff (2003); BR: Souza & Hutz (2016). 26 itens, 1-5. 6 subescalas.
// Autojulgamento, Isolamento e Sobre-Identificação invertidos para total.
export const scs: EscalaGeralConfig = {
  id: "scs",
  sigla: "SCS",
  nome: "Escala de Autocompaixao",
  instrucoes: "Leia cada afirmacao e indique com que frequencia voce age da maneira descrita.",
  tipo: "likert",
  opcoes: [
    { label: "Quase nunca", valor: 1 },
    { label: "Raramente", valor: 2 },
    { label: "As vezes", valor: 3 },
    { label: "Frequentemente", valor: 4 },
    { label: "Quase sempre", valor: 5 },
  ],
  pontuacaoMaxima: 130,
  invertidos: [1, 2, 4, 6, 8, 11, 13, 16, 18, 20, 21, 24, 25],
  dominios: [
    { id: "autobondade", nome: "Autobondade", itens: [5, 12, 19, 23, 26] },
    { id: "autojulgamento", nome: "Autojulgamento", itens: [1, 8, 11, 16, 21] },
    { id: "humanidade", nome: "Humanidade Comum", itens: [3, 7, 10, 15] },
    { id: "isolamento", nome: "Isolamento", itens: [4, 13, 18, 25] },
    { id: "mindfulness", nome: "Atencao Plena", itens: [9, 14, 17, 22] },
    { id: "sobreidentificacao", nome: "Sobre-Identificacao", itens: [2, 6, 20, 24] },
  ],
  itens: [
    "Eu me reprovo e faco julgamentos sobre meus erros e inadequacoes.",
    "Quando estou me sentindo para baixo, tendo a ficar obcecado(a) e fixado(a) em tudo que e errado.",
    "Quando as coisas vao mal para mim, vejo as dificuldades como parte da vida pelas quais todo mundo passa.",
    "Quando penso nas minhas inadequacoes, isso tende a me fazer sentir mais separado(a) e isolado(a) do resto do mundo.",
    "Tento ser amavel comigo mesmo(a) quando estou me sentindo emocionalmente mal.",
    "Quando eu falho em algo importante para mim, fico consumido(a) por sentimentos de inadequacao.",
    "Quando estou para baixo e triste, lembro que existem muitas outras pessoas no mundo se sentindo como eu.",
    "Quando tempos sao realmente dificeis, tendo a ser duro(a) comigo mesmo(a).",
    "Quando algo me chateia, tento manter minhas emocoes em equilibrio.",
    "Quando me sinto inadequado(a) de alguma forma, tento lembrar que sentimentos de inadequacao sao compartilhados pela maioria das pessoas.",
    "Sou intolerante e impaciente com os aspectos de minha personalidade dos quais nao gosto.",
    "Quando estou passando por um momento muito dificil, dou a mim mesmo(a) o cuidado e carinho que preciso.",
    "Quando estou para baixo, sinto que a maioria das outras pessoas e provavelmente mais feliz do que eu.",
    "Quando algo doloroso acontece, tento ter uma visao equilibrada da situacao.",
    "Tento ver meus erros como parte da condicao humana.",
    "Quando vejo aspectos de mim mesmo(a) dos quais nao gosto, fico deprimido(a).",
    "Quando eu falho em algo importante para mim, tento manter as coisas em perspectiva.",
    "Quando estou realmente passando por dificuldades, tendo a sentir que outras pessoas devem estar tendo uma vida mais facil.",
    "Sou gentil comigo mesmo(a) quando estou experienciando sofrimento.",
    "Quando algo me chateia, sou tomado(a) pelos meus sentimentos.",
    "Posso ser um pouco frio(a) e insensivel comigo mesmo(a) quando experiencio sofrimento.",
    "Quando estou me sentindo para baixo, tento abordar meus sentimentos com curiosidade e abertura.",
    "Sou tolerante com minhas proprias falhas e inadequacoes.",
    "Quando algo doloroso acontece, tendo a exagerar na importancia do evento.",
    "Quando eu falho em algo que e importante para mim, tendo a me sentir sozinho(a) na minha falha.",
    "Tento ser compreensivo(a) e paciente com os aspectos de minha personalidade dos quais nao gosto.",
  ],
};

// ============ MDQ (Questionário de Transtornos do Humor) ============
// Hirschfeld et al. (2000); BR: Castelo et al. (2010). 13 itens yes/no. Cutoff ≥ 7.
export const mdq: EscalaGeralConfig = {
  id: "mdq",
  sigla: "MDQ",
  nome: "Questionario de Transtornos do Humor",
  instrucoes: "Responda Sim ou Nao para cada pergunta. Ja houve um periodo de tempo em que voce nao era o seu eu habitual e...",
  tipo: "binary",
  pontuacaoMaxima: 13,
  opcoes: [
    { label: "Sim", valor: 1 },
    { label: "Nao", valor: 0 },
  ],
  chaveCorrecao: {
    1: "C", 2: "C", 3: "C", 4: "C", 5: "C", 6: "C", 7: "C",
    8: "C", 9: "C", 10: "C", 11: "C", 12: "C", 13: "C",
  },
  itens: [
    "Voce se sentiu tao bem ou tao para cima que outras pessoas acharam que voce nao estava no seu normal, ou estava tao para cima que arranjou problemas?",
    "Voce ficou tao irritavel que gritava com as pessoas ou comecava brigas ou discussoes?",
    "Voce se sentiu muito mais autoconfiante do que o habitual?",
    "Voce dormiu muito menos do que o habitual e descobriu que nao fazia falta?",
    "Voce ficou muito mais falante ou falou muito mais rapido do que o habitual?",
    "Os pensamentos passavam rapidamente pela sua cabeca e voce nao conseguia diminuir o ritmo deles?",
    "Voce se distraia tao facilmente com as coisas a sua volta que tinha dificuldade em se concentrar ou manter um pensamento?",
    "Voce teve muito mais energia do que o habitual?",
    "Voce ficou muito mais ativo(a) ou fez muito mais coisas do que o habitual?",
    "Voce ficou muito mais sociavel ou extrovertido(a) do que o habitual, por exemplo, telefonava para amigos no meio da noite?",
    "Voce ficou muito mais interessado(a) em sexo do que o habitual?",
    "Voce fez coisas que eram incomuns para voce ou que outras pessoas acharam que foram excessivas, tolas ou arriscadas?",
    "Gastos de dinheiro colocaram voce ou sua familia em problemas?",
  ],
};

// ============ PCL-5 (Checklist de TEPT — DSM-5) ============
// Weathers et al. (2013); BR: Lima et al. (2016). 20 itens, 0-4. 4 clusters. Cutoff ≥ 33.
export const pcl5: EscalaGeralConfig = {
  id: "pcl5",
  sigla: "PCL-5",
  nome: "Checklist de Transtorno de Estresse Pos-Traumatico",
  instrucoes: "Abaixo ha uma lista de problemas que as pessoas as vezes tem em resposta a uma experiencia muito estressante. Indique o quanto voce foi incomodado(a) por cada problema no ultimo mes.",
  tipo: "likert",
  opcoes: [
    { label: "Nada", valor: 0 },
    { label: "Um pouco", valor: 1 },
    { label: "Moderadamente", valor: 2 },
    { label: "Bastante", valor: 3 },
    { label: "Extremamente", valor: 4 },
  ],
  pontuacaoMaxima: 80,
  dominios: [
    { id: "intrusao", nome: "Intrusao (Criterio B)", itens: [1, 2, 3, 4, 5] },
    { id: "evitacao", nome: "Evitacao (Criterio C)", itens: [6, 7] },
    { id: "cognicao", nome: "Cognicao e Humor Negativos (Criterio D)", itens: [8, 9, 10, 11, 12, 13, 14] },
    { id: "hiperativacao", nome: "Hiperativacao (Criterio E)", itens: [15, 16, 17, 18, 19, 20] },
  ],
  itens: [
    "Memorias, pensamentos ou imagens repetidas e perturbadoras da experiencia estressante.",
    "Sonhos repetidos e perturbadores sobre a experiencia estressante.",
    "De repente, sentir ou agir como se a experiencia estressante estivesse acontecendo novamente (como se voce estivesse revivendo).",
    "Sentir-se muito perturbado(a) quando algo lembrou voce da experiencia estressante.",
    "Ter reacoes fisicas fortes quando algo lembrou voce da experiencia estressante (coracao disparado, dificuldade para respirar, suor).",
    "Evitar memorias, pensamentos ou sentimentos relacionados a experiencia estressante.",
    "Evitar lembretes externos da experiencia estressante (pessoas, lugares, conversas, atividades, objetos ou situacoes).",
    "Dificuldade em lembrar partes importantes da experiencia estressante.",
    "Ter crencas negativas fortes sobre si mesmo(a), outras pessoas ou o mundo (por exemplo: eu sou mau(ma), ha algo de muito errado comigo, nao se pode confiar em ninguem, o mundo e completamente perigoso).",
    "Culpar a si mesmo(a) ou outra pessoa pela experiencia estressante ou pelo que aconteceu depois dela.",
    "Ter sentimentos negativos fortes como medo, horror, raiva, culpa ou vergonha.",
    "Perda de interesse em atividades de que voce costumava gostar.",
    "Sentir-se distante ou desligado(a) de outras pessoas.",
    "Dificuldade em ter sentimentos positivos (por exemplo, ser incapaz de sentir felicidade ou ter sentimentos amorosos por pessoas proximas a voce).",
    "Comportamento irritavel, explosoes de raiva ou agir agressivamente.",
    "Correr muitos riscos ou fazer coisas que poderiam causar dano a voce.",
    "Estar superalerta, vigilante ou em guarda.",
    "Sobressaltar-se ou assustar-se facilmente.",
    "Ter dificuldade em se concentrar.",
    "Dificuldade para pegar no sono ou permanecer dormindo.",
  ],
};

// ============ OCI-R (Inventário Obsessivo-Compulsivo Revisado) ============
// Foa et al. (2002); BR: Souza et al. (2011). 18 itens, 0-4. 6 subescalas. Cutoff ≥ 21.
export const ocir: EscalaGeralConfig = {
  id: "ocir",
  sigla: "OCI-R",
  nome: "Inventario Obsessivo-Compulsivo Revisado",
  instrucoes: "As afirmacoes seguintes referem-se a experiencias que muitas pessoas tem no dia a dia. Indique o grau de sofrimento ou incomodo que cada experiencia lhe causou durante o ultimo mes.",
  tipo: "likert",
  opcoes: [
    { label: "Nenhum", valor: 0 },
    { label: "Pouco", valor: 1 },
    { label: "Moderado", valor: 2 },
    { label: "Muito", valor: 3 },
    { label: "Extremo", valor: 4 },
  ],
  pontuacaoMaxima: 72,
  dominios: [
    { id: "acumulacao", nome: "Acumulacao", itens: [1, 7, 13] },
    { id: "verificacao", nome: "Verificacao", itens: [2, 8, 14] },
    { id: "ordenacao", nome: "Ordenacao", itens: [3, 9, 15] },
    { id: "neutralizacao", nome: "Neutralizacao", itens: [4, 10, 16] },
    { id: "lavagem", nome: "Lavagem", itens: [5, 11, 17] },
    { id: "obsessao", nome: "Obsessao", itens: [6, 12, 18] },
  ],
  itens: [
    "Tenho guardado tantas coisas que elas atrapalham.",
    "Eu verifico as coisas mais do que o necessario.",
    "Fico perturbado(a) se os objetos nao estao arrumados de forma correta.",
    "Sinto necessidade de contar enquanto estou fazendo coisas.",
    "Acho dificil tocar um objeto quando sei que ele foi tocado por estranhos ou por certas pessoas.",
    "Acho dificil controlar meus proprios pensamentos.",
    "Eu junto coisas de que nao preciso.",
    "Eu verifico repetidamente portas, janelas, gavetas, etc.",
    "Fico perturbado(a) se os outros mudam a forma como arrumei as coisas.",
    "Sinto que tenho que repetir certos numeros.",
    "As vezes tenho que me lavar ou me limpar so porque me sinto contaminado(a).",
    "Fico perturbado(a) por pensamentos desagradaveis que vem a minha mente contra a minha vontade.",
    "Evito jogar coisas fora porque tenho medo de precisar delas depois.",
    "Eu verifico repetidamente torneiras de gas, agua e interruptores de luz depois de desliga-los.",
    "Preciso que as coisas estejam arrumadas em uma ordem particular.",
    "Sinto que existem numeros bons e maus.",
    "Eu lavo as maos mais do que o necessario.",
    "Frequentemente tenho pensamentos nojentos e tenho dificuldade em me livrar deles.",
  ],
};

// ============ Epworth / ESS (Escala de Sonolência de Epworth) ============
// Johns (1991); BR: Bertolazi et al. (2009). 8 itens, 0-3.
export const epworth: EscalaGeralConfig = {
  id: "epworth",
  sigla: "ESS",
  nome: "Escala de Sonolencia de Epworth",
  instrucoes: "Qual a chance de voce cochilar ou adormecer nas seguintes situacoes, em contraste com apenas se sentir cansado(a)? Considere seu modo de vida recente.",
  tipo: "likert",
  opcoes: [
    { label: "Nenhuma chance de cochilar", valor: 0 },
    { label: "Pequena chance de cochilar", valor: 1 },
    { label: "Moderada chance de cochilar", valor: 2 },
    { label: "Alta chance de cochilar", valor: 3 },
  ],
  pontuacaoMaxima: 24,
  itens: [
    "Sentado(a) e lendo.",
    "Assistindo televisao.",
    "Sentado(a), quieto(a), em um lugar publico (por exemplo, em um teatro, reuniao ou palestra).",
    "Andando de carro por uma hora sem parar, como passageiro(a).",
    "Deitado(a) para descansar a tarde, quando as circunstancias permitem.",
    "Sentado(a) conversando com alguem.",
    "Sentado(a) quieto(a) apos o almoco sem ter bebido alcool.",
    "Em um carro, parado(a) por alguns minutos no transito.",
  ],
};

// ============ DASS-21 (Escala de Depressao, Ansiedade e Estresse) ============
// Lovibond & Lovibond (1995); BR: Vignola & Tucci (2014). 21 itens, 0-3.
export const dass21: EscalaGeralConfig = {
  id: "dass21",
  sigla: "DASS-21",
  nome: "Escala de Depressao, Ansiedade e Estresse",
  instrucoes: "Leia cada afirmacao e indique o quanto ela se aplicou a voce durante a ultima semana. Nao ha respostas certas ou erradas.",
  tipo: "likert",
  pontuacaoMaxima: 63,
  opcoes: [
    { label: "Nao se aplicou de maneira alguma", valor: 0 },
    { label: "Aplicou-se em algum grau ou pouco tempo", valor: 1 },
    { label: "Aplicou-se em um grau consideravel ou boa parte do tempo", valor: 2 },
    { label: "Aplicou-se muito ou na maioria do tempo", valor: 3 },
  ],
  dominios: [
    { id: "depressao", nome: "Depressao", itens: [3, 5, 10, 13, 16, 17, 21] },
    { id: "ansiedade", nome: "Ansiedade", itens: [2, 4, 7, 9, 15, 19, 20] },
    { id: "estresse", nome: "Estresse", itens: [1, 6, 8, 11, 12, 14, 18] },
  ],
  itens: [
    "Achei dificil me acalmar",
    "Percebi que minha boca estava seca",
    "Nao consegui vivenciar nenhum sentimento positivo",
    "Tive dificuldade em respirar em alguns momentos (sem esforco fisico)",
    "Achei dificil ter iniciativa para fazer as coisas",
    "Tive a tendencia de reagir de forma exagerada",
    "Senti tremores (ex: nas maos)",
    "Senti que estava sempre nervoso(a)",
    "Preocupei-me com situacoes em que poderia entrar em panico e fazer papel de bobo(a)",
    "Senti que nao tinha nada a esperar do futuro",
    "Percebi que estava ficando agitado(a)",
    "Achei dificil relaxar",
    "Senti-me deprimido(a) e sem animo",
    "Fui intolerante com as coisas que me impediam de continuar o que estava fazendo",
    "Senti que ia entrar em panico",
    "Nao consegui me entusiasmar com nada",
    "Senti que nao tinha muito valor como pessoa",
    "Senti que estava um pouco emotivo(a) ou sensivel demais",
    "Sabia que meu coracao estava alterado mesmo sem ter feito esforco fisico (ex: aceleracao cardiaca)",
    "Senti medo sem ter uma razao obvia para isso",
    "Senti que a vida nao tinha sentido",
  ],
};

// ============ ERQ (Questionario de Regulacao Emocional) ============
// Gross & John (2003); BR: Batistoni, Ordonez & Silva (2013). 10 itens, 1-7.
export const erq: EscalaGeralConfig = {
  id: "erq",
  sigla: "ERQ",
  nome: "Questionario de Regulacao Emocional",
  instrucoes: "Gostaríamos de lhe fazer algumas perguntas sobre sua vida emocional. Estamos interessados em como voce controla (regula e gerencia) suas emocoes. Para cada item, responda usando a escala de 1 a 7.",
  tipo: "likert",
  pontuacaoMaxima: 70,
  opcoes: [
    { label: "Discordo totalmente", valor: 1 },
    { label: "Discordo", valor: 2 },
    { label: "Discordo parcialmente", valor: 3 },
    { label: "Neutro", valor: 4 },
    { label: "Concordo parcialmente", valor: 5 },
    { label: "Concordo", valor: 6 },
    { label: "Concordo totalmente", valor: 7 },
  ],
  dominios: [
    { id: "reavaliacao", nome: "Reavaliacao Cognitiva", itens: [1, 3, 5, 7, 8, 10] },
    { id: "supressao", nome: "Supressao Expressiva", itens: [2, 4, 6, 9] },
  ],
  itens: [
    "Quando quero sentir mais emocoes positivas (como alegria ou diversao), mudo o que estou pensando.",
    "Guardo minhas emocoes para mim mesmo(a).",
    "Quando quero sentir menos emocoes negativas (como tristeza ou raiva), mudo o que estou pensando.",
    "Quando estou sentindo emocoes positivas, tomo cuidado para nao expressa-las.",
    "Quando estou diante de uma situacao estressante, forco-me a pensar sobre ela de uma forma que me ajude a manter a calma.",
    "Controlo minhas emocoes nao as expressando.",
    "Quando quero sentir mais emocoes positivas, mudo a forma como penso sobre a situacao.",
    "Controlo minhas emocoes mudando a forma como penso sobre a situacao em que me encontro.",
    "Quando estou sentindo emocoes negativas, faco o possivel para nao expressa-las.",
    "Quando quero sentir menos emocoes negativas, mudo a forma como penso sobre a situacao.",
  ],
};

// ============ MAAS (Escala de Atencao e Consciencia Plena) ============
// Brown & Ryan (2003); BR: Barros et al. (2015). 15 itens, 1-6.
export const maas: EscalaGeralConfig = {
  id: "maas",
  sigla: "MAAS",
  nome: "Escala de Atencao e Consciencia Plena",
  instrucoes: "Abaixo ha uma serie de afirmacoes sobre sua experiencia cotidiana. Indique com que frequencia voce tem cada experiencia descrita, usando a escala de 1 (quase sempre) a 6 (quase nunca). Quanto maior a pontuacao, maior o nivel de atencao plena.",
  tipo: "likert",
  pontuacaoMaxima: 90,
  opcoes: [
    { label: "Quase sempre", valor: 1 },
    { label: "Com muita frequencia", valor: 2 },
    { label: "Com alguma frequencia", valor: 3 },
    { label: "Com pouca frequencia", valor: 4 },
    { label: "Raramente", valor: 5 },
    { label: "Quase nunca", valor: 6 },
  ],
  itens: [
    "Posso estar experienciando alguma emocao e nao estar consciente dela ate algum tempo depois.",
    "Quebro ou derramo coisas por descuido, por nao prestar atencao, ou por estar pensando em outra coisa.",
    "Acho dificil permanecer focado(a) no que esta acontecendo no presente.",
    "Tenho tendencia a caminhar rapido para chegar aonde quero ir sem prestar atencao ao que experiencio ao longo do caminho.",
    "Tendo a nao perceber sensacoes de tensao fisica ou desconforto ate que elas realmente chamem minha atencao.",
    "Esqueco o nome de uma pessoa quase que imediatamente apos ouvi-lo pela primeira vez.",
    "Parece que estou funcionando no piloto automatico, sem muita consciencia do que estou fazendo.",
    "Faco atividades com pressa sem estar realmente atento(a) a elas.",
    "Fico tao focado(a) na meta que quero alcancar que perco a nocao do que estou fazendo agora para chegar la.",
    "Faco trabalhos ou tarefas automaticamente, sem estar consciente do que estou fazendo.",
    "Percebo que ouco alguem falar com um ouvido enquanto faco outra coisa ao mesmo tempo.",
    "Dirijo ou me desloco no piloto automatico e depois me pergunto por que fui aquele lugar.",
    "Fico preocupado(a) com o futuro ou com o passado.",
    "Percebo que faco coisas sem prestar atencao.",
    "Faco lanches sem estar consciente de que estou comendo.",
  ],
};

// ============ SPIN (Inventario de Fobia Social) ============
// Connor et al. (2000); BR: Osorio et al. (2008). 17 itens, 0-4.
export const spin: EscalaGeralConfig = {
  id: "spin",
  sigla: "SPIN",
  nome: "Inventario de Fobia Social",
  instrucoes: "Indique o quanto as seguintes situacoes te incomodaram durante a ultima semana.",
  tipo: "likert",
  pontuacaoMaxima: 68,
  opcoes: [
    { label: "Nenhum pouco", valor: 0 },
    { label: "Um pouco", valor: 1 },
    { label: "Moderadamente", valor: 2 },
    { label: "Bastante", valor: 3 },
    { label: "Extremamente", valor: 4 },
  ],
  dominios: [
    { id: "medo", nome: "Medo", itens: [1, 3, 5, 10, 14, 15] },
    { id: "evitacao", nome: "Evitacao", itens: [4, 6, 8, 9, 11, 16] },
    { id: "fisiologico", nome: "Fisiologico", itens: [2, 7, 12, 13, 17] },
  ],
  itens: [
    "Tenho medo de pessoas em posicoes de autoridade.",
    "Fico incomodado(a) ao corar na frente das pessoas.",
    "Festas e eventos sociais me assustam.",
    "Evito falar com pessoas que nao conheco.",
    "Ser criticado(a) me assusta muito.",
    "O medo de ficar constrangido(a) me faz evitar fazer coisas ou falar com pessoas.",
    "Transpirar na frente das pessoas me causa angustia.",
    "Evito ir a festas.",
    "Evito atividades em que sou o centro das atencoes.",
    "Conversar com estranhos me assusta.",
    "Evito ter que fazer discursos.",
    "Eu faria qualquer coisa para evitar ser criticado(a).",
    "Palpitacoes cardiacas me incomodam quando estou entre pessoas.",
    "Tenho medo de fazer coisas quando as pessoas podem estar olhando.",
    "Estar constrangido(a) ou parecer estupido(a) estao entre meus piores medos.",
    "Evito falar com qualquer pessoa em posicao de autoridade.",
    "Tremer ou estremecer na frente dos outros me angustia.",
  ],
};

// ============ WHOQOL-bref (Qualidade de Vida — OMS) ============
// The WHOQOL Group (1998); BR: Fleck et al. (1999, 2000). 26 itens, dominio publico
// (uso livre para fins clinicos/pesquisa, mediante registro junto ao WHOQOL Group).
// Domain I (Fisico): 3,4,10,15,16,17,18 | Domain II (Psicologico): 5,6,7,11,19,26
// Domain III (Relacoes sociais): 20,21,22 | Domain IV (Meio ambiente): 8,9,12,13,14,23,24,25
// Facetas gerais (fora dos dominios): 1, 2. Itens invertidos: 3, 4, 26.
// REVISAO CLINICA: texto reconstruido a partir da versao brasileira publicada;
// confira a redacao exata de cada item antes do uso clinico.
const wq = (opcoes: BDIItem["opcoes"]) => opcoes;
const wqRating: BDIItem["opcoes"] = [
  { texto: "Muito ruim", valor: 1 }, { texto: "Ruim", valor: 2 }, { texto: "Nem ruim nem boa", valor: 3 },
  { texto: "Boa", valor: 4 }, { texto: "Muito boa", valor: 5 },
];
const wqSatisfacao: BDIItem["opcoes"] = [
  { texto: "Muito insatisfeito(a)", valor: 1 }, { texto: "Insatisfeito(a)", valor: 2 }, { texto: "Nem satisfeito nem insatisfeito", valor: 3 },
  { texto: "Satisfeito(a)", valor: 4 }, { texto: "Muito satisfeito(a)", valor: 5 },
];
const wqExtensao: BDIItem["opcoes"] = [
  { texto: "Nada", valor: 1 }, { texto: "Muito pouco", valor: 2 }, { texto: "Mais ou menos", valor: 3 },
  { texto: "Bastante", valor: 4 }, { texto: "Extremamente", valor: 5 },
];
const wqCapacidade: BDIItem["opcoes"] = [
  { texto: "Nada", valor: 1 }, { texto: "Muito pouco", valor: 2 }, { texto: "Medio", valor: 3 },
  { texto: "Muito", valor: 4 }, { texto: "Completamente", valor: 5 },
];
const wqFrequencia: BDIItem["opcoes"] = [
  { texto: "Nunca", valor: 1 }, { texto: "Algumas vezes", valor: 2 }, { texto: "Frequentemente", valor: 3 },
  { texto: "Muito frequentemente", valor: 4 }, { texto: "Sempre", valor: 5 },
];
export const whoqolbref: EscalaGeralConfig = {
  id: "whoqolbref",
  sigla: "WHOQOL-bref",
  nome: "Escala de Qualidade de Vida (OMS)",
  instrucoes: "Este questionario pergunta sobre como voce se sente a respeito da sua qualidade de vida, saude e outras areas da sua vida, pensando nas ultimas duas semanas.",
  tipo: "likert-statements",
  escalaMin: 1,
  escalaMax: 5,
  invertidos: [3, 4, 26],
  dominios: [
    { id: "fisico", nome: "Dominio Fisico", itens: [3, 4, 10, 15, 16, 17, 18] },
    { id: "psicologico", nome: "Dominio Psicologico", itens: [5, 6, 7, 11, 19, 26] },
    { id: "social", nome: "Relacoes Sociais", itens: [20, 21, 22] },
    { id: "ambiente", nome: "Meio Ambiente", itens: [8, 9, 12, 13, 14, 23, 24, 25] },
  ],
  itens: [
    { opcoes: wq(wqRating) }, // 1 - Como voce avaliaria sua qualidade de vida?
    { opcoes: wq(wqSatisfacao) }, // 2 - Quao satisfeito(a) voce esta com a sua saude?
    { opcoes: wq(wqExtensao) }, // 3 - Em que medida voce acha que sua dor (fisica) impede voce de fazer o que voce precisa? (invertido)
    { opcoes: wq(wqExtensao) }, // 4 - O quanto voce precisa de algum tratamento medico para levar sua vida diaria? (invertido)
    { opcoes: wq(wqExtensao) }, // 5 - O quanto voce aproveita a vida?
    { opcoes: wq(wqExtensao) }, // 6 - Em que medida voce acha que a sua vida tem sentido?
    { opcoes: wq(wqExtensao) }, // 7 - O quanto voce consegue se concentrar?
    { opcoes: wq(wqExtensao) }, // 8 - Quao seguro(a) voce se sente em sua vida diaria?
    { opcoes: wq(wqExtensao) }, // 9 - Quao saudavel e o seu ambiente fisico (clima, barulho, poluicao, atrativos)?
    { opcoes: wq(wqCapacidade) }, // 10 - Voce tem energia suficiente para seu dia a dia?
    { opcoes: wq(wqCapacidade) }, // 11 - Voce e capaz de aceitar a sua aparencia fisica?
    { opcoes: wq(wqCapacidade) }, // 12 - Voce tem dinheiro suficiente para satisfazer suas necessidades?
    { opcoes: wq(wqCapacidade) }, // 13 - Quao disponiveis para voce estao as informacoes que precisa no seu dia a dia?
    { opcoes: wq(wqCapacidade) }, // 14 - Em que medida voce tem oportunidades de atividade de lazer?
    { opcoes: wq(wqCapacidade) }, // 15 - Voce e capaz de se locomover fisicamente?
    { opcoes: wq(wqSatisfacao) }, // 16 - Quao satisfeito(a) voce esta com o seu sono?
    { opcoes: wq(wqSatisfacao) }, // 17 - Quao satisfeito(a) voce esta com sua capacidade de desempenhar as atividades do seu dia a dia?
    { opcoes: wq(wqSatisfacao) }, // 18 - Quao satisfeito(a) voce esta com sua capacidade para o trabalho?
    { opcoes: wq(wqSatisfacao) }, // 19 - Quao satisfeito(a) voce esta consigo mesmo(a)?
    { opcoes: wq(wqSatisfacao) }, // 20 - Quao satisfeito(a) voce esta com suas relacoes pessoais (amigos, parentes, conhecidos, colegas)?
    { opcoes: wq(wqSatisfacao) }, // 21 - Quao satisfeito(a) voce esta com sua vida sexual?
    { opcoes: wq(wqSatisfacao) }, // 22 - Quao satisfeito(a) voce esta com o apoio que voce recebe de seus amigos?
    { opcoes: wq(wqSatisfacao) }, // 23 - Quao satisfeito(a) voce esta com as condicoes do local onde mora?
    { opcoes: wq(wqSatisfacao) }, // 24 - Quao satisfeito(a) voce esta com o seu acesso aos servicos de saude?
    { opcoes: wq(wqSatisfacao) }, // 25 - Quao satisfeito(a) voce esta com o seu meio de transporte?
    { opcoes: wq(wqFrequencia) }, // 26 - Com que frequencia voce tem sentimentos negativos, tais como mau humor, desespero, ansiedade ou depressao? (invertido)
  ],
};

// ============ PANAS (Escala de Afetos Positivos e Negativos) ============
// Watson, Clark & Tellegen (1988); BR: Galinha & Ribeiro / Carvalho et al.
// 20 itens, escala 1-5. Dominio publico, uso livre para fins clinicos/pesquisa.
// REVISAO CLINICA: confira a traducao exata dos adjetivos de afeto.
export const panas: EscalaGeralConfig = {
  id: "panas",
  sigla: "PANAS",
  nome: "Escala de Afetos Positivos e Negativos",
  instrucoes: "Esta escala apresenta uma serie de palavras que descrevem sentimentos e emocoes. Leia cada item e indique o quanto voce tem se sentido assim nas ultimas duas semanas.",
  tipo: "likert",
  opcoes: [
    { label: "Nem um pouco", valor: 1 },
    { label: "Um pouco", valor: 2 },
    { label: "Moderadamente", valor: 3 },
    { label: "Bastante", valor: 4 },
    { label: "Extremamente", valor: 5 },
  ],
  dominios: [
    { id: "positivo", nome: "Afeto Positivo", itens: [1, 3, 5, 9, 10, 12, 14, 16, 17, 19] },
    { id: "negativo", nome: "Afeto Negativo", itens: [2, 4, 6, 7, 8, 11, 13, 15, 18, 20] },
  ],
  itens: [
    "Interessado(a)", "Angustiado(a)", "Entusiasmado(a)", "Chateado(a)", "Forte",
    "Culpado(a)", "Assustado(a)", "Hostil", "Entusiástico(a)", "Orgulhoso(a)",
    "Irritado(a)", "Alerta", "Envergonhado(a)", "Inspirado(a)", "Nervoso(a)",
    "Decidido(a)", "Atento(a)", "Inquieto(a)", "Ativo(a)", "Amedrontado(a)",
  ],
};

// ============ CBI (Copenhagen Burnout Inventory) ============
// Kristensen et al. (2005); adaptacao brasileira. 19 itens, dominio publico
// (instrumento gratuito, preferido ao MBI por nao exigir licenca comercial).
// Escore de cada subescala = media dos itens (0-100), nao soma.
// REVISAO CLINICA: confira a traducao exata dos itens e os pontos de corte.
export const cbi: EscalaGeralConfig = {
  id: "cbi",
  sigla: "CBI",
  nome: "Inventario de Burnout de Copenhague",
  instrucoes: "As perguntas a seguir se referem a como voce tem se sentido em relacao ao seu trabalho e a sua vida em geral. Responda pensando no ultimo mes.",
  tipo: "likert",
  opcoes: [
    { label: "Nunca / Quase nunca", valor: 0 },
    { label: "Raramente", valor: 25 },
    { label: "As vezes", valor: 50 },
    { label: "Frequentemente", valor: 75 },
    { label: "Sempre", valor: 100 },
  ],
  dominios: [
    { id: "pessoal", nome: "Burnout Pessoal", itens: [1, 2, 3, 4, 5, 6] },
    { id: "trabalho", nome: "Burnout Relacionado ao Trabalho", itens: [7, 8, 9, 10, 11, 12, 13], invertidos: [10] },
    { id: "cliente", nome: "Burnout Relacionado ao Cliente/Paciente", itens: [14, 15, 16, 17, 18, 19] },
  ],
  itens: [
    "Com que frequencia voce se sente cansado(a)?",
    "Com que frequencia voce se sente fisicamente exausto(a)?",
    "Com que frequencia voce se sente emocionalmente exausto(a)?",
    "Com que frequencia voce pensa: 'Eu nao aguento mais isso'?",
    "Com que frequencia voce se sente esgotado(a)?",
    "Com que frequencia voce se sente fraco(a) e suscetivel a doencas?",
    "Voce se sente exausto(a) no final do dia de trabalho?",
    "Voce se sente exausto(a) pela manha, ao pensar em mais um dia de trabalho?",
    "Voce sente que cada hora de trabalho e cansativa para voce?",
    "Voce tem energia suficiente para a familia e amigos durante o tempo livre?",
    "Seu trabalho e emocionalmente desgastante?",
    "Seu trabalho o(a) frustra?",
    "Voce se sente esgotado(a) por causa do seu trabalho?",
    "Voce acha dificil trabalhar com pacientes/clientes?",
    "Voce acha frustrante trabalhar com pacientes/clientes?",
    "Trabalhar com pacientes/clientes drena a sua energia?",
    "Voce sente que da mais do que recebe de volta ao trabalhar com pacientes/clientes?",
    "Voce esta cansado(a) de trabalhar com pacientes/clientes?",
    "Voce as vezes se pergunta por quanto tempo mais conseguira continuar trabalhando com pacientes/clientes?",
  ],
};

// ============ C-SSRS (Rastreio — Columbia Suicide Severity Rating Scale) ============
// Posner et al. (2011); versao screener de 6 perguntas, uso comunitario livre
// (Columbia Lighthouse Project). ESCALA RESTRITA — ver escalas-restritas.ts.
// O resultado NUNCA e exibido ao paciente; o CrisisCard e sempre exibido ao
// final desta escala, independente das respostas (ver pacienteEmRisco em scoring.ts).
// REVISAO CLINICA: confira a traducao oficial certificada, se disponivel.
export const cssrs: EscalaGeralConfig = {
  id: "cssrs",
  sigla: "C-SSRS",
  nome: "Rastreio de Risco de Suicidio (Columbia)",
  instrucoes: "Responda com sinceridade as perguntas abaixo, pensando no ultimo mes. Nao ha respostas certas ou erradas.",
  tipo: "likert",
  opcoes: [
    { label: "Nao", valor: 0 },
    { label: "Sim", valor: 1 },
  ],
  itens: [
    "Voce deseja estar morto(a) ou deseja poder dormir e nao acordar?",
    "Voce teve pensamentos reais de tirar a propria vida?",
    "Voce pensou em como poderia fazer isso (o metodo), sem ter um plano especifico ou intencao de leva-lo adiante?",
    "Voce teve alguma intencao de agir de acordo com esses pensamentos de se matar, e nao apenas o pensamento em si?",
    "Voce comecou a elaborar ou elaborou os detalhes de como se matar, e pretende levar esse plano adiante?",
    "Voce ja fez alguma vez uma tentativa de suicidio ou comecou a fazer algo para se preparar para tirar a propria vida (por exemplo: reunir comprimidos, arranjar uma arma, escrever um bilhete de despedida)?",
  ],
};

// ============ MERGED MAP ============
export const escalasGerais: Record<string, EscalaGeralConfig> = {
  asrs, bai, bdi, bhs, ebep, less, neoffir, neopir, who5, rosenberg, pss10, isi, audit, scs,
  mdq, pcl5, ocir, epworth, dass21, erq, maas, spin,
  whoqolbref, panas, cbi, cssrs,
};
