export interface EscalaDominio {
  id: string;
  nome: string;
  esquemas: { id: string; nome: string; itens: number[]; invertido?: boolean }[];
}

export interface EscalaConfig {
  id: string;
  sigla: string;
  nome: string;
  instrucoes: string;
  itens: string[];
  opcoes: { label: string; valor: number }[];
  dominios?: EscalaDominio[];
  scoring: "schema-avg" | "threshold";
}

const opcoes6 = [
  { label: "Completamente falso", valor: 1 },
  { label: "Em grande parte falso", valor: 2 },
  { label: "Mais verdadeiro do que falso", valor: 3 },
  { label: "Moderadamente verdadeiro", valor: 4 },
  { label: "Em grande parte verdadeiro", valor: 5 },
  { label: "Me descreve perfeitamente", valor: 6 },
];

export const ysq: EscalaConfig = {
  id: "ysq",
  sigla: "YSQ-S3",
  nome: "Questionario de Esquemas de Young",
  instrucoes:
    "Leia cada afirmacao e avalie o quanto ela descreve voce no ultimo ano. Quando voce nao tiver certeza, baseie sua resposta nos seus sentimentos, e nao no que voce acredita racionalmente que seja verdade.",
  opcoes: opcoes6,
  scoring: "schema-avg",
  dominios: [
    {
      id: "d1",
      nome: "Desconexao e Rejeicao",
      esquemas: [
        { id: "ed", nome: "Privacao Emocional", itens: [1, 19, 37, 55, 73] },
        { id: "ab", nome: "Abandono / Instabilidade", itens: [2, 20, 38, 56, 74] },
        { id: "ma", nome: "Desconfianca / Abuso", itens: [3, 21, 39, 57, 75] },
        { id: "si", nome: "Isolamento Social", itens: [4, 22, 40, 58, 76] },
        { id: "ds", nome: "Defectividade / Vergonha", itens: [5, 23, 41, 59, 77] },
      ],
    },
    {
      id: "d2",
      nome: "Autonomia e Desempenho Prejudicados",
      esquemas: [
        { id: "fa", nome: "Fracasso", itens: [6, 24, 42, 60, 78] },
        { id: "di", nome: "Dependencia / Incompetencia", itens: [7, 25, 43, 61, 79] },
        { id: "vu", nome: "Vulnerabilidade ao Perigo/Doenca", itens: [8, 26, 44, 62, 80] },
        { id: "em", nome: "Emaranhamento / Self Subdesenvolvido", itens: [9, 27, 45, 63, 81] },
      ],
    },
    {
      id: "d3",
      nome: "Limites Prejudicados",
      esquemas: [
        { id: "et", nome: "Arrogo / Grandiosidade", itens: [14, 32, 50, 68, 86] },
        { id: "is", nome: "Autocontrole / Autodisciplina Insuficientes", itens: [15, 33, 51, 69, 87] },
      ],
    },
    {
      id: "d4",
      nome: "Direcionamento para o Outro",
      esquemas: [
        { id: "sb", nome: "Subjugacao", itens: [10, 28, 46, 64, 82] },
        { id: "ss", nome: "Autossacrificio", itens: [11, 29, 47, 65, 83] },
        { id: "as", nome: "Busca de Aprovacao / Reconhecimento", itens: [16, 34, 52, 70, 88] },
      ],
    },
    {
      id: "d5",
      nome: "Supervigilancia e Inibicao",
      esquemas: [
        { id: "np", nome: "Negativismo / Pessimismo", itens: [17, 35, 53, 71, 89] },
        { id: "ei", nome: "Inibicao Emocional", itens: [12, 30, 48, 66, 84] },
        { id: "us", nome: "Padroes Inflexiveis / Postura Hipercritica", itens: [13, 31, 49, 67, 85] },
        { id: "pu", nome: "Punicao", itens: [18, 36, 54, 72, 90] },
      ],
    },
  ],
  itens: [
    "Eu nao tive ninguem para me dar afeto, cuidado e protecao, que partilhasse sua vida comigo, ou que se importasse de verdade com as coisas que me acontecem.",
    "Eu percebo que me agarro as pessoas que sao proximas de mim com medo de que elas me abandonem.",
    "Eu sinto que as pessoas vao tirar vantagem de mim.",
    "Eu nao me encaixo.",
    "Nenhum homem/mulher que eu deseje seria capaz de me amar depois de ver meus defeitos ou falhas.",
    "Quase nada do que eu faco no trabalho (ou nos estudos) e tao bom quanto o que os outros sao capazes de fazer.",
    "Eu nao me sinto capaz de me virar sem a ajuda dos outros no dia a dia.",
    "Parece que eu nao consigo parar de sentir que algo ruim esta prestes a acontecer.",
    "Eu ainda nao consegui me separar dos meus pais (ambos ou um deles) do jeito que as outras pessoas da minha idade parecem ter se separado.",
    "Eu sinto que, se eu fizer o que quero, os outros nao me apoiarao e poderao ficar bravos ou chateados comigo.",
    "Geralmente sou eu quem acaba cuidando das pessoas que sao proximas de mim.",
    "Eu sou envergonhado demais para demonstrar sentimentos positivos para os outros (por ex.: afeto; demonstrar que me importo com eles).",
    "Eu tenho que ser o melhor na maioria das coisas que eu faco; nao consigo aceitar o segundo lugar.",
    "Eu tenho muita dificuldade de aceitar um 'nao' quando quero algo dos outros.",
    "Parece que eu nao consigo me disciplinar para concluir a maioria das tarefas rotineiras ou entediantes.",
    "Ter dinheiro e conhecer pessoas importantes faz com que eu me sinta uma pessoa com valor.",
    "Mesmo quando as coisas parecem estar indo bem, eu sinto que e apenas questao de tempo para que elas comecem a dar errado.",
    "Se eu cometer algum erro, mereco ser punido.",
    "Eu nao tenho quem me de carinho, apoio e afeto.",
    "Eu preciso tanto das pessoas que fico muito preocupado com a possibilidade de perde-las.",
    "Eu sinto que nao posso baixar a guarda na presenca de outras pessoas, senao elas irao me machucar de proposito.",
    "Eu sou fundamentalmente diferente das outras pessoas.",
    "Ninguem que eu deseje iria querer ficar perto de mim se conhecesse quem eu sou de verdade.",
    "Eu sou incompetente quando se refere a realizacoes pessoais/profissionais.",
    "Eu me vejo como uma pessoa dependente dos outros no que se refere ao meu funcionamento diario.",
    "Eu sinto que uma tragedia (natural, financeira, criminal ou de saude) pode acontecer a qualquer momento.",
    "Eu e meu pai/mae temos a tendencia de nos envolver demais nos problemas e na vida uns dos outros.",
    "Eu sinto como se eu nao tivesse outra opcao a nao ser ceder aos desejos dos outros, senao eles irao ficar bravos, me rejeitar ou retaliar de alguma forma.",
    "Sou uma boa pessoa por pensar mais nos outros do que em mim.",
    "Eu acho constrangedor demonstrar o que eu sinto para as outras pessoas.",
    "Eu tento fazer o meu melhor; eu nao consigo me conformar em ser 'bom o suficiente'.",
    "Eu sou diferenciado e nao deveria ter que aceitar muitas das restricoes ou limitacoes impostas as outras pessoas.",
    "Se nao consigo atingir um objetivo, eu logo me frustro e desisto.",
    "Minhas conquistas tem mais valor para mim se forem notadas pelas outras pessoas.",
    "Se algo de bom acontece, fico preocupado e pensando que algo ruim provavelmente vai acontecer depois.",
    "Se eu nao der o meu melhor, eu tenho que me dar mal mesmo.",
    "Eu nunca me senti especial para ninguem.",
    "Eu me preocupo muito com a possibilidade de que pessoas proximas a mim me deixem ou me abandonem.",
    "E so uma questao de tempo ate alguem me trair.",
    "Eu nao faco parte; sou uma pessoa solitaria.",
    "Eu nao sou digno de receber amor, atencao e o respeito dos outros.",
    "A maioria das pessoas e mais capaz do que eu no trabalho e nas realizacoes pessoais.",
    "Me falta bom senso.",
    "Eu me preocupo muito em ser agredido fisicamente por alguem.",
    "Eu e meu pai/mae temos dificuldades de deixar de contar detalhes intimos uns para os outros sem nos sentirmos culpados.",
    "Nos relacionamentos, eu geralmente deixo que a outra pessoa tome as decisoes e esteja no controle.",
    "Eu passo tanto tempo fazendo coisas para as pessoas com quem me importo que acabo tendo pouco tempo para mim mesmo.",
    "Eu acho dificil me sentir livre e ser espontaneo perto de outras pessoas.",
    "Eu tenho que dar conta de todas as minhas responsabilidades.",
    "Eu detesto me sentir obrigado a fazer algo ou que me impecam de fazer aquilo que eu quero.",
    "Para mim, e muito dificil abrir mao de prazeres imediatos para atingir objetivos de longo prazo.",
    "Se as pessoas nao me dao muita atencao, eu me sinto menos importante.",
    "Todo cuidado e pouco, quase sempre algo vai dar errado.",
    "Se eu nao fizer minhas tarefas de forma correta, devo sofrer as consequencias.",
    "Eu nao tive ninguem que realmente me escutasse, compreendesse, ou estivesse conectado com as minhas verdadeiras necessidades e sentimentos.",
    "Quando alguem importante para mim parece estar se fechando ou se afastando, eu fico desesperado.",
    "Eu desconfio bastante das intencoes das outras pessoas.",
    "Eu me sinto isolado ou desconectado dos outros.",
    "Eu sinto que sou alguem que nao pode ser amado.",
    "Eu nao sou tao talentoso no trabalho quanto a maioria das pessoas.",
    "Nao se pode contar com meu julgamento em situacoes do dia a dia.",
    "Eu tenho medo de perder todo o meu dinheiro, de passar necessidades ou ficar muito pobre.",
    "Eu frequentemente sinto como se meus pais vivessem a minha vida ou vivessem atraves de mim - e como se eu nao tivesse uma vida propria.",
    "Eu sempre deixei as outras pessoas escolherem por mim, entao nem sei o que eu quero para mim mesmo.",
    "Eu sempre fui aquele que escuta os problemas de todo mundo.",
    "Eu me controlo tanto que muitas pessoas acham que eu nao tenho emocoes ou sou insensivel.",
    "Sinto que ha uma pressao constante para que eu conquiste e termine as coisas.",
    "Eu sinto que nao deveria ter que seguir as regras e normas que as outras pessoas tem que seguir.",
    "Eu nao consigo me forcar a fazer coisas que eu nao goste, mesmo quando sei que e para o meu proprio bem.",
    "Quando eu faco comentarios em uma reuniao, ou sou apresentado a alguem em uma situacao social, para mim e importante receber reconhecimento e admiracao.",
    "Independentemente de quanto eu trabalhe, preocupo-me com a ideia de ter problemas financeiros serios e perder quase tudo que tenho.",
    "Nao importa os motivos que me levaram a cometer um erro. Quando faco algo errado, devo sofrer as consequencias.",
    "Eu nao tenho tido uma pessoa forte ou sabia para me dar conselhos uteis ou orientacao quando nao tenho certeza do que fazer.",
    "As vezes eu me preocupo tanto que as pessoas possam me abandonar que as afasto de mim.",
    "Eu geralmente estou atento aos motivos ocultos e as segundas intencoes das outras pessoas.",
    "Eu sempre me senti deslocado ou de fora dos grupos.",
    "Sou inaceitavel demais para mostrar para as pessoas como eu sou ou deixar que elas me conhecam bem.",
    "Nao sou tao inteligente no trabalho (ou estudos) quanto a maioria das pessoas.",
    "Nao tenho confianca na minha habilidade de resolver os problemas que surgem no dia a dia.",
    "Eu me preocupo com a possibilidade de desenvolver uma doenca grave, mesmo que nada serio tenha sido diagnosticado por um medico.",
    "Eu muitas vezes sinto que nao tenho uma identidade separada da do meu pai/mae ou companheiro(a).",
    "Para mim, e muito dificil exigir que meus direitos sejam respeitados e que meus sentimentos sejam levados em consideracao.",
    "As pessoas consideram que faco demais pelos outros e nao faco o suficiente por mim mesmo.",
    "As pessoas me veem como alguem mais fechado emocionalmente.",
    "Eu nao posso 'pegar leve' comigo mesmo ou ficar arranjando desculpas pelos meus erros.",
    "Eu sinto que o que tenho a oferecer tem muito mais valor quando comparado ao que os outros tem para dar.",
    "Eu raramente consigo seguir com minhas resolucoes ou projetos pessoais/profissionais.",
    "Receber muitos elogios dos outros faz com que eu me sinta uma pessoa de valor.",
    "Eu me preocupo que uma decisao errada possa causar um desastre.",
    "Sou uma pessoa ma e que merece ser punida.",
  ],
};

export const ypi: EscalaConfig = {
  id: "ypi",
  sigla: "YPI",
  nome: "Inventario Parental de Young",
  instrucoes:
    "Leia cada afirmacao e avalie o quanto ela descreve as atitudes dos seus pais enquanto voce crescia. 1 = Completamente Falso ate 6 = Descreve Perfeitamente.",
  opcoes: opcoes6,
  scoring: "schema-avg",
  dominios: [
    {
      id: "d1",
      nome: "Desconexao e Rejeicao",
      esquemas: [
        { id: "pe", nome: "Privacao Emocional", itens: [1, 2, 3, 4, 5], invertido: true },
        { id: "ab", nome: "Abandono", itens: [6, 7, 8, 9] },
        { id: "da", nome: "Desconfianca / Abuso", itens: [10, 11, 12, 13] },
        { id: "dv", nome: "Defectividade / Vergonha", itens: [21, 22, 23, 24] },
      ],
    },
    {
      id: "d2",
      nome: "Autonomia e Desempenho Prejudicados",
      esquemas: [
        { id: "vu", nome: "Vulnerabilidade ao Dano", itens: [14, 15, 16, 17] },
        { id: "di", nome: "Dependencia / Incompetencia", itens: [18, 19, 20] },
        { id: "fr", nome: "Fracasso", itens: [25, 26, 27, 28] },
        { id: "em", nome: "Emaranhamento", itens: [52, 53, 54, 55] },
      ],
    },
    {
      id: "d3",
      nome: "Orientacao para o Outro",
      esquemas: [
        { id: "sb", nome: "Subjugacao", itens: [29, 30, 31, 32] },
        { id: "as", nome: "Auto-Sacrificio", itens: [33, 34, 35, 36] },
        { id: "bar", nome: "Busca de Aprovacao", itens: [69, 70, 71, 72] },
      ],
    },
    {
      id: "d4",
      nome: "Supervigilancia e Inibicao",
      esquemas: [
        { id: "pi", nome: "Padroes Inflexiveis", itens: [37, 38, 39, 40, 41, 42, 43] },
        { id: "np", nome: "Negativismo / Pessimismo", itens: [56, 57, 58, 59] },
        { id: "ie", nome: "Inibicao Emocional", itens: [60, 61, 62, 63, 64] },
        { id: "pu", nome: "Postura Punitiva", itens: [65, 66, 67, 68] },
      ],
    },
    {
      id: "d5",
      nome: "Limites Prejudicados",
      esquemas: [
        { id: "gr", nome: "Grandiosidade / Arrogo", itens: [44, 45, 46, 47] },
        { id: "ai", nome: "Autocontrole Insuficiente", itens: [48, 49, 50, 51] },
      ],
    },
  ],
  itens: [
    "Gostava de mim e me tratava como uma pessoa especial.",
    "Prestava atencao em mim, passando bastante tempo comigo.",
    "Costumava me dar conselhos e orientacoes uteis.",
    "Costumava me ouvir, me entender e compartilhar sentimentos comigo.",
    "Era caloroso(a) e afetuoso(a).",
    "Morreu ou abandonou a casa para sempre quando eu era crianca.",
    "Era mal humorado(a), imprevisivel ou alcoolatra.",
    "Preferia meus irmaos a mim.",
    "Isolava-se ou me deixava sozinho(a) por longos periodos de tempo.",
    "Mentia pra mim, me enganava e me traia.",
    "Abusava fisica, emocional ou sexualmente de mim.",
    "Usava-me para satisfazer suas necessidades emocionais.",
    "Parecia ter prazer em magoar os outros.",
    "Preocupava-se excessivamente com o fato de eu poder me magoar.",
    "Preocupava-se excessivamente com o fato de eu ficar fisicamente doente.",
    "Era uma pessoa medrosa ou fobica.",
    "Era superprotetor(a).",
    "Fazia-me sentir que eu nao podia confiar em minhas decisoes ou opinioes.",
    "Fazia as coisas por mim em vez de me deixar tentar faze-las sozinho(a).",
    "Tratava-me como se eu fosse mais novo(a) do que eu realmente era.",
    "Criticava-me bastante.",
    "Nao me fazia sentir amado(a) ou me fazia sentir rejeitado(a).",
    "Tratava-me como se houvesse algo de errado comigo.",
    "Fazia-me sentir vergonha de mim mesmo(a) em aspectos importantes.",
    "Nunca me ensinou a ter disciplina suficiente para ser bem sucedido(a) na escola.",
    "Tratava-me como se eu fosse estupido(a) ou nao tivesse jeito pra nada.",
    "No fundo, nao queria que eu fosse bem sucedido(a).",
    "Esperava que eu fosse um fracasso na vida.",
    "Tratava-me como se as minhas opinioes ou desejos nao contassem.",
    "Fazia o que queria, independente das minhas necessidades.",
    "Controlava tanto a minha vida que eu tinha pouca liberdade de escolha.",
    "Tudo tinha que ser como ele(a) queria.",
    "Sacrificava as suas necessidades para o bem da familia.",
    "Era incapaz de lidar com a maior parte das responsabilidades diarias, de modo que eu tinha que fazer mais do que a minha parte.",
    "Era bastante infeliz e apoiava-se em mim para conforta-lo(a) e compreende-lo(a).",
    "Fazia-me sentir que eu era forte e que devia cuidar dos outros.",
    "Tinha expectativas muito altas em relacao a si mesmo(a).",
    "Esperava que eu fizesse sempre o melhor.",
    "Era perfeccionista em muitas areas; as coisas tinham que ser do jeito dele(a).",
    "Fazia-me sentir que quase nada do que eu fazia era suficientemente bom.",
    "Tinha regras rigidas e estritas quanto ao que era certo e errado.",
    "Ficava impaciente se as coisas nao fossem feitas de forma adequada ou suficientemente rapida.",
    "Dava mais importancia a fazer as coisas bem do que a se divertir ou relaxar.",
    "Estragou-me com mimos ou era demasiado indulgente em muitos aspectos.",
    "Fazia-me sentir que eu era especial, melhor que a maioria das outras pessoas.",
    "Era exigente; esperava que as coisas ocorressem a sua maneira.",
    "Nao me ensinou que eu tinha responsabilidade para com os outros.",
    "Forneceu-me muito pouca disciplina e limites.",
    "Estabeleceu poucas regras ou responsabilidades para mim.",
    "Permitia-me ficar muito bravo(a) ou perder o controle.",
    "Era uma pessoa indisciplinada.",
    "Eramos tao proximos que compreendiam um ao outro de uma maneira quase perfeita.",
    "Eu sentia que nao tinha individualidade suficiente, nao me sentindo separado dele(a).",
    "Enquanto crescia, eu sentia que nao tinha meu proprio senso de direcao de tanto que estava ligado(a) a ele(a).",
    "Eu sentia que nos magoariamos um(a) ao outro(a) se nos afastassemos.",
    "Preocupava-se muito com os problemas financeiros da familia.",
    "Fazia-me sentir que se eu cometesse um erro, mesmo que pequeno, algo de mal poderia acontecer.",
    "Tinha uma perspectiva pessimista; frequentemente esperava pelo pior.",
    "Seu foco era nos aspectos negativos da vida ou nas coisas que estavam indo mal.",
    "Tinha que ter tudo sob controle.",
    "Sentia-se desconfortavel ao demonstrar afeto ou vulnerabilidade.",
    "Era estruturado(a) e organizado(a); preferia o que era habitual a mudanca.",
    "Raramente expressava raiva.",
    "Era reservado(a); raramente discutia seus sentimentos.",
    "Ficava bravo(a) ou criticava bastante se eu fizesse algo de errado.",
    "Eu era castigado(a) se eu fizesse algo de errado.",
    "Costumava me xingar (por exemplo, de 'estupido' ou 'idiota') se eu cometesse algum erro.",
    "Culpava as pessoas quando as coisas iam mal.",
    "Preocupava-se com as aparencias e com o status social.",
    "Dava muita importancia ao sucesso e a competicao.",
    "Preocupava-se com o que os outros pensariam dele(a) por causa do meu comportamento.",
    "Parecia me dar mais atencao quando eu me sobressaia.",
  ],
};

export const yci: EscalaConfig = {
  id: "yci",
  sigla: "YCI",
  nome: "Inventario de Compensacao de Young",
  instrucoes:
    "Leia cada afirmacao e decida o quao bem elas descrevem voce. Responda guiado por como voce sente e age, nao pelo que acha 'correto'.",
  opcoes: opcoes6,
  scoring: "threshold",
  itens: [
    "Eu desconto as minhas frustracoes nos outros.",
    "Muitas vezes eu culpo os outros quando as coisas dao errado.",
    "Eu demonstro muita raiva quando as pessoas me decepcionam ou me traem.",
    "Eu nao consigo parar de sentir raiva ate me vingar.",
    "Quando eu sou criticado, fico na defensiva.",
    "E importante que os outros admirem minhas realizacoes ou conquistas.",
    "Para mim, e importante demonstrar o meu sucesso (p. ex., com carros caros, roupas, casa).",
    "Eu me esforco muito para ficar entre os melhores ou mais bem-sucedidos.",
    "Eu considero importante ser popular (p. ex., fazer parte de um grupo seleto).",
    "Eu frequentemente tenho fantasias de sucesso, fama, riqueza, poder ou popularidade.",
    "Eu gosto de ser o centro das atencoes.",
    "Eu flerto mais ou sou mais sedutor do que as pessoas em geral.",
    "Eu dou muita importancia a ordem na minha vida (p. ex., organizacao, estrutura, planejamento, rotina).",
    "Eu gasto muita energia tentando evitar que as coisas deem errado.",
    "Eu penso muito antes de tomar decisoes para que eu nao cometa um erro.",
    "Eu sou bastante controlador em relacao as pessoas a minha volta.",
    "Eu gosto de estar em posicoes nas quais eu tenha controle ou autoridade sobre as pessoas ao meu redor.",
    "Eu nao gosto que as pessoas deem palpites sobre a minha vida.",
    "Para mim, e muito dificil ceder ou chegar num consenso.",
    "Eu nao gosto de ser dependente de ninguem.",
    "Eu considero essencial que eu tome as minhas proprias decisoes e seja independente.",
    "Eu tenho dificuldade de me comprometer com uma pessoa ou me manter em uma relacao estavel.",
    "Eu gosto de ser uma pessoa livre, de ter liberdade para fazer o que eu quiser.",
    "Eu tenho dificuldade de me limitar a um emprego ou carreira; eu gosto de ter liberdade de escolha.",
    "Eu geralmente coloco as minhas proprias necessidades na frente das dos outros.",
    "Muitas vezes eu sou exigente com as outras pessoas - eu gosto que tudo seja 'exatamente como tem que ser'.",
    "Eu preciso cuidar de mim primeiro, assim como fazem as outras pessoas.",
    "Para mim, e muito importante que o meu ambiente seja confortavel (p. ex., temperatura, luz, moveis).",
    "Eu me considero uma pessoa rebelde; eu frequentemente vou contra a autoridade estabelecida.",
    "Eu nao gosto de regras e sinto satisfacao quando as desrespeito.",
    "Eu gosto de nao ser convencional, mesmo que isso me faca ser pouco popular ou que eu nao me encaixe por isso.",
    "Eu nao procuro sucesso seguindo os padroes da sociedade (ex., riqueza, realizacoes, popularidade).",
    "Eu sempre fui diferente; nunca fui atras da maioria.",
    "Eu sou uma pessoa muito reservada; nao gosto que as pessoas saibam muito a respeito da minha vida particular ou dos meus sentimentos.",
    "Eu tento sempre parecer forte para as outras pessoas, mesmo que me sinta vulneravel ou inseguro.",
    "As vezes eu sou muito possessivo e fico muito grudado com as pessoas que eu valorizo.",
    "Eu frequentemente manipulo os outros para atingir meus objetivos.",
    "Em vez de pedir o que eu quero diretamente, muitas vezes prefiro conseguir as coisas por meios indiretos.",
    "Eu mantenho as pessoas a distancia para que elas so vejam as partes de mim que eu quero que elas vejam.",
    "Eu sou uma pessoa extremamente critica.",
    "Eu sinto que me pressiono demais para satisfazer os meus proprios padroes e responsabilidades.",
    "Muitas vezes eu nao tenho tato ou sou insensivel ao me expressar.",
    "Eu tento ser otimista o tempo todo; nao me permito dar atencao aos aspectos negativos.",
    "Eu acho que e importante parecer feliz, independentemente de como eu me sinta por dentro.",
    "Varias vezes eu sinto inveja ou fico frustrado quando os outros sao mais bem-sucedidos ou recebem mais atencao do que eu.",
    "Eu irei ate aonde for necessario para me certificar de que eu ganhe o que e meu por direito e que eu nao seja enganado ou traido.",
    "Eu busco maneiras de ser mais esperto do que os outros para que eles nao tirem vantagem de mim ou me magoem.",
    "Eu sei exatamente o que dizer ou fazer para que os outros gostem de mim (p. ex., elogiar, dizer aquilo que eles querem ouvir).",
  ],
};

export const escalas: Record<string, EscalaConfig> = { ysq, ypi, yci };