export interface Exercicio {
  id: string;
  titulo: string;
  categoria: string;
  abordagem: string;
  publico: "adulto" | "infantojuvenil";
  objetivo: string;
  instrucoes: string[];
  exemplo?: string;
  referencia: string;
  tempoEstimado: string;
}

export const exercicios: Exercicio[] = [
  {
    id: "registro-pensamentos",
    titulo: "Registro de Pensamentos Disfuncionais",
    categoria: "Reestruturação Cognitiva",
    abordagem: "Terapia Cognitivo-Comportamental",
    publico: "adulto",
    objetivo: "Identificar e questionar pensamentos automáticos negativos, promovendo respostas alternativas mais adaptativas.",
    instrucoes: [
      "Identifique a situação: descreva brevemente o que estava acontecendo quando você começou a se sentir mal.",
      "Registre a emoção: nomeie o que sentiu (tristeza, ansiedade, raiva, etc.) e avalie a intensidade de 0 a 100.",
      "Identifique o pensamento automático: qual pensamento passou pela sua cabeça naquele momento? Escreva exatamente como pensou.",
      "Busque evidências a favor: liste fatos concretos que apoiam esse pensamento.",
      "Busque evidências contra: liste fatos concretos que contradizem ou relativizam esse pensamento.",
      "Formule um pensamento alternativo: considerando as evidências, escreva uma forma mais equilibrada de pensar sobre a situação.",
      "Reavalie a emoção: após o exercício, avalie novamente a intensidade da emoção de 0 a 100.",
    ],
    exemplo: "Situação: chefe não respondeu meu e-mail. Emoção: ansiedade (80/100). Pensamento: 'Ele está insatisfeito com meu trabalho.' Evidências a favor: ele costuma responder rápido. Evidências contra: ele está em reuniões o dia todo; na última avaliação, recebi feedback positivo. Pensamento alternativo: 'Ele provavelmente está ocupado, não há evidência de insatisfação.' Emoção reavaliada: ansiedade (30/100).",
    referencia: "Beck, J. S. (2021). Terapia Cognitivo-Comportamental: Teoria e Prática (3ª ed.). Artmed.",
    tempoEstimado: "15-20 min",
  },
  {
    id: "ativacao-comportamental",
    titulo: "Planejamento de Ativação Comportamental",
    categoria: "Ativação Comportamental",
    abordagem: "Terapia Cognitivo-Comportamental",
    publico: "adulto",
    objetivo: "Reverter o ciclo de inatividade e evitação presente na depressão, aumentando gradualmente atividades prazerosas e de domínio.",
    instrucoes: [
      "Monitore suas atividades: durante 3 dias, registre tudo que fez hora a hora, anotando o nível de prazer (P: 0-10) e domínio/realização (D: 0-10).",
      "Identifique padrões: observe quais atividades trouxeram mais prazer e sensação de realização, e quais momentos foram de maior inatividade.",
      "Planeje atividades: para a próxima semana, agende pelo menos 1 atividade prazerosa e 1 atividade de domínio por dia, mesmo que pareçam pequenas.",
      "Comece pequeno: se sair de casa parece difícil, comece com 5 minutos de caminhada. O objetivo é quebrar a inércia, não a performance.",
      "Registre o resultado: após cada atividade planejada, anote como se sentiu antes (previsão) e depois (resultado real). Compare.",
      "Ajuste semanalmente: aumente gradualmente a complexidade e duração das atividades conforme se sentir mais confiante.",
    ],
    exemplo: "Segunda: caminhada 15 min (P:6 D:7) — previsão era P:3, resultado real foi melhor que o esperado. Terça: cozinhar uma receita nova (P:7 D:8). Quarta: ligar para um amigo (P:8 D:5).",
    referencia: "Martell, C. R., Dimidjian, S., & Herman-Dunn, R. (2013). Ativação Comportamental para Depressão. Artmed.",
    tempoEstimado: "10 min/dia",
  },
  {
    id: "flash-cards-esquema",
    titulo: "Flash Cards de Esquemas",
    categoria: "Esquemas Iniciais Desadaptativos",
    abordagem: "Terapia do Esquema",
    publico: "adulto",
    objetivo: "Criar cartões de enfrentamento que ajudem a reconhecer e responder ao esquema no momento em que ele é ativado.",
    instrucoes: [
      "Identifique o esquema ativado: nomeie o esquema (ex: Abandono, Defectividade, Fracasso) que está gerando sofrimento neste momento.",
      "Lado 1 — A voz do esquema: escreva o que o esquema diz. Ex: 'Ninguém vai ficar comigo. Eu sempre serei abandonado.'",
      "Lado 2 — A resposta saudável: escreva a resposta do 'adulto saudável'. Ex: 'Esse é meu esquema de Abandono falando. Tenho pessoas que se importam comigo. Relações têm altos e baixos, mas isso não significa abandono.'",
      "Inclua evidências concretas: no lado saudável, liste 2-3 fatos reais que contradizem o esquema.",
      "Carregue o cartão consigo: quando sentir o esquema ativando, leia o lado saudável em voz alta ou mentalmente.",
      "Revise periodicamente: atualize os cartões conforme avança na terapia e novas evidências surgem.",
    ],
    exemplo: "Esquema: Defectividade. Voz do esquema: 'Eu sou defeituoso, se me conhecerem de verdade vão me rejeitar.' Resposta saudável: 'Esse é meu esquema de Defectividade. Meus amigos próximos me conhecem bem e continuam presentes. Meu terapeuta disse que esse sentimento vem da infância, não da realidade atual.'",
    referencia: "Young, J. E., Klosko, J. S., & Weishaar, M. E. (2008). Terapia do Esquema: Guia de Técnicas Cognitivo-Comportamentais Inovadoras. Artmed.",
    tempoEstimado: "15 min",
  },
  {
    id: "respiracao-diafragmatica",
    titulo: "Respiração Diafragmática (4-7-8)",
    categoria: "Regulação Fisiológica",
    abordagem: "Técnica Transdiagnóstica",
    publico: "adulto",
    objetivo: "Ativar o sistema nervoso parassimpático para reduzir a resposta de ansiedade e promover relaxamento.",
    instrucoes: [
      "Sente-se confortavelmente ou deite-se. Coloque uma mão no peito e outra no abdômen.",
      "Inspire pelo nariz contando até 4, direcionando o ar para o abdômen (a mão no abdômen deve subir, a do peito deve ficar parada).",
      "Segure a respiração contando até 7.",
      "Expire lentamente pela boca contando até 8, esvaziando completamente os pulmões.",
      "Repita o ciclo 4 vezes. Com a prática, aumente para 8 ciclos.",
      "Pratique 2 vezes ao dia (manhã e noite) e sempre que sentir ansiedade aumentando.",
      "Dica: se contar até 7 ou 8 for difícil no início, use proporções menores (2-3-4) e vá aumentando.",
    ],
    referencia: "Weil, A. (2015). Breathing: The Master Key to Self Healing. Sounds True. / Leahy, R. L. (2015). Livre de Ansiedade. Artmed.",
    tempoEstimado: "5 min",
  },
  {
    id: "dessensibilizacao-exposicao",
    titulo: "Hierarquia de Exposição Gradual",
    categoria: "Exposição",
    abordagem: "Terapia Cognitivo-Comportamental",
    publico: "adulto",
    objetivo: "Enfrentar gradualmente situações temidas para reduzir a ansiedade por meio da habituação e aprendizagem corretiva.",
    instrucoes: [
      "Liste as situações que você evita por medo ou ansiedade (ex: falar em público, pegar elevador, ir a festas).",
      "Classifique cada situação de 0 a 100 conforme o nível de ansiedade que provoca (SUDS — Escala Subjetiva de Desconforto).",
      "Ordene da menos ansiogênica (ex: 20) à mais ansiogênica (ex: 95). Esta é sua hierarquia.",
      "Comece pela situação mais fácil. Exponha-se a ela repetidamente até que a ansiedade reduza pela metade.",
      "Registre: antes da exposição (ansiedade prevista), durante (ansiedade máxima real), e depois (ansiedade final).",
      "Quando uma etapa ficar confortável (SUDS < 25), passe para a próxima da hierarquia.",
      "Importante: NÃO use comportamentos de segurança (ex: levar remédio 'por via das dúvidas'). A exposição funciona quando você experimenta a ansiedade e percebe que ela diminui sozinha.",
    ],
    exemplo: "Hierarquia para medo social: (20) cumprimentar vizinho, (35) pedir informação a desconhecido, (50) almoçar com colega, (70) fazer pergunta em reunião, (90) apresentar projeto para equipe.",
    referencia: "Abramowitz, J. S., Deacon, B. J., & Whiteside, S. P. H. (2019). Exposure Therapy for Anxiety (2nd ed.). Guilford Press.",
    tempoEstimado: "Variável (sessões)",
  },
  {
    id: "diario-emocional-esquemas",
    titulo: "Diário de Esquemas Emocionais",
    categoria: "Regulação Emocional",
    abordagem: "Terapia Cognitivo-Comportamental / Esquemas Emocionais",
    publico: "adulto",
    objetivo: "Identificar crenças sobre as próprias emoções que dificultam o processamento emocional saudável.",
    instrucoes: [
      "Quando sentir uma emoção intensa, registre: qual emoção, intensidade (0-100), e situação que a disparou.",
      "Identifique sua crença sobre essa emoção. Ex: 'Não deveria sentir raiva', 'Se chorar, vou perder o controle', 'Essa tristeza nunca vai passar'.",
      "Classifique o tipo de crença: é sobre duração? Controle? Vergonha? Ser único nisso?",
      "Questione: 'Essa crença é um fato ou uma interpretação? O que aconteceu das últimas vezes que senti isso?'",
      "Pratique a validação: escreva 'Faz sentido sentir isso porque...' — conecte a emoção à situação sem julgá-la.",
      "Observe o resultado: a emoção diminuiu? Se manteve? Conseguiu tolerá-la melhor?",
    ],
    referencia: "Leahy, R. L. (2015). Livre de Ansiedade. Artmed. / Leahy, R. L. (2019). Regulação Emocional em Psicoterapia. Artmed.",
    tempoEstimado: "10-15 min",
  },
  {
    id: "resolucao-problemas",
    titulo: "Técnica de Resolução de Problemas",
    categoria: "Habilidades de Enfrentamento",
    abordagem: "Terapia Cognitivo-Comportamental",
    publico: "adulto",
    objetivo: "Desenvolver uma abordagem estruturada para lidar com problemas concretos que geram sofrimento emocional.",
    instrucoes: [
      "Defina o problema: escreva de forma clara e específica. Ex: em vez de 'minha vida está um caos', escreva 'estou atrasado em 3 contas e não sei como priorizar'.",
      "Gere soluções: faça brainstorming de TODAS as soluções possíveis, sem julgar nenhuma. Quantidade importa mais que qualidade neste passo.",
      "Avalie cada solução: para cada uma, liste prós e contras considerando: efetividade, viabilidade, consequências a curto e longo prazo.",
      "Escolha a melhor solução (ou combinação de soluções).",
      "Planeje a implementação: divida em passos concretos com prazos específicos.",
      "Execute e avalie: após implementar, avalie o resultado. Se não funcionou, volte ao passo 2 — não desista, ajuste.",
    ],
    referencia: "Nezu, A. M., Nezu, C. M., & D'Zurilla, T. J. (2013). Problem-Solving Therapy. Springer.",
    tempoEstimado: "20-30 min",
  },
  {
    id: "reparentalização-limitada",
    titulo: "Exercício de Reparentalização por Imagens",
    categoria: "Trabalho com Modos",
    abordagem: "Terapia do Esquema",
    publico: "adulto",
    objetivo: "Acessar memórias da infância ligadas ao esquema e oferecer ao 'eu-criança' o que não foi recebido, fortalecendo o modo Adulto Saudável.",
    instrucoes: [
      "Feche os olhos e traga à mente uma lembrança da infância em que se sentiu sozinho(a), assustado(a) ou invalidado(a).",
      "Observe a cena: onde está? Quantos anos tem? O que está acontecendo? O que sente?",
      "Agora, imagine seu 'eu-adulto' entrando na cena. Aproxime-se da criança.",
      "Diga à criança o que ela precisava ouvir naquele momento. Ex: 'Você não tem culpa', 'Eu estou aqui com você', 'Você merece ser amado'.",
      "Se possível, imagine abraçando ou confortando a criança. Permita-se sentir a emoção.",
      "Traga a criança para um lugar seguro na imagem. Diga que ela pode contar com você sempre.",
      "Abra os olhos lentamente. Registre como se sentiu antes e depois do exercício.",
    ],
    referencia: "Young, J. E., Klosko, J. S., & Weishaar, M. E. (2008). Terapia do Esquema. Artmed. / Arntz, A., & Jacob, G. (2013). Schema Therapy in Practice. Wiley.",
    tempoEstimado: "20-30 min",
  },

  // ========== INFANTOJUVENIL — Caderno de Autoestima ==========

  {
    id: "escala-autoestima-kids",
    titulo: "Termometro da Autoestima",
    categoria: "Autoestima",
    abordagem: "Psicologia Positiva / TCC Infantil",
    publico: "infantojuvenil",
    objetivo: "Ajudar a crianca ou adolescente a perceber como anda a relacao consigo mesmo(a), identificando pontos fortes e areas que podem melhorar — tudo de um jeito leve e sem julgamento!",
    instrucoes: [
      "Leia cada frase abaixo e pense: 'De 0 a 10, o quanto eu acredito nisso?' (0 = nada, 10 = totalmente!)",
      "As frases sao: (1) Eu fico feliz por ser eu mesmo, (2) Nao tenho medo de errar, (3) Foco nas coisas legais que faco, (4) Conheco minhas qualidades, (5) Me amo mesmo quando alguem nao gosta de mim, (6) Gosto do meu jeito, (7) Me respeito, (8) Adoro tentar coisas novas, (9) Sou bom em resolver problemas, (10) Sei lidar com criticas, (11) Me sinto bem com elogios, (12) Tenho orgulho do que ja conquistei, (13) Prefiro ser eu do que qualquer outra pessoa, (14) Sou tao importante quanto qualquer um, (15) Acredito em mim!",
      "Some todos os pontos. Quanto maior o total, mais forte esta sua autoestima!",
      "Escolha uma frase que voce deu nota baixa. O que precisaria mudar pra subir so 1 pontinho? Escreva isso — pequenos passos fazem grande diferenca!",
    ],
    exemplo: "Maria, 12 anos, deu nota 4 em 'Sei lidar com criticas'. Ela escreveu: 'Pra subir pra 5, vou tentar lembrar que criticas nao significam que sou ruim — as vezes a pessoa so quer ajudar.' Na semana seguinte, subiu pra 6!",
    referencia: "Caderno de Atividades de Autoestima para Criancas e Adolescentes.",
    tempoEstimado: "10-15 min",
  },
  {
    id: "checkin-diario-autoestima",
    titulo: "Diario dos Momentos Legais",
    categoria: "Autoestima",
    abordagem: "Psicologia Positiva / TCC Infantil",
    publico: "infantojuvenil",
    objetivo: "Treinar o cerebro pra prestar atencao nas coisas boas do dia, fortalecendo a autoestima um pouquinho a cada dia — como um musculo que fica mais forte com exercicio!",
    instrucoes: [
      "Escolha um caderno ou folha que sera seu 'Diario dos Momentos Legais'.",
      "Todo dia antes de dormir, responda 3 perguntas rapidas:",
      "DOMINGO: 'Hoje me diverti quando...', 'Fiz um bom trabalho em...', 'Uma coisa positiva que vi foi...'",
      "SEGUNDA: 'Algo positivo que experimentei...', 'Fiquei orgulhoso(a) de mim quando...', 'Ajudei alguem fazendo...'",
      "TERCA: 'Algo interessante que aconteceu...', 'Algo que conquistei hoje...', 'Sou grato(a) por...'",
      "QUARTA: 'A melhor coisa de hoje...', 'Fiquei orgulhoso(a) de alguem quando...', 'Algo que aprendi...'",
      "QUINTA: 'Minha coisa favorita hoje...', 'Fiquei orgulhoso(a) de mim quando...', 'Amanha estou ansioso(a) pra...'",
      "SEXTA: 'Sou grato(a) por...', 'Algo interessante que aconteceu...', 'Algo que conquistei...'",
      "SABADO: 'Me diverti quando...', 'Ajudei alguem fazendo...', 'Um elogio que daria a mim mesmo(a) hoje e...'",
      "Depois de uma semana, releia tudo. Voce vai se surpreender com quantas coisas legais aconteceram!",
    ],
    referencia: "Caderno de Atividades de Autoestima para Criancas e Adolescentes.",
    tempoEstimado: "5 min/dia",
  },
  {
    id: "minhas-conquistas",
    titulo: "Mural das Conquistas",
    categoria: "Autoestima",
    abordagem: "Psicologia Positiva / TCC Infantil",
    publico: "infantojuvenil",
    objetivo: "Olhar pra tras e perceber tudo de incrivel que voce ja fez! Muitas vezes a gente esquece das proprias vitorias — este exercicio ajuda a lembrar.",
    instrucoes: [
      "Escolha um periodo (ultimo mes, 6 meses, ou 1 ano).",
      "Responda cada pergunta escrevendo ou desenhando:",
      "3 coisas dificeis que eu fiz sao...",
      "Uma pessoa que eu ajudei foi... e eu ajudei fazendo...",
      "3 coisas que eu aprendi sao...",
      "2 coisas pelas quais sou grato(a)...",
      "Um desafio que eu superei foi...",
      "Pequenas conquistas do dia a dia que eu nao valorizo tanto sao...",
      "3 coisas em que eu melhorei...",
      "A coisa que eu fiz e mais me orgulho e...",
      "Agora escolha 2 metas que quer alcancar nos proximos meses. Escreva passos pequenos pra chegar la!",
      "BONUS: Desenhe sua maior conquista! Pode ser colorido, pode ser enorme — e sua!",
    ],
    referencia: "Caderno de Atividades de Autoestima para Criancas e Adolescentes.",
    tempoEstimado: "15-20 min",
  },
  {
    id: "quem-sou-eu",
    titulo: "Quem Sou Eu? — Meu Mapa Interior",
    categoria: "Autoconhecimento",
    abordagem: "Psicologia Positiva / TCC Infantil",
    publico: "infantojuvenil",
    objetivo: "Explorar quem voce e de verdade — seus sonhos, medos, o que te move e o que te faz unico(a). Quanto mais voce se conhece, mais forte fica!",
    instrucoes: [
      "Complete cada frase com a primeira coisa que vier na sua cabeca — nao precisa pensar muito, so sinta!",
      "Eu sou alguem que... AMA ___",
      "Eu sou alguem que... QUER ___",
      "Eu sou alguem que... TEM COMO OBJETIVO ___",
      "Eu sou alguem que... ANTES TINHA MEDO DE ___",
      "Eu sou alguem que... E MOVIDO(A) POR ___",
      "Eu sou alguem que... E INSPIRADO(A) POR ___",
      "Eu sou alguem que... E MAIS FELIZ QUANDO ___",
      "Eu sou alguem que... FICA DECEPCIONADO(A) COM ___",
      "Eu sou alguem que... GOSTARIA DE PODER ___",
      "Eu sou alguem que... ACREDITA EM ___",
      "Eu sou alguem que... UM DIA VAI ___",
      "Quando terminar, leia tudo de volta. Essas sao partes maravilhosas de quem voce e!",
    ],
    exemplo: "Lucas, 10 anos: 'Eu sou alguem que AMA jogar bola com meus amigos, que QUER aprender a tocar guitarra, que ANTES TINHA MEDO DE falar na frente da turma mas agora ja consigo!'",
    referencia: "Caderno de Atividades de Autoestima para Criancas e Adolescentes.",
    tempoEstimado: "10-15 min",
  },
  {
    id: "eu-sou-alguem-que",
    titulo: "Eu Sou Alguem Que... (Versao Desafio!)",
    categoria: "Autoconhecimento",
    abordagem: "Psicologia Positiva / TCC Infantil",
    publico: "infantojuvenil",
    objetivo: "Conhecer a si mesmo(a) de um jeito divertido, completando frases que revelam coisas sobre voce — ate as que voce nunca tinha parado pra pensar!",
    instrucoes: [
      "Complete cada frase rapidamente, sem pensar demais:",
      "EU SOU ALGUEM QUE AMA ___",
      "EU SOU ALGUEM QUE ODEIA ___",
      "EU SOU ALGUEM QUE NAO CONSEGUE ___",
      "EU SOU ALGUEM QUE CONSEGUE ___",
      "EU SOU ALGUEM QUE NUNCA VAI ___",
      "EU SOU ALGUEM QUE MAL PODE ESPERAR PARA ___",
      "EU SOU ALGUEM QUE PREFERE ___",
      "EU SOU ALGUEM QUE DESEJA ___",
      "EU SOU ALGUEM QUE TENTOU ___",
      "EU SOU ALGUEM QUE NAO SABE COMO ___",
      "EU SOU ALGUEM QUE NUNCA ESQUECE DE ___",
      "EU SOU ALGUEM QUE E GRATO(A) POR ___",
      "EU SOU ALGUEM QUE SIMPLESMENTE NAO TEM O BASTANTE DE ___",
      "EU SOU ___!",
      "Releia suas respostas. Tem alguma surpresa? Compartilhe com seu psicologo as que chamaram sua atencao!",
    ],
    referencia: "Caderno de Atividades de Autoestima para Criancas e Adolescentes.",
    tempoEstimado: "10 min",
  },
  {
    id: "lista-de-sonhos",
    titulo: "Minha Lista de Sonhos Sem Limites",
    categoria: "Autoestima",
    abordagem: "Psicologia Positiva / TCC Infantil",
    publico: "infantojuvenil",
    objetivo: "Deixar a imaginacao voar livre! Sonhar sem barreiras ajuda a criar esperanca, motivacao e a sensacao de que voce pode ser e fazer coisas incriveis.",
    instrucoes: [
      "Imagine que nao existe nenhum limite — voce tem todo o tempo, todo o dinheiro, toda a coragem do mundo!",
      "Escreva ate 20 sonhos. Podem ser grandes ou pequenos, serios ou malucos. Tudo vale!",
      "Pense em: conquistas, amigos, familia, viagens, coisas que quer aprender, lugares que quer conhecer, quem quer se tornar...",
      "Quando terminar, feche os olhos e imagine cada sonho se realizando. Sinta a alegria, o orgulho, a emocao!",
      "Imagine como as pessoas que voce ama ficariam felizes por voce.",
      "BONUS: Desenhe 2 ou 3 dos seus sonhos mais especiais. Pode ser um desenho enorme, colorido e cheio de detalhes!",
      "Cole sua lista num lugar que voce veja todo dia. Sonhos lembrados tem mais chance de virar realidade!",
    ],
    exemplo: "Sofia, 11 anos, escreveu: '1. Ter um cachorro golden, 2. Viajar pro Japao, 3. Aprender a surfar, 4. Ser veterinaria, 5. Cozinhar um bolo perfeito, 6. Fazer um amigo em outro pais...'",
    referencia: "Caderno de Atividades de Autoestima para Criancas e Adolescentes.",
    tempoEstimado: "15-20 min",
  },
  {
    id: "afirmacoes-enfrentamento-kids",
    titulo: "Frases-Escudo: Minha Armadura Invisivel",
    categoria: "Autoestima",
    abordagem: "TCC Infantil / Psicologia Positiva",
    publico: "infantojuvenil",
    objetivo: "Criar frases poderosas que funcionam como um escudo protetor nos momentos dificeis — quando a confianca cai, voce saca seu escudo e se lembra de quem voce realmente e!",
    instrucoes: [
      "Leia estas frases-escudo. Quando voce se sentir pra baixo, escolha uma e repita pra si mesmo(a):",
      "'Eu sou corajoso(a). Mesmo com medo, eu ajo!'",
      "'Quando as coisas ficam dificeis, eu nao desisto — eu continuo tentando!'",
      "'Eu posso me tratar com carinho, como trataria meu melhor amigo.'",
      "'Eu nao me comparo com ninguem. Eu sou minha propria pessoa!'",
      "'Errar e normal. Nao preciso ser perfeito(a). Sou humano(a)!'",
      "'Estou crescendo e mudando pra melhor, um pouquinho de cada vez.'",
      "'Eu conheco minhas qualidades e tenho orgulho delas!'",
      "'Sou grato(a) pelos desafios — eles me deixam mais forte.'",
      "'Eu me perdoo e perdoo os outros.'",
      "'Posso aceitar ajuda — isso nao me faz fraco(a), me faz esperto(a)!'",
      "Agora crie 3 frases-escudo SUAS! Frases que so voce sabe que funcionam. Escreva-as num cartao e carregue na mochila ou cole no espelho!",
    ],
    referencia: "Caderno de Atividades de Autoestima para Criancas e Adolescentes.",
    tempoEstimado: "10-15 min",
  },
  {
    id: "minhas-forcas-kids",
    titulo: "Caca ao Tesouro das Minhas Forcas",
    categoria: "Autoconhecimento",
    abordagem: "Psicologia Positiva / Forcas de Carater",
    publico: "infantojuvenil",
    objetivo: "Descobrir quais sao seus superpoderes do dia a dia! Todo mundo tem forcas — as vezes a gente so precisa parar pra notar.",
    instrucoes: [
      "Olhe a lista abaixo e circule (ou escreva) TODAS as forcas que voce tem. Seja honesto(a) — voce tem mais do que imagina!",
      "Forcas possiveis: Honesto, Gentil, Atencioso, Confiavel, Grato, Carinhoso, Resiliente, Humilde, Responsavel, Flexivel, Corajoso, Otimista, Leal, Criativo, Paciente, Perdoador, Independente, Empatico, Determinado, Persistente, Cooperativo, Aventureiro, Engracado, Lider, Confiante, Atletico, Inteligente, Curioso, Artistico, Util, Focado, Amoroso, Bom amigo, Talentoso, Capaz, Trabalhador, Compreensivo, Compassivo.",
      "Agora escolha suas 3 PRINCIPAIS forcas. Escreva: 'Eu sou ___!'",
      "Pra cada uma, escreva um exemplo real de quando voce usou essa forca.",
      "Escolha 2 forcas que voce quer DESENVOLVER. Quais passos pode dar pra isso?",
      "BONUS: Pergunte a alguem proximo (pai, mae, amigo, professor) quais forcas ele/ela ve em voce. Vai se surpreender!",
    ],
    exemplo: "Pedro, 13 anos: 'Minhas 3 forcas sao: Engracado (faco meus amigos rirem todo dia), Leal (nunca conto segredo dos meus amigos), Curioso (adoro aprender coisas novas no YouTube).' Forca pra desenvolver: Focado — passo: desligar o celular na hora do estudo.",
    referencia: "Caderno de Atividades de Autoestima para Criancas e Adolescentes.",
    tempoEstimado: "15 min",
  },
  {
    id: "super-heroi",
    titulo: "Se Eu Fosse um Super-Heroi!",
    categoria: "Autoconhecimento",
    abordagem: "TCC Infantil / Ludoterapia",
    publico: "infantojuvenil",
    objetivo: "Explorar qualidades pessoais de forma criativa e divertida, ajudando a crianca/adolescente a reconhecer suas habilidades como 'superpoderes' do mundo real.",
    instrucoes: [
      "Invente seu nome de super-heroi! (pode ser engraçado, epico, misterioso...)",
      "Desenhe como voce ficaria de super-heroi — capa, mascara, roupa, tudo!",
      "Escolha seu(s) superpoder(es) entre estes ou invente o seu: Ficar invisivel, Voar, Ler mentes, Ver atraves das paredes, Mover objetos com a mente, Viajar no tempo, Curar pessoas, Controlar o clima, Superforça, Supervelocidade, Controle da agua, Outro: ___",
      "Escreva sua MISSAO PRINCIPAL: 'Minha missao e ajudar as pessoas atraves de...'",
      "Use estas palavras pra descrever sua missao: poderoso(a), gentil, rapido(a), generoso(a), corajoso(a), inteligente, heroico(a), amigavel, paciente, forte, justo(a).",
      "Agora pense: quais desses 'superpoderes' voce JA TEM no mundo real? Ser gentil e um superpoder! Ser corajoso(a) e um superpoder! Fazer as pessoas rirem e um superpoder!",
      "Escreva: 'Meu superpoder real e ___ porque ___.'",
    ],
    exemplo: "Ana, 9 anos: 'Meu nome de super-heroi e Super Ana Relampago! Meu poder e supervelocidade e cura. Minha missao e ajudar as pessoas sendo rapida e gentil. Meu superpoder real e fazer meus amigos se sentirem melhor quando estao tristes.'",
    referencia: "Caderno de Atividades de Autoestima para Criancas e Adolescentes.",
    tempoEstimado: "15-20 min",
  },
  {
    id: "zona-de-conforto-kids",
    titulo: "Aventura Fora da Zona de Conforto",
    categoria: "Autoconfianca",
    abordagem: "TCC Infantil / Exposicao Gradual",
    publico: "infantojuvenil",
    objetivo: "Entender que sair da zona de conforto e como um musculo — quanto mais voce treina, mais forte fica sua confianca! E tudo bem sentir um friozinho na barriga.",
    instrucoes: [
      "Desenhe dois circulos: um menor dentro de um maior, como um alvo!",
      "No CIRCULO INTERNO (zona de conforto), escreva coisas que voce faz com facilidade e se sente seguro(a) fazendo.",
      "No CIRCULO EXTERNO (zona de aventura), escreva coisas que voce gostaria de tentar mas da um pouquinho de medo ou vergonha.",
      "Ideias pra zona de aventura: entrar num clube ou atividade nova, testar um hobby, provar comidas diferentes, conversar com alguem que nao conhece, elogiar alguem, fazer trabalho voluntario, falar na aula, ficar um dia sem celular, ouvir um estilo de musica diferente...",
      "Escolha UMA coisa da zona de aventura que voce vai tentar esta semana. So uma!",
      "Depois que fizer, responda: 'Como me senti? O que aconteceu? Foi tao ruim quanto eu pensava?'",
      "Spoiler: quase sempre a gente descobre que nao era tao assustador assim!",
    ],
    exemplo: "Gustavo, 14 anos: zona de conforto = jogar videogame, ficar com os amigos de sempre. Zona de aventura = falar na aula, elogiar um colega. Ele escolheu 'elogiar um colega'. Resultado: 'O cara ficou super feliz e a gente comecou a conversar mais. Nao foi dificil!'",
    referencia: "Caderno de Atividades de Autoestima para Criancas e Adolescentes.",
    tempoEstimado: "15 min",
  },
  {
    id: "perdoando-a-mim-mesmo",
    titulo: "A Arte de Se Perdoar",
    categoria: "Autocompaixao",
    abordagem: "TCC Infantil / Autocompaixao",
    publico: "infantojuvenil",
    objetivo: "Aprender que todo mundo erra e que se perdoar nao e fraqueza — e inteligencia emocional! Guardar culpa so pesa, e voce merece andar leve.",
    instrucoes: [
      "Pense em algo que voce fez e se sente culpado(a) ou chateado(a). Escreva: 'Hoje eu me perdoo por...'",
      "Agora escreva: 'Eu mereco perdao porque...'",
      "Escreva: 'Da proxima vez que eu estiver numa situacao parecida, eu vou...'",
      "Escolha uma ou mais 'frases de perdao' pra repetir quando a culpa aparecer:",
      "'Eu aceito que sou humano(a) e cometo erros.'",
      "'Eu me perdoo por nao saber antes o que sei agora.'",
      "'Vou me tratar com carinho e compaixao.'",
      "'Na epoca, eu fiz o melhor que podia com o que sabia.'",
      "'Ficar preso(a) no passado nao ajuda. Vou focar no presente e usar o que aprendi.'",
      "Escreva sua frase favorita num papel e cole num lugar especial. Ela vai te lembrar de ser gentil consigo mesmo(a)!",
    ],
    referencia: "Caderno de Atividades de Autoestima para Criancas e Adolescentes.",
    tempoEstimado: "10-15 min",
  },
  {
    id: "diario-autoestima-kids",
    titulo: "Meu Diario de Coisas Incriveis",
    categoria: "Autoestima",
    abordagem: "Psicologia Positiva / TCC Infantil",
    publico: "infantojuvenil",
    objetivo: "Criar um registro pessoal de tudo que faz voce ser incrivel — um lugar pra voltar sempre que precisar de um lembrete de como voce e demais!",
    instrucoes: [
      "Pegue uma folha ou caderno e responda cada item com calma:",
      "3 coisas que eu GOSTO em mim:",
      "3 coisas em que eu sou BOM (BOA):",
      "Algo do qual eu tenho ORGULHO:",
      "Algo em que eu trabalhei DURO pra conseguir:",
      "Eu me sinto calmo(a) e em paz quando...",
      "3 coisas pelas quais sou GRATO(A):",
      "Objetivos que estou trabalhando pra alcancar:",
      "Coisas que me fazem UNICO(A):",
      "Elogios que eu ja recebi (e que sao verdade!):",
      "Desafios que eu ja SUPEREI:",
      "Eu me sinto mais CONFIANTE quando...",
      "Pessoas que me AMAM:",
      "Releia tudo. Esse e voce. E voce e incrivel!",
    ],
    referencia: "Caderno de Atividades de Autoestima para Criancas e Adolescentes.",
    tempoEstimado: "15-20 min",
  },
  {
    id: "autoestima-acompanhamento",
    titulo: "Meu Grafico de Autoestima — 7 Dias",
    categoria: "Autoestima",
    abordagem: "TCC Infantil / Monitoramento",
    publico: "infantojuvenil",
    objetivo: "Acompanhar como sua autoestima muda ao longo da semana. Assim como o humor, a autoestima sobe e desce — e tudo bem! O importante e aprender o que te faz bem.",
    instrucoes: [
      "Todo dia, de uma nota de 0 a 10 pra como voce se sente consigo mesmo(a).",
      "Pra cada dia, escreva tambem: 'Coisas que me fizeram me sentir bem hoje foram...'",
      "No final de 7 dias, olhe o grafico:",
      "Em quais dias a nota foi mais alta? O que aconteceu nesses dias?",
      "Em quais dias a nota foi mais baixa? O que aconteceu?",
      "Consegue identificar um padrao? (Ex: dias que faco exercicio fico melhor, dias que brigo com alguem fico pior...)",
      "Escreva 3 coisas que voce pode fazer DE PROPOSITO pra manter sua autoestima alta.",
      "Repita na proxima semana e compare! Voce vai perceber que tem mais poder sobre como se sente do que imagina.",
    ],
    referencia: "Caderno de Atividades de Autoestima para Criancas e Adolescentes.",
    tempoEstimado: "3 min/dia + 10 min revisao",
  },
  {
    id: "eu-sou-qualidades",
    titulo: "Eu Sou! — Descubra Suas Qualidades",
    categoria: "Autoconhecimento",
    abordagem: "Psicologia Positiva / TCC Infantil",
    publico: "infantojuvenil",
    objetivo: "Identificar qualidades positivas sobre si mesmo(a) e encontrar provas reais de que voce as possui. Nao e se gabar — e reconhecer a verdade!",
    instrucoes: [
      "Pense em 5 qualidades positivas suas. Pode ser: corajoso(a), cuidadoso(a), inteligente, engraçado(a), criativo(a), leal, gentil, forte, determinado(a)...",
      "Pra CADA qualidade, escreva: 'EU SOU ___!'",
      "Logo embaixo, escreva: 'Eu sei disso porque...' — conte um exemplo real, uma situacao em que voce mostrou essa qualidade.",
      "Exemplo: 'EU SOU CORAJOSO! Eu sei disso porque falei na frente da turma toda mesmo com medo.'",
      "Depois de escrever as 5, leia em voz alta. Parece estranho? Normal! Mas quanto mais voce fala coisas boas sobre si, mais acredita nelas.",
      "Peca pra alguem que voce confia adicionar mais uma qualidade que ele/ela ve em voce.",
    ],
    referencia: "Caderno de Atividades de Autoestima para Criancas e Adolescentes.",
    tempoEstimado: "10-15 min",
  },
  {
    id: "espelho-triplo-autoestima",
    titulo: "O Espelho Triplo — Como Eu Me Vejo?",
    categoria: "Autoestima / Autopercepção",
    abordagem: "TCC Infantil / Reestruturação Cognitiva",
    publico: "infantojuvenil",
    objetivo: "Explorar como voce se enxerga, como os outros te enxergam e como voce gostaria de ser — tres espelhos que, juntos, revelam crencas importantes sobre voce mesmo(a).",
    instrucoes: [
      "ESPELHO 1 — COMO EU ME VEJO: Divida uma folha ao meio. De um lado, escreva 'Minhas Qualidades' e do outro 'Meus Defeitos'. Preencha os dois lados com honestidade.",
      "Agora responda: Qual e sua MELHOR qualidade? Por que voce acha isso?",
      "E qual e seu PIOR defeito? Sera que e tao ruim assim? Alguem ja te disse isso ou voce mesmo(a) decidiu?",
      "ESPELHO 2 — COMO OS OUTROS ME VEEM: Imagine que alguem proximo (amigo, familiar, professor) esta te descrevendo. O que essa pessoa diria? Escreva as qualidades e defeitos que ELA apontaria.",
      "Compare os dois espelhos: sao parecidos ou muito diferentes? O que isso te diz?",
      "ESPELHO 3 — COMO EU GOSTARIA DE SER: Se voce pudesse escolher, como seria a versao ideal de voce? Escreva ou desenhe essa versao.",
      "Agora olhe de novo: voce ja tem alguma dessas qualidades da versao ideal? (Aposto que sim!)",
      "BONUS — COISAS QUE ME DEIXAM ORGULHOSO(A): Escreva pelo menos 5 coisas que voce faz e que te dao orgulho. Podem ser grandes ou pequenas!",
      "Compartilhe com seu psicologo: qual espelho foi mais facil? Qual foi mais dificil? Isso diz muito sobre como anda sua autoestima!",
    ],
    exemplo: "Joao, 15 anos: Espelho 1 — Qualidades: leal, engracado, bom em matematica. Defeitos: timido, impaciente. Espelho 2 — Amigo diria: 'Joao e o cara mais confiavel que existe, mas precisa se soltar mais.' Espelho 3 — 'Queria ser mais corajoso pra falar com pessoas novas.' Descoberta: Joao percebeu que ja e corajoso de outras formas (enfrenta provas dificeis sem reclamar) e pode usar essa coragem em situacoes sociais tambem!",
    referencia: "Adaptado de CriAtivar Recursos Terapeuticos — Debora Barboza Rodrigues Martins, Psicologa e Neuropsicologa (CRP 06/131118).",
    tempoEstimado: "15-20 min",
  },

  // ========== TERAPIA DO ESQUEMA — Manual de Técnicas (Schütz, 2023) ==========

  {
    id: "te-gatilhos-abandono",
    titulo: "Mapeamento de Gatilhos — Abandono/Instabilidade",
    categoria: "Esquema: Abandono",
    abordagem: "Terapia do Esquema",
    publico: "adulto",
    objetivo: "Identificar situações, gatilhos e estratégias de enfrentamento ligadas ao esquema de abandono/instabilidade, diferenciando estratégias válidas das que perpetuam o esquema.",
    instrucoes: [
      "Liste situações recentes em que você sentiu seu esquema de abandono ativado (ex: parceiro demorou pra responder, amigo cancelou plano).",
      "Para cada situação, identifique os gatilhos presentes: o que exatamente disparou a sensação? (Ex: silêncio, distância física, mudança de plano.)",
      "Escreva: 'Quando isso acontece, eu costumo...' — liste suas reações habituais.",
      "Agora avalie cada reação: ela é uma estratégia válida OU é uma estratégia que também alimenta o esquema? (Ex: ligar 10 vezes → busca reasseguramento excessivo.)",
      "Para as estratégias inválidas, pergunte: 'Por que essa estratégia também me prejudica?'",
      "Substitua por uma estratégia exclusivamente válida. (Ex: em vez de ligar 10 vezes, combinar um horário de check-in com a pessoa.)",
      "Liste seus direitos e necessidades emocionais legítimos em relacionamentos. O que você precisa e merece receber?",
    ],
    referencia: "Schütz, N. T. (2023). Manual de Técnicas em Terapia do Esquema. Sinopsys Editora. Anexos 1-4.",
    tempoEstimado: "20-30 min",
  },
  {
    id: "te-desconfianca-reformulacao",
    titulo: "Reformulação de Histórias — Desconfiança/Abuso",
    categoria: "Esquema: Desconfiança/Abuso",
    abordagem: "Terapia do Esquema",
    publico: "adulto",
    objetivo: "Revisitar experiências de violação de direitos e reformulá-las a partir de uma posição de força, além de acumular evidências de relações positivas.",
    instrucoes: [
      "Liste situações em que seus direitos foram violados. Quem foi responsável? Por quê?",
      "Escreva: 'O que isso representou na minha vida foi...'",
      "Agora REFORMULE cada história: reescreva o acontecimento se colocando como FORTE. Como você teria reagido sabendo o que sabe hoje?",
      "Parte 2 — Acumulando relações positivas: liste situações em que alguém fez algo genuinamente bom por você.",
      "Para cada uma: 'Como eu me senti?' e 'Como posso vivenciar isso mais vezes?'",
      "Reflexão final: as experiências ruins foram causadas por pessoas específicas em contextos específicos — não por todas as pessoas. Quais relações atuais contradizem o esquema?",
    ],
    referencia: "Schütz, N. T. (2023). Manual de Técnicas em Terapia do Esquema. Sinopsys Editora. Anexos 5-7.",
    tempoEstimado: "25-30 min",
  },
  {
    id: "te-privacao-emocional",
    titulo: "Automonitoramento de Privação Emocional",
    categoria: "Esquema: Privação Emocional",
    abordagem: "Terapia do Esquema",
    publico: "adulto",
    objetivo: "Clarificar suas necessidades emocionais e monitorar momentos em que o esquema de privação emocional é ativado, conectando com memórias de origem.",
    instrucoes: [
      "Escreva dentro de uma silhueta (ou liste): o que você acredita ser importante receber emocionalmente — de si e dos outros?",
      "Liste situações recentes em que se sentiu emocionalmente privado(a).",
      "Para cada uma, identifique: (a) gatilhos que ativaram o esquema, (b) sensações emocionais observadas, (c) sensações físicas observadas.",
      "Conecte com o passado: existe alguma memória infantil ligada a essa situação?",
      "Identifique seu modo de funcionamento nesses momentos (evitar? hipercompensar? resignar?).",
      "Agora descreva a vida que você QUER e MERECE: o que precisa emocionalmente? Onde está hoje em relação a isso? O que pode fazer para se aproximar?",
    ],
    referencia: "Schütz, N. T. (2023). Manual de Técnicas em Terapia do Esquema. Sinopsys Editora. Anexos 8-10.",
    tempoEstimado: "20-25 min",
  },
  {
    id: "te-defectividade-vergonha",
    titulo: "Enfrentando a Defectividade/Vergonha",
    categoria: "Esquema: Defectividade",
    abordagem: "Terapia do Esquema",
    publico: "adulto",
    objetivo: "Identificar tentativas de hipercompensação do esquema de defectividade, construir reações alternativas aos erros e aprender a aceitar amor.",
    instrucoes: [
      "Liste exemplos de quando você se sente defectivo(a) ou com vergonha.",
      "Para cada um: como você tenta hipercompensar esse sentimento? (Ex: perfeccionismo, evitação, agradar excessivamente.)",
      "Avalie os resultados: quais são as vantagens E desvantagens dessa hipercompensação?",
      "Registro de erros: liste erros recentes. Para cada um, escreva: pensamento que teve, emoção que sentiu, e como poderia ter lidado de forma MENOS CRÍTICA.",
      "Aceitando amor: o que significa receber amor para você? De que formas as pessoas tentam te oferecer amor? Como você pode ser mais receptivo(a)?",
      "Fontes da rejeição: em aspectos físicos, mentais e sociais — de onde vem a sensação de rejeição? Como você lidou? Qual seria uma forma mais assertiva?",
    ],
    referencia: "Schütz, N. T. (2023). Manual de Técnicas em Terapia do Esquema. Sinopsys Editora. Anexos 11-14.",
    tempoEstimado: "25-30 min",
  },
  {
    id: "te-isolamento-social",
    titulo: "Reconectando — Isolamento Social",
    categoria: "Esquema: Isolamento Social",
    abordagem: "Terapia do Esquema",
    publico: "adulto",
    objetivo: "Questionar previsões negativas sobre conviver com pessoas, reconhecer experiências sociais positivas e planejar passos concretos de mudança.",
    instrucoes: [
      "Identifique sua previsão negativa sobre conviver com pessoas. Escreva exatamente o que você espera que aconteça.",
      "Responda: como você se sente ao prever as coisas assim? Essas previsões realmente te protegem?",
      "Quantas vezes você fez previsões negativas que NÃO se concretizaram?",
      "O que você PERDE quando deixa de tentar por já imaginar o pior?",
      "Como seria sua vida se você se permitisse tentar mais?",
      "Liste situações sociais que foram BOM para você. Que lições elas mostram?",
      "Planeje passos concretos: cite ações que você pode dar para interagir mais socialmente. Comece pela mais fácil.",
    ],
    referencia: "Schütz, N. T. (2023). Manual de Técnicas em Terapia do Esquema. Sinopsys Editora. Anexos 15-17.",
    tempoEstimado: "20 min",
  },
  {
    id: "te-dependencia-incompetencia",
    titulo: "Ciclo da Dependência/Incompetência",
    categoria: "Esquema: Dependência",
    abordagem: "Terapia do Esquema",
    publico: "adulto",
    objetivo: "Rastrear a origem do esquema de dependência, separar o que é do outro do que é seu, e quebrar o ciclo ansiedade → dependência.",
    instrucoes: [
      "Quem cuidava de você na infância? Qual era o estilo dessas pessoas? (superprotetores? controladores? negligentes?)",
      "Por que essas pessoas lidavam com você dessa forma? O que isso diz sobre ELAS (e não sobre você)?",
      "Separe: o que era delas × o que era realmente seu. Faça o mesmo para hoje.",
      "Mapeie o ciclo: situação ansiogênica → pensamentos → como lida com a ansiedade → a quem recorre → resultado → como isso alimenta o esquema.",
      "Fortalecendo autoeficácia: liste situações em que se descreve de forma depreciativa. Reescreva cada uma considerando que você TERÁ eficácia.",
      "Lições dos erros: liste seus erros, os fatores envolvidos, o que aprendeu com cada um, e uma visão mais assertiva deles agora.",
    ],
    referencia: "Schütz, N. T. (2023). Manual de Técnicas em Terapia do Esquema. Sinopsys Editora. Anexos 18-20, 29-30.",
    tempoEstimado: "25-30 min",
  },
  {
    id: "te-vulnerabilidade-medos",
    titulo: "Enfrentando Medos e Vulnerabilidades",
    categoria: "Esquema: Vulnerabilidade ao Dano",
    abordagem: "Terapia do Esquema",
    publico: "adulto",
    objetivo: "Mapear vulnerabilidades percebidas, comparar medos da infância com os atuais, e desenvolver pensamentos e comportamentos de enfrentamento.",
    instrucoes: [
      "No que você se sente vulnerável? Preencha para cada área: saúde/doenças, perigos, pobreza, perder o controle. Como se sente? Por quê?",
      "Liste medos da infância com nível de ansiedade (0-10). Depois liste medos atuais com nível de ansiedade.",
      "Compare: o que é semelhante? O que mudou? Por quê?",
      "Para seus medos atuais: 'Quase nada do que penso é 100% verdade.' Escreva seus pensamentos de preocupação e reescreva convencendo-se de que são apenas pensamentos, não verdades absolutas.",
      "Avalie a intensidade da preocupação (0-100%). O que mudou depois de reescrever?",
      "Planeje o enfrentamento: pensamento de enfrentamento + comportamentos a aplicar + resultados esperados.",
    ],
    referencia: "Schütz, N. T. (2023). Manual de Técnicas em Terapia do Esquema. Sinopsys Editora. Anexos 21-25.",
    tempoEstimado: "25 min",
  },
  {
    id: "te-subjugacao",
    titulo: "Reconhecendo Minha Subjugação",
    categoria: "Esquema: Subjugação",
    abordagem: "Terapia do Esquema",
    publico: "adulto",
    objetivo: "Identificar origens e gatilhos do esquema de subjugação, reconhecer necessidades e emoções próprias, e praticar autoexpressão.",
    instrucoes: [
      "Liste situações em que foi coagido(a) a ser submisso(a). Motivos, pessoas envolvidas, e suas considerações sobre esses acontecimentos.",
      "Mapeie gatilhos por área: família, relacionamento, parentalidade, amizades, trabalho. Quais gatilhos ativam o esquema de subjugação em cada área?",
      "Crie dois planos: (1) como evitar gatilhos quando possível, (2) como lidar com eles quando inevitáveis.",
      "Liste suas necessidades e emoções. Quais benefícios existem em reconhecê-las como importantes?",
      "Autoexpressão: quais pessoas te invalidavam? O que você precisa expressar? Escreva como se fosse dizer a elas — mesmo que nunca envie.",
      "Como você se sente agora depois deste exercício?",
    ],
    referencia: "Schütz, N. T. (2023). Manual de Técnicas em Terapia do Esquema. Sinopsys Editora. Anexos 38-40, 50.",
    tempoEstimado: "20-25 min",
  },
  {
    id: "te-autossacrificio",
    titulo: "Balança do Autossacrifício",
    categoria: "Esquema: Autossacrifício",
    abordagem: "Terapia do Esquema",
    publico: "adulto",
    objetivo: "Avaliar vantagens e desvantagens de sempre colocar os outros em primeiro lugar, e verificar se a troca em seus relacionamentos está equilibrada.",
    instrucoes: [
      "Liste 3 situações recentes em que você ajudou alguém. Para cada uma, escreva as VANTAGENS e DESVANTAGENS de ter ajudado.",
      "Agora faça a balança geral: de um lado, 'O que eu ofereço'. Do outro, 'O que eu recebo'. As coisas estão justas?",
      "Se a balança está desigual: o que você pode fazer para equilibrá-la sem deixar de ser uma pessoa generosa?",
      "Construa uma rotina mais saudável: liste atividades diárias que aumentam SUA satisfação pessoal.",
      "Identifique obstáculos no cumprimento dessas atividades e estratégias para lidar com cada um.",
      "Reflexão: você consegue ser generoso(a) E cuidar de si ao mesmo tempo? O que precisa mudar?",
    ],
    referencia: "Schütz, N. T. (2023). Manual de Técnicas em Terapia do Esquema. Sinopsys Editora. Anexos 41-42, 31.",
    tempoEstimado: "20 min",
  },
  {
    id: "te-padroes-inflexiveis",
    titulo: "Flexibilizando Padrões e Regras Internas",
    categoria: "Esquema: Padrões Inflexíveis",
    abordagem: "Terapia do Esquema",
    publico: "adulto",
    objetivo: "Questionar regras rígidas internalizadas, conectar-se com valores autênticos e desenvolver flexibilidade psicológica.",
    instrucoes: [
      "Liste suas regras sobre como as coisas 'deveriam' ser. Quem te ensinou cada uma?",
      "Para cada regra: o quanto é baseada na realidade? O quanto pode ter sido distorcida antes de chegar a você?",
      "Avalie custos × benefícios de seguir cada regra. Por que você ainda a segue?",
      "Conecte-se com seus valores: liste valores por área (relações, parentalidade, amizades, carreira, lazer, saúde, espiritualidade).",
      "Para cada área: quais desvios você comete quando o esquema de padrões inflexíveis está ativado?",
      "Flexibilidade psicológica: o que é uma vida significativa para você? O quanto sua vida atual é significativa? O que precisa enfrentar para mudar?",
      "Otimize energia: separe em duas colunas: 'Tenho controle' e 'Não tenho controle'. Foque apenas no primeiro.",
    ],
    referencia: "Schütz, N. T. (2023). Manual de Técnicas em Terapia do Esquema. Sinopsys Editora. Anexos 53-56, 54-55.",
    tempoEstimado: "25-30 min",
  },
  {
    id: "te-postura-punitiva",
    titulo: "Da Punição à Compreensão",
    categoria: "Esquema: Postura Punitiva",
    abordagem: "Terapia do Esquema",
    publico: "adulto",
    objetivo: "Transformar a postura punitiva em compreensão, liberando-se da culpa e dos rótulos autocríticos.",
    instrucoes: [
      "Liste situações em que usou sua postura punitiva (contra si ou outros).",
      "Para cada uma: quais fatores/pessoas estavam envolvidos? Quem foram os responsáveis e quanto cada um foi responsável (%)? Foi intencional?",
      "Pensamentos automáticos diante do erro: escreva-os. Depois liste variáveis envolvidas sobre as quais você NÃO tinha controle.",
      "Construa uma visão mais equilibrada do erro.",
      "Rótulos: liste rótulos que coloca em si e nos outros. Reescreva cada um descrevendo apenas o COMPORTAMENTO que ocorreu (não a pessoa).",
      "Treinando gentileza: liste formas de ser gentil com os outros, frases gentis que pode usar, e ganhos que terá sendo mais gentil.",
    ],
    referencia: "Schütz, N. T. (2023). Manual de Técnicas em Terapia do Esquema. Sinopsys Editora. Anexos 57-60, 34.",
    tempoEstimado: "20-25 min",
  },
  {
    id: "te-autocontrole-impulsividade",
    titulo: "Análise para Escolhas Mais Saudáveis",
    categoria: "Esquema: Autocontrole Insuficiente",
    abordagem: "Terapia do Esquema",
    publico: "adulto",
    objetivo: "Avaliar prós e contras da impulsividade e desenvolver um processo de tomada de decisão mais consciente antes de agir.",
    instrucoes: [
      "Prós e contras de agir por impulso: liste ambos. Em escala 0-10, qual o impacto de cada na sua vida?",
      "Identifique: como foi privado(a) de frustrações na infância? Quem evitou essas frustrações? Como isso te prejudica hoje?",
      "Quando se sentir empolgado(a) ou frustrado(a), antes de agir responda: (a) Pensamentos que passam na minha mente agora, (b) Esses pensamentos são verdadeiros?, (c) O quanto fazer isso pode me ajudar?, (d) Quais consequências terei?, (e) Como vou me sentir depois de algum tempo?",
      "Como outras pessoas que você admira avaliariam o que está pensando em fazer?",
      "Existem outras formas de pensar sobre isso?",
      "Cartão de enfrentamento emocional: 'Estou consciente de que emoções são ___, elas me ajudam a ___, então quando uma emoção estiver ativada, eu posso ___.'",
    ],
    referencia: "Schütz, N. T. (2023). Manual de Técnicas em Terapia do Esquema. Sinopsys Editora. Anexos 35-37, 52.",
    tempoEstimado: "20-25 min",
  },
  {
    id: "te-aprovacao-reconhecimento",
    titulo: "Espiral da Busca por Aprovação",
    categoria: "Esquema: Busca de Aprovação",
    abordagem: "Terapia do Esquema",
    publico: "adulto",
    objetivo: "Reconhecer o ciclo vicioso de condicionar seu bem-estar à aprovação dos outros, aceitar imperfeições e melhorar a autoestima de forma autônoma.",
    instrucoes: [
      "Avalie sua autoestima numa escala. O que está por trás dessa avaliação? Quais são os riscos?",
      "Espiral da aprovação: liste problemas, frustrações e dificuldades que surgem quando você espera se sentir bem ATRAVÉS dos outros.",
      "Observe o ciclo: busca por sucesso → reconhecimento → mas menos conexão afetiva → busca mais sucesso → ... Quando isso acontece com você?",
      "Faça uma lista hierárquica das coisas mais importantes na sua vida. Como espera que elas proporcionem amor e segurança?",
      "Aceitando imperfeições: liste-as. Como acha que os outros percebem? Eles também têm imperfeições? Pessoas que admira — como lidam com as delas?",
      "Se os outros têm imperfeições, você tem o mesmo direito? Descreva como pode lidar melhor com as suas, considerando aceitação.",
    ],
    referencia: "Schütz, N. T. (2023). Manual de Técnicas em Terapia do Esquema. Sinopsys Editora. Anexos 43-45, 33, 44.",
    tempoEstimado: "20-25 min",
  },
  {
    id: "te-negativismo-pessimismo",
    titulo: "Outros Pontos de Vista — Negativismo/Pessimismo",
    categoria: "Esquema: Negativismo",
    abordagem: "Terapia do Esquema",
    publico: "adulto",
    objetivo: "Ampliar perspectivas diante de situações difíceis, focando em recursos disponíveis e permitindo-se aproveitar eventos agradáveis.",
    instrucoes: [
      "Liste coisas que te incomodam atualmente. Para cada uma: por que acha que aconteceu? O quanto focar nisso te ajuda?",
      "Existe alguma lição importante? Como pessoas que você admira lidam com isso?",
      "Gere 3 outros pontos de vista sobre cada situação. Quais vantagens existem em avaliar mais perspectivas?",
      "Foco nos recursos: de um lado, liste perigos percebidos. Do outro, seus recursos para lidar com eles.",
      "Aproveitando eventos agradáveis: como você costuma lidar com coisas boas? Tem desvantagens na forma como lida? (Ex: minimizar, sabotar, esperar o pior.)",
      "Formas alternativas de lidar com eventos agradáveis + benefícios esperados. Planeje eventos agradáveis para testar.",
    ],
    referencia: "Schütz, N. T. (2023). Manual de Técnicas em Terapia do Esquema. Sinopsys Editora. Anexos 46-48, 51.",
    tempoEstimado: "20-25 min",
  },
  {
    id: "te-emaranhamento",
    titulo: "Quebra-Cabeça Relacional — Emaranhamento",
    categoria: "Esquema: Emaranhamento",
    abordagem: "Terapia do Esquema",
    publico: "adulto",
    objetivo: "Reconhecer a importância da independência emocional, definir o papel de cada pessoa na sua vida e monitorar como você se sente nos momentos de solidão.",
    instrucoes: [
      "Liste os benefícios da independência emocional na sua vida.",
      "Como você pode mostrar às pessoas emaranhadas a você que independência é saudável? Quando fará isso?",
      "Imagine um quebra-cabeça: cada peça representa uma pessoa da sua vida. Escreva o nome e a FUNÇÃO de cada pessoa, respeitando que cada peça é individual e tem seu lugar.",
      "Agora monitore seus momentos de solidão: em quais momentos do dia você fica sozinho(a)?",
      "Para cada momento: como se sente? Por que acha que se sente assim?",
      "Reflexão: solidão e estar sozinho(a) são coisas diferentes. Você consegue estar sozinho(a) e se sentir bem? O que ajudaria?",
    ],
    referencia: "Schütz, N. T. (2023). Manual de Técnicas em Terapia do Esquema. Sinopsys Editora. Anexos 26-28.",
    tempoEstimado: "20 min",
  },
  {
    id: "te-arrogo-grandiosidade",
    titulo: "Origens e Ciclos do Arrogo/Grandiosidade",
    categoria: "Esquema: Arrogo/Grandiosidade",
    abordagem: "Terapia do Esquema",
    publico: "adulto",
    objetivo: "Compreender a formação do esquema de arrogo/grandiosidade a partir da infância, identificar o ciclo sucesso-reconhecimento-vazio, e reconectar com o que realmente importa.",
    instrucoes: [
      "Quem eram seus cuidadores na infância? Descreva o perfil de cada um.",
      "Qual a ligação entre o perfil de cada cuidador e a formação do seu esquema? (Ex: mimaram excessivamente, trataram como especial, não impuseram limites.)",
      "Faça uma lista hierárquica das coisas MAIS IMPORTANTES na sua vida. Como espera que elas proporcionem amor e segurança?",
      "Observe o ciclo: Busca por sucesso → Reconhecimento → Menos conexão afetiva → Busca mais sucesso → ... Quando isso acontece com você?",
      "Como você foi privado(a) de frustrações na infância? Quem evitou essas frustrações? Como isso te prejudica hoje?",
      "Treinando gentileza: liste formas de ser gentil, frases gentis que pode usar, e ganhos que terá ao praticá-las.",
    ],
    referencia: "Schütz, N. T. (2023). Manual de Técnicas em Terapia do Esquema. Sinopsys Editora. Anexos 32-35, 34.",
    tempoEstimado: "25 min",
  },
  {
    id: "te-fracasso",
    titulo: "Fortalecendo a Autoeficácia — Fracasso",
    categoria: "Esquema: Fracasso",
    abordagem: "Terapia do Esquema",
    publico: "adulto",
    objetivo: "Ressignificar a relação com erros e fracassos, substituindo a autodepreciação por uma visão de crescimento e competência.",
    instrucoes: [
      "Liste situações em que você se descreve de forma depreciativa (ex: 'sou burro', 'nunca consigo', 'sou um fracasso').",
      "Reescreva cada situação considerando que você TERÁ eficácia ao passar por ela. (Ex: 'Eu posso aprender isso com prática e paciência.')",
      "Visão dos erros: qual visão você tem dos erros que cometeu até hoje?",
      "Liste os principais erros. Para cada um: quais fatores estavam envolvidos? O que você aprendeu graças a esse erro?",
      "Construa uma visão mais assertiva dos seus erros: eles foram 100% sua culpa? Havia variáveis fora do seu controle?",
      "Rotina de competência: liste atividades diárias que aumentam sua satisfação e senso de capacidade. Identifique obstáculos e estratégias para superá-los.",
    ],
    referencia: "Schütz, N. T. (2023). Manual de Técnicas em Terapia do Esquema. Sinopsys Editora. Anexos 29-31.",
    tempoEstimado: "20 min",
  },
  {
    id: "te-inibicao-emocional",
    titulo: "Conversa com Meus Dois Lados — Inibição Emocional",
    categoria: "Esquema: Inibição Emocional",
    abordagem: "Terapia do Esquema",
    publico: "adulto",
    objetivo: "Dialogar entre a parte que bloqueia as emoções e a parte que precisa expressá-las, criando um cartão de enfrentamento para se permitir sentir.",
    instrucoes: [
      "Identifique seus dois lados: o lado que bloqueia/esconde emoções e o lado que quer expressá-las.",
      "Dê voz ao lado que bloqueia: 'Eu não expresso porque...' — escreva todos os motivos.",
      "Dê voz ao lado que quer sentir: 'Eu preciso sentir porque...' — escreva a resposta.",
      "Pessoas que te invalidavam: quem eram? O que você precisa expressar que ficou guardado?",
      "Escreva como se fosse dizer a essas pessoas o que ficou preso. Como se sente agora?",
      "Crie seu cartão de enfrentamento emocional: 'Estou consciente de que emoções são ___. Elas me ajudam a ___. Os benefícios são ___. Quando alguma emoção estiver ativada, eu posso ___.'",
      "Eventos agradáveis: como você costuma lidar com coisas boas? Consegue aproveitá-las ou sabota? Liste formas alternativas de aproveitar.",
    ],
    referencia: "Schütz, N. T. (2023). Manual de Técnicas em Terapia do Esquema. Sinopsys Editora. Anexos 49-52.",
    tempoEstimado: "20-25 min",
  },
  {
    id: "te-xo-culpa",
    titulo: "Xô, Culpa! — Liberando-se da Culpa",
    categoria: "Esquema: Postura Punitiva",
    abordagem: "Terapia do Esquema",
    publico: "adulto",
    objetivo: "Distribuir responsabilidades de forma realista, questionando a culpa desproporcional e substituindo rótulos por descrições de comportamentos.",
    instrucoes: [
      "Explique sua culpa: descreva a situação que gera culpa em você.",
      "Quem são TODOS os responsáveis por essa situação? (Inclua outras pessoas, circunstâncias, contexto.)",
      "Distribua a responsabilidade: quanto (%) cada envolvido foi responsável? (A soma deve dar 100%.)",
      "Foi intencional? Você agiu com a intenção de causar mal?",
      "Pensamentos automáticos diante do erro: escreva-os. Agora liste variáveis que estavam FORA do seu controle.",
      "Construa uma visão mais equilibrada: dado o contexto completo, qual é uma forma mais justa de avaliar a situação?",
      "Rótulos: transforme rótulos negativos ('sou egoísta', 'sou irresponsável') em descrições de comportamentos específicos que ocorreram em um contexto específico.",
    ],
    referencia: "Schütz, N. T. (2023). Manual de Técnicas em Terapia do Esquema. Sinopsys Editora. Anexos 57-60.",
    tempoEstimado: "20 min",
  },

  // ========== TCC — Técnicas de Terapia Cognitiva (Leahy, 2ª ed.) ==========

  {
    id: "leahy-abc-distorcoes",
    titulo: "Técnica A-B-C e Distorções Cognitivas",
    categoria: "Identificação de Pensamentos",
    abordagem: "Terapia Cognitivo-Comportamental",
    publico: "adulto",
    objetivo: "Aprender a separar eventos de pensamentos e sentimentos, identificar pensamentos automáticos e reconhecer quais distorções cognitivas estão presentes.",
    instrucoes: [
      "Distinção evento-pensamento-sentimento: descreva uma situação recente que te incomodou. Separe: (A) o EVENTO (fato objetivo), (B) o PENSAMENTO que você teve, (C) o SENTIMENTO que surgiu.",
      "Avalie: qual emoção surgiu? De 0 a 100%, o quanto você acredita nesse pensamento?",
      "Agora liste OUTROS FATOS POSSÍVEIS que explicariam a mesma situação. Quantos cenários diferentes existem?",
      "Verifique distorções cognitivas presentes: leitura mental, catastrofização, filtro negativo, desqualificação do positivo, pensamento tudo-ou-nada, generalização, personalização, rotulação, 'deveria', raciocínio emocional, ampliação/minimização.",
      "Para cada distorção encontrada: escreva um exemplo de como ela apareceu no seu pensamento.",
      "Seta descendente: 'Se meu pensamento fosse verdade, por que isso me incomodaria?' Repita até chegar na crença central.",
      "Reavalie: após todo o exercício, de 0 a 100%, o quanto você ainda acredita no pensamento original?",
    ],
    exemplo: "Evento: colega não me cumprimentou. Pensamento: 'Ele me odeia' (crença: 85%). Sentimento: tristeza, rejeição. Distorções: leitura mental, personalização. Outros fatos: estava no celular, com pressa, não me viu. Seta descendente: 'Se ele me odeia → vou ficar sozinho → sou rejeitável.' Crença pós-exercício: 30%.",
    referencia: "Leahy, R. L. (2019). Técnicas de Terapia Cognitiva: Manual do Terapeuta (2ª ed.). Artmed. Formulários 2.1-2.11.",
    tempoEstimado: "20-25 min",
  },
  {
    id: "leahy-exame-evidencias",
    titulo: "Tribunal dos Pensamentos — Exame de Evidências",
    categoria: "Reestruturação Cognitiva",
    abordagem: "Terapia Cognitivo-Comportamental",
    publico: "adulto",
    objetivo: "Colocar um pensamento negativo 'no banco dos réus', examinando evidências a favor e contra, e atuando como seu próprio advogado de defesa.",
    instrucoes: [
      "Escreva o pensamento negativo que quer examinar. Avalie a crença de 0-100%.",
      "Defina os termos: o que exatamente você quer dizer? Outras pessoas usariam esses termos da mesma forma?",
      "Liste EVIDÊNCIAS A FAVOR do pensamento. São fatos concretos ou interpretações?",
      "Avalie a QUALIDADE dessas evidências: são baseadas em fatos ou sentimentos? São atuais ou antigas?",
      "Agora seja seu ADVOGADO DE DEFESA: liste todas as evidências CONTRA o pensamento.",
      "Suas contestações são relevantes? Elas realmente respondem ao pensamento negativo?",
      "Dramatize ambos os lados: escreva um diálogo entre a 'parte acusadora' e a 'parte defensora'. Quem tem argumentos mais fortes?",
      "Veredito: formule um pensamento alternativo mais equilibrado. Nova crença: ____%.",
    ],
    referencia: "Leahy, R. L. (2019). Técnicas de Terapia Cognitiva (2ª ed.). Artmed. Formulários 3.5-3.9.",
    tempoEstimado: "20 min",
  },
  {
    id: "leahy-custo-beneficio",
    titulo: "Análise de Custo-Benefício dos Pensamentos",
    categoria: "Reestruturação Cognitiva",
    abordagem: "Terapia Cognitivo-Comportamental",
    publico: "adulto",
    objetivo: "Avaliar se manter um pensamento ou crença traz mais custos ou benefícios para sua vida, no curto e no longo prazo.",
    instrucoes: [
      "Escreva o pensamento ou crença que quer avaliar.",
      "Divida uma folha em 4 quadrantes: Custos a curto prazo | Benefícios a curto prazo | Custos a longo prazo | Benefícios a longo prazo.",
      "Preencha cada quadrante honestamente.",
      "Avalie a validade: os benefícios são reais ou ilusórios? Os custos são evitáveis?",
      "Avalie rótulos negativos: se você rotula a si mesmo (ex: 'fracassado'), esse rótulo é uma descrição completa? Que variações existem? (Busca de variações: liste vezes em que o rótulo NÃO se aplicou.)",
      "Plano de ação: se os custos superam os benefícios, que comportamento concreto você pode modificar para mudar o pensamento?",
    ],
    referencia: "Leahy, R. L. (2019). Técnicas de Terapia Cognitiva (2ª ed.). Artmed. Formulários 3.3-3.4, 3.10-3.12.",
    tempoEstimado: "15-20 min",
  },
  {
    id: "leahy-regras-perfeccionismo",
    titulo: "Desafiando Regras Internas e Perfeccionismo",
    categoria: "Pressupostos e Regras",
    abordagem: "Terapia Cognitivo-Comportamental",
    publico: "adulto",
    objetivo: "Identificar pressupostos, regras do tipo 'deveria' e padrões perfeccionistas que geram sofrimento, transformando-os em diretrizes mais flexíveis.",
    instrucoes: [
      "Liste suas regras internas: 'Eu deveria ___', 'Eu preciso ___', 'Se eu não ___, então ___.'",
      "Para cada 'deveria': quem te ensinou isso? É uma preferência ou um mandamento universal? O que acontece se você não cumprir?",
      "Identifique crenças condicionais: 'Se eu ___, então ___.' Essas conexões são reais ou assumidas?",
      "Inventário de perfeccionismo: em quais áreas você exige perfeição? Quais são os custos e benefícios de buscar perfeição vs. buscar PROGRESSO?",
      "Transforme antigas regras em novas: (Antiga) 'Devo ser perfeito em tudo' → (Nova) 'Posso buscar melhorar sem me punir por não ser perfeito.'",
      "Escreva sua NOVA DECLARAÇÃO DE DIREITOS: liste 5 direitos que você merece ter (ex: 'Tenho direito de errar', 'Tenho direito de dizer não').",
      "Clarificação de valores: o que realmente importa para você? Suas regras estão alinhadas com seus valores ou contra eles?",
    ],
    referencia: "Leahy, R. L. (2019). Técnicas de Terapia Cognitiva (2ª ed.). Artmed. Formulários 4.1-4.13.",
    tempoEstimado: "25-30 min",
  },
  {
    id: "leahy-erros-logica",
    titulo: "Detetive de Erros Lógicos",
    categoria: "Processamento de Informação",
    abordagem: "Terapia Cognitivo-Comportamental",
    publico: "adulto",
    objetivo: "Identificar vieses cognitivos e erros de lógica que distorcem como você processa informações e toma conclusões.",
    instrucoes: [
      "Viés de confirmação: você só busca informações que confirmam o que já acredita? Liste evidências que IGNOROU por não encaixarem na sua conclusão.",
      "Utilize TODAS as informações: para sua situação atual, liste tudo que sabe — não apenas o que confirma o negativo.",
      "Estimativa de probabilidade: qual a chance REAL (%) de que o pior cenário aconteça? Baseado em quê?",
      "Erros de lógica: examine se há (a) conclusões tiradas sem dados suficientes, (b) confusão entre correlação e causa, (c) generalização de um caso para todos.",
      "Falsas dicotomias: você está pensando em termos de tudo-ou-nada? Quais são os tons de cinza entre os extremos?",
      "Teste do absurdo: leve seu pensamento ao extremo lógico. Se fosse 100% verdade, o que aconteceria? Faz sentido?",
      "Efeito de recenticidade: você está dando peso excessivo ao que aconteceu mais recentemente, ignorando todo o histórico?",
    ],
    referencia: "Leahy, R. L. (2019). Técnicas de Terapia Cognitiva (2ª ed.). Artmed. Formulários 5.1-5.10.",
    tempoEstimado: "20 min",
  },
  {
    id: "leahy-tomada-decisao",
    titulo: "Tomada de Decisão Consciente",
    categoria: "Tomada de Decisão",
    abordagem: "Terapia Cognitivo-Comportamental",
    publico: "adulto",
    objetivo: "Melhorar a qualidade das suas decisões, evitando armadilhas cognitivas como custos irrecuperáveis, aversão à perda e decisões baseadas em humor.",
    instrucoes: [
      "Defina seus objetivos de curto prazo (próximos 30 dias) e de longo prazo (próximo ano). Suas decisões atuais estão alinhadas?",
      "Custos não recuperáveis: você está mantendo algo (relacionamento, emprego, projeto) só porque 'já investiu muito'? O que faria se começasse do zero hoje?",
      "Humor e decisão: está tomando esta decisão num momento de emoção intensa? Como se sentiria sobre ela daqui a 1 semana? 1 mês? 1 ano?",
      "Perdas vs. ganhos: você está focando mais no que pode PERDER do que no que pode GANHAR? Liste ambos.",
      "Decisão pelo self atual E futuro: o que seu 'eu do futuro' gostaria que você decidisse agora?",
      "Liste atividades recompensadoras: passadas (que já funcionaram), presentes (que pratica), e futuras (que quer começar).",
      "Comprometa-se: escreva sua decisão e um primeiro passo concreto para HOJE.",
    ],
    referencia: "Leahy, R. L. (2019). Técnicas de Terapia Cognitiva (2ª ed.). Artmed. Formulários 6.1-6.10.",
    tempoEstimado: "20-25 min",
  },
  {
    id: "leahy-desapego-consciente",
    titulo: "Desapego Consciente — Mindfulness de Pensamentos",
    categoria: "Mindfulness / Desapego",
    abordagem: "Terapia Cognitivo-Comportamental / 3ª Onda",
    publico: "adulto",
    objetivo: "Aprender a observar pensamentos sem se fundir com eles — como nuvens passando no céu — reduzindo o poder que exercem sobre suas emoções.",
    instrucoes: [
      "Desapego consciente: observe seu pensamento perturbador. Em vez de discutir com ele, apenas note: 'Estou tendo o pensamento de que ___.'",
      "Não atenda a ligação: imagine que o pensamento é um telefone tocando. Você não é obrigado a atender. Deixe tocar.",
      "Balão de pensamentos: imagine o pensamento dentro de um balão de quadrinhos flutuando sobre sua cabeça. Observe-o de fora.",
      "Pensamentos vs. realidade: 'Esse pensamento é um FATO ou é uma produção da minha mente?' Liste a diferença.",
      "O pensamento visitante: imagine que o pensamento é um visitante indesejado na porta. Você pode reconhecer que está ali sem convidá-lo pra entrar.",
      "Respostas problemáticas: quando tem um pensamento indesejado, você tenta (a) suprimir, (b) ruminar, (c) neutralizar? Qual o resultado de cada?",
      "Técnica tédio: repita o pensamento perturbador em voz alta ou mentalmente, devagar, por 2 minutos seguidos. Perceba como ele vai perdendo força.",
    ],
    referencia: "Leahy, R. L. (2019). Técnicas de Terapia Cognitiva (2ª ed.). Artmed. Formulários 7.1-7.9.",
    tempoEstimado: "15-20 min",
  },
  {
    id: "leahy-preocupacao",
    titulo: "Domando a Preocupação — Produtiva vs. Improdutiva",
    categoria: "Preocupação e Ruminação",
    abordagem: "Terapia Cognitivo-Comportamental",
    publico: "adulto",
    objetivo: "Distinguir preocupações que levam a ações (produtivas) das que só geram sofrimento (improdutivas), e desenvolver estratégias específicas para cada tipo.",
    instrucoes: [
      "Automonitoramento: registre suas preocupações do dia. Para cada uma, anote: tema, frequência, intensidade (0-10), o que fez a respeito.",
      "Custos e benefícios de se preocupar: preocupar-se te ajuda a resolver ou só te paralisa?",
      "Classifique cada preocupação: PRODUTIVA (posso agir agora) ou IMPRODUTIVA (não posso controlar / é sobre o futuro incerto)?",
      "Para produtivas: transforme em previsões testáveis. 'O que especificamente acho que vai acontecer?' Teste e registre o resultado real.",
      "Para improdutivas: pratique a técnica 'Tempo da Preocupação' — adie preocupações para um horário fixo de 20 min. Fora dele, anote e guarde.",
      "Revise previsões passadas: quantas se concretizaram? Por que não aprendemos com isso?",
      "Inundação com incerteza: repita 'É possível que ___' até que a incerteza perca o poder emocional.",
      "Máquina do tempo: imagine-se daqui a 5 anos olhando para esta preocupação. Qual a importância real dela?",
    ],
    referencia: "Leahy, R. L. (2019). Técnicas de Terapia Cognitiva (2ª ed.). Artmed. Formulários 8.1-8.24.",
    tempoEstimado: "25-30 min",
  },
  {
    id: "leahy-torta-continuum",
    titulo: "Gráfico de Torta e Continuum",
    categoria: "Reatribuição / Perspectiva",
    abordagem: "Terapia Cognitivo-Comportamental",
    publico: "adulto",
    objetivo: "Redistribuir responsabilidade e percepções usando técnicas visuais que ampliam a perspectiva e reduzem o pensamento polarizado.",
    instrucoes: [
      "Gráfico de torta: para uma situação que te incomoda, liste TODOS os fatores que contribuíram (incluindo outros, circunstâncias, acaso). Distribua 100% entre eles. Quanto sobrou pra você?",
      "Continuum: em vez de 'sou X ou não sou X', coloque a qualidade num continuum de 0-100. Onde você se posiciona? Onde posiciona outras pessoas? Isso muda a perspectiva?",
      "'O que ainda posso fazer': mesmo na pior das hipóteses, o que AINDA está ao seu alcance?",
      "Comparações com o ponto zero: em vez de comparar com o ideal, compare com o 'ponto zero' (não ter nada). O quanto você avançou?",
      "Despolarize comparações: em vez de 'fulano é melhor que eu', liste 10 qualidades — em quantas você é melhor? Em quantas ele é?",
      "Como outros lidaram: pense em alguém que passou por algo parecido. Como essa pessoa lidou? O que você pode aprender?",
      "Viagem ao futuro: imagine-se daqui a 1, 5, 10 anos. Como verá esta situação? Que oportunidades podem surgir dela?",
    ],
    referencia: "Leahy, R. L. (2019). Técnicas de Terapia Cognitiva (2ª ed.). Artmed. Formulários 9.1-9.12.",
    tempoEstimado: "20 min",
  },
  {
    id: "leahy-esquemas-personalidade",
    titulo: "Identificando e Transcendendo Esquemas Pessoais",
    categoria: "Esquemas e Crenças Centrais",
    abordagem: "Terapia Cognitivo-Comportamental",
    publico: "adulto",
    objetivo: "Reconhecer padrões repetitivos de pensamento e comportamento (esquemas), entender suas origens e desenvolver motivação para modificá-los.",
    instrucoes: [
      "Examine padrões problemáticos: quais situações se repetem na sua vida? (Ex: sempre atrair os mesmos tipos de relacionamento, sempre sabotar conquistas.)",
      "Identifique seus esquemas: qual crença central sobre si mesmo está por trás? (Ex: 'Sou inadequado', 'Não mereço amor', 'O mundo é perigoso.')",
      "Esquiva e compensação: como você EVITA ativar o esquema? Como COMPENSA? (Ex: evita intimidade para não ser rejeitado; trabalha excessivamente para não se sentir fracassado.)",
      "Lembranças precoces: quais memórias da infância estão ligadas a esse esquema?",
      "Carta à fonte: escreva uma carta (que não precisa enviar) à pessoa ou situação que originou o esquema. Diga o que precisava ouvir.",
      "Contestação: liste 3 evidências que contradizem seu esquema. O esquema é a realidade completa?",
      "Vida por lentes diferentes: como seria sua vida se você operasse a partir de um esquema POSITIVO? (Ex: 'Sou capaz e digno de amor.') Descreva um dia típico.",
      "Motivação: liste razões concretas para modificar este esquema. O que você ganha mantendo-o? O que ganha transcendendo-o?",
    ],
    referencia: "Leahy, R. L. (2019). Técnicas de Terapia Cognitiva (2ª ed.). Artmed. Formulários 10.1-10.11.",
    tempoEstimado: "30 min",
  },
  {
    id: "leahy-processamento-emocional",
    titulo: "Diário de Emoções e Esquemas Emocionais",
    categoria: "Processamento Emocional",
    abordagem: "Terapia Cognitivo-Comportamental / Esquemas Emocionais",
    publico: "adulto",
    objetivo: "Identificar emoções evitadas, crenças sobre emoções (esquemas emocionais) e desenvolver maior aceitação e processamento emocional.",
    instrucoes: [
      "Diário de emoções: registre situação, emoção, intensidade (0-100), pensamentos associados, e resposta (o que fez).",
      "Emoções que evito: quais emoções você tem dificuldade de sentir ou expressar? O que aconteceria se as sentisse plenamente?",
      "Identifique pontos de tensão no corpo: onde você 'guarda' cada emoção? (Ex: ansiedade no peito, raiva no maxilar.)",
      "Esquemas emocionais: quais crenças você tem SOBRE suas emoções? (Ex: 'Se eu chorar, vou perder o controle', 'Raiva é inaceitável', 'Tristeza é fraqueza.')",
      "Aceitação: 'Faz sentido eu sentir ___ porque ___.' Valide sua emoção sem julgá-la.",
      "Reformulação da história: reescreva uma experiência emocional difícil de uma perspectiva de aceitação e crescimento.",
      "Ação baseada em valores: em vez de agir para ESCAPAR da emoção, como você pode agir de acordo com seus VALORES mesmo sentindo desconforto?",
    ],
    referencia: "Leahy, R. L. (2019). Técnicas de Terapia Cognitiva (2ª ed.). Artmed. Formulários 11.1-11.11.",
    tempoEstimado: "20-25 min",
  },
];
