export interface FerramentaTerapeuta {
  id: string;
  titulo: string;
  categoria: string;
  campos: { label: string; tipo: "texto" | "area" | "lista" }[];
  referencia: string;
}

export const ferramentas: FerramentaTerapeuta[] = [
  {
    id: "formulacao-caso",
    titulo: "Formulação do Caso e Testagem de Hipóteses",
    categoria: "Conceituação",
    campos: [
      { label: "Nome do paciente", tipo: "texto" },
      { label: "Data", tipo: "texto" },
      { label: "1. Diagnóstico do cliente", tipo: "area" },
      { label: "2. Problemas atuais — como se desenvolveram e como são mantidos", tipo: "area" },
      { label: "3. Pensamentos e crenças disfuncionais associados (reações emocionais, fisiológicas e comportamentais)", tipo: "area" },
      { label: "4a. Como o cliente vê a SI MESMO", tipo: "area" },
      { label: "4b. Como o cliente vê OS OUTROS", tipo: "area" },
      { label: "4c. Como o cliente vê SEU FUTURO", tipo: "area" },
    ],
    referencia: "Formulação do Caso e Testagem de Hipóteses — Processos Básicos.",
  },
  {
    id: "conceituacao-cognitiva",
    titulo: "Diagrama de Conceituação Cognitiva",
    categoria: "Conceituação",
    campos: [
      { label: "Dados relevantes da história", tipo: "area" },
      { label: "Crença Central", tipo: "texto" },
      { label: "Crenças Intermediárias (pressupostos, regras, atitudes)", tipo: "area" },
      { label: "Estratégias Compensatórias", tipo: "area" },
      { label: "Situação 1", tipo: "texto" },
      { label: "Pensamento Automático (Sit. 1)", tipo: "texto" },
      { label: "Significado do PA (Sit. 1)", tipo: "texto" },
      { label: "Resposta Emocional (Sit. 1)", tipo: "texto" },
      { label: "Resposta Física (Sit. 1)", tipo: "texto" },
      { label: "Comportamento (Sit. 1)", tipo: "texto" },
      { label: "Situação 2", tipo: "texto" },
      { label: "Pensamento Automático (Sit. 2)", tipo: "texto" },
      { label: "Significado do PA (Sit. 2)", tipo: "texto" },
      { label: "Resposta Emocional (Sit. 2)", tipo: "texto" },
      { label: "Resposta Física (Sit. 2)", tipo: "texto" },
      { label: "Comportamento (Sit. 2)", tipo: "texto" },
    ],
    referencia: "Diagrama de Conceituação Cognitiva — Judith Beck.",
  },
  {
    id: "conceituacao-esquema",
    titulo: "Conceituação — Terapia do Esquema",
    categoria: "Conceituação",
    campos: [
      { label: "Necessidades emocionais não supridas na infância (origem)", tipo: "area" },
      { label: "Esquemas Iniciais Desadaptativos (EIDs) identificados", tipo: "area" },
      { label: "Estilo de Enfrentamento predominante (Rendição / Evitação / Supercompensação)", tipo: "texto" },
      { label: "Situação 1", tipo: "texto" },
      { label: "Modo de Esquema ativado (Sit. 1)", tipo: "texto" },
      { label: "Pensamento (Sit. 1)", tipo: "texto" },
      { label: "Resposta Emocional (Sit. 1)", tipo: "texto" },
      { label: "Resposta Comportamental (Sit. 1)", tipo: "texto" },
      { label: "Situação 2", tipo: "texto" },
      { label: "Modo de Esquema ativado (Sit. 2)", tipo: "texto" },
      { label: "Pensamento (Sit. 2)", tipo: "texto" },
      { label: "Resposta Emocional (Sit. 2)", tipo: "texto" },
      { label: "Resposta Comportamental (Sit. 2)", tipo: "texto" },
      { label: "Padrão relacional/vincular geral", tipo: "area" },
    ],
    referencia: "Terapia do Esquema — Jeffrey Young.",
  },
  {
    id: "conceituacao-funcional",
    titulo: "Conceituação Funcional (ABC)",
    categoria: "Conceituação",
    campos: [
      { label: "Comportamento-alvo", tipo: "texto" },
      { label: "Função hipotética (fuga/esquiva, atenção, reforço tangível, autorregulação)", tipo: "area" },
      { label: "Situação 1 — Antecedente", tipo: "texto" },
      { label: "Situação 1 — Comportamento", tipo: "texto" },
      { label: "Situação 1 — Consequência (o que mantém)", tipo: "texto" },
      { label: "Situação 2 — Antecedente", tipo: "texto" },
      { label: "Situação 2 — Comportamento", tipo: "texto" },
      { label: "Situação 2 — Consequência", tipo: "texto" },
      { label: "Consequências de longo prazo / custo do padrão", tipo: "area" },
    ],
    referencia: "Análise Funcional do Comportamento — modelo ABC.",
  },
  {
    id: "conceituacao-act",
    titulo: "Conceituação ACT (Hexaflex)",
    categoria: "Conceituação",
    campos: [
      { label: "Valores identificados", tipo: "area" },
      { label: "Ação comprometida (passos práticos)", tipo: "area" },
      { label: "Fusão cognitiva (pensamentos aos quais está fundido)", tipo: "area" },
      { label: "Esquiva experiencial (do que foge)", tipo: "area" },
      { label: "Self conceitualizado (história que conta sobre si)", tipo: "area" },
      { label: "Situação 1 — gatilho", tipo: "texto" },
      { label: "Situação 1 — reação de inflexibilidade", tipo: "texto" },
      { label: "Situação 1 — custo", tipo: "texto" },
      { label: "Situação 2 — gatilho", tipo: "texto" },
      { label: "Situação 2 — reação de inflexibilidade", tipo: "texto" },
      { label: "Situação 2 — custo", tipo: "texto" },
    ],
    referencia: "Terapia de Aceitação e Compromisso — modelo Hexaflex (Steven Hayes).",
  },
  {
    id: "conceituacao-processos",
    titulo: "Conceituação — Processos (EEMM/Hayes)",
    categoria: "Conceituação",
    campos: [
      { label: "Processo Afetivo", tipo: "area" },
      { label: "Processo Cognitivo", tipo: "area" },
      { label: "Processo Atencional", tipo: "area" },
      { label: "Processo do Self", tipo: "area" },
      { label: "Processo Motivacional", tipo: "area" },
      { label: "Processo Comportamental", tipo: "area" },
      { label: "Hipótese do processo central de manutenção", tipo: "area" },
    ],
    referencia: "Terapia Baseada em Processos — EEMM (Steven Hayes).",
  },
  {
    id: "formulacao-sistemica",
    titulo: "Formulação de Caso Sistêmica (CTC Veda)",
    categoria: "Conceituação",
    campos: [
      { label: "Paciente / Idade", tipo: "texto" },
      { label: "Fatores de vulnerabilidade", tipo: "area" },
      { label: "Formulação cultural", tipo: "area" },
      { label: "Experiências tardias", tipo: "area" },
      { label: "Crenças / regras e pressupostos", tipo: "area" },
      { label: "Histórico de vida relevante", tipo: "area" },
      { label: "Gatilhos", tipo: "area" },
      { label: "Fatores precipitantes / incidentes críticos", tipo: "area" },
      { label: "Modificadores", tipo: "area" },
      { label: "Fatores de manutenção", tipo: "area" },
      { label: "Pensamentos", tipo: "area" },
      { label: "Emoções", tipo: "area" },
      { label: "Comportamentos", tipo: "area" },
      { label: "Reações fisiológicas", tipo: "area" },
      { label: "Pontos fortes e recursos", tipo: "area" },
      { label: "Metas do tratamento", tipo: "area" },
      { label: "Obstáculos ao tratamento", tipo: "area" },
    ],
    referencia: "Nicoletti, E. A. et al. (2022). Guia Prático de Formulação de Casos em TCC. Sinopsys.",
  },
  {
    id: "formulacao-infantojuvenil",
    titulo: "Formulação de Caso — Crianças e Adolescentes (CTC Veda)",
    categoria: "Conceituação",
    campos: [
      { label: "Paciente / Idade", tipo: "texto" },
      { label: "Fatores de vulnerabilidade (biológicos, ambientais, sociais)", tipo: "area" },
      { label: "Fatores culturais", tipo: "area" },
      { label: "Crenças centrais (sobre si, outros, mundo, pais)", tipo: "area" },
      { label: "Pressupostos e regras", tipo: "area" },
      { label: "Gatilhos situacionais", tipo: "area" },
      { label: "Dificuldades atuais", tipo: "area" },
      { label: "Fatores precipitantes", tipo: "area" },
      { label: "Modificadores de curso", tipo: "area" },
      { label: "Pensamentos da criança/adolescente", tipo: "area" },
      { label: "Emoções", tipo: "area" },
      { label: "Reações fisiológicas", tipo: "area" },
      { label: "Figura Parental 1 — pensamentos/crenças sobre si e sobre a criança", tipo: "area" },
      { label: "Figura Parental 1 — emoções e comportamentos/manejo", tipo: "area" },
      { label: "Figura Parental 2 — pensamentos/crenças sobre si e sobre a criança", tipo: "area" },
      { label: "Figura Parental 2 — emoções e comportamentos/manejo", tipo: "area" },
      { label: "Respostas do ambiente (social, escolar)", tipo: "area" },
      { label: "Fatores de manutenção", tipo: "area" },
      { label: "Objetivos do tratamento", tipo: "area" },
      { label: "Pontos fortes e recursos", tipo: "area" },
      { label: "Obstáculos", tipo: "area" },
    ],
    referencia: "Nicoletti, E. A. et al. (2022). Guia Prático de Formulação de Casos em TCC. Sinopsys.",
  },
  {
    id: "plano-tratamento",
    titulo: "Plano de Tratamento",
    categoria: "Planejamento",
    campos: [
      { label: "Meta 1 — O que trabalhar", tipo: "texto" },
      { label: "Meta 1 — Por que trabalhar primeiro", tipo: "area" },
      { label: "Meta 1 — Como trabalhar (ferramentas)", tipo: "area" },
      { label: "Meta 2 — O que trabalhar", tipo: "texto" },
      { label: "Meta 2 — Por que trabalhar primeiro", tipo: "area" },
      { label: "Meta 2 — Como trabalhar (ferramentas)", tipo: "area" },
      { label: "Meta 3 — O que trabalhar", tipo: "texto" },
      { label: "Meta 3 — Por que trabalhar primeiro", tipo: "area" },
      { label: "Meta 3 — Como trabalhar (ferramentas)", tipo: "area" },
    ],
    referencia: "Nicoletti, E. A. et al. (2022). Guia Prático de Formulação de Casos em TCC. Sinopsys.",
  },
  {
    id: "checklist-metas-casais",
    titulo: "Checklist de Metas para Tratamento de Casais",
    categoria: "Avaliação — Casais",
    campos: [
      { label: "Metas selecionadas (marque todas aplicáveis)", tipo: "lista" },
      { label: "Problemas identificados", tipo: "area" },
      { label: "Objetivos para cada problema", tipo: "area" },
      { label: "Passos específicos para alcançar cada objetivo", tipo: "area" },
    ],
    referencia: "Ludgate, J. W. & Grubr, T. N. (2025). Guia de Ferramentas da TCC para Casais. Sinopsys.",
  },
];
